#!/usr/bin/env python3
import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
P = ROOT / "data" / "data_products.csv"
D = ROOT / "data" / "product_distributions.csv"
TODAY = "2026-08-15"

products = [
["DP000119","DR0074","Hidrogeologia 1:250.000 — cartas e mapas regionais","Hidrogeologia 1:250.000","Mapas Ambientais — Hidrogeologia","map_layer_collection","Coleção oficial do IBGE de cartas hidrogeológicas e mapas regionais que representam sistemas aquíferos, potencialidades, vulnerabilidade e condições de ocorrência de águas subterrâneas; a página atual reúne cartas 1:250.000 e produtos para Nordeste, Sudeste e Sul.","Hydrogeology | Geology | Water resources | Environmental mapping","hidrogeologia | aquíferos | água subterrânea | potencialidade | vulnerabilidade | IBGE","Brasil parcial — regiões Nordeste, Sudeste e Sul e cartas conforme recortes disponíveis","parcial","cartas temáticas | mapas regionais | base espacial","1:250.000 nas cartas; escalas próprias nos mapas regionais","levantamentos e edições históricas; produtos regionais disponíveis na página oficial","por edição cartográfica","irregular","ativo","coleção oficial corrente; produtos regionais históricos","family_level","https://www.ibge.gov.br/geociencias/informacoes-ambientais/geologia/15824-hidrogeologia.html","https://www.ibge.gov.br/geociencias/informacoes-ambientais/geologia/15824-hidrogeologia.html","derivado","A coleção não constitui cobertura nacional homogênea em uma única escala ou data. Registrar mapa, recorte, escala, edição e fonte dos dados de poços efetivamente usados.",TODAY],
["DP000120","DR0074","Geologia por Estado — mapas temáticos do IBGE","Geologia por Estado","Mapas Ambientais por Unidade da Federação","map_layer_collection","Coleção oficial de mapas geológicos em diferentes escalas com recortes por Unidade da Federação, disponibilizada pelo IBGE para estados selecionados.","Geology | Geosciences | Environmental mapping","geologia | mapas estaduais | unidades da federação | cartografia temática | IBGE","Acre, Amapá, Amazonas, Maranhão, Mato Grosso, Pará, Rondônia, Roraima e Tocantins conforme página oficial","parcial","mapas por Unidade da Federação","varia por estado e edição","edições históricas variáveis por estado","por edição cartográfica","irregular","ativo","coleção por estado disponível no portal","family_level","https://www.ibge.gov.br/geociencias/cartas-e-mapas/mapas-estaduais/15823-geologia-do-estado-ro-rr-to-ac-am-ap-ma-mt-e-pa.html","https://www.ibge.gov.br/geociencias/cartas-e-mapas/mapas-estaduais/15823-geologia-do-estado-ro-rr-to-ac-am-ap-ma-mt-e-pa.html","derivado","Escalas, datas, métodos e detalhamento variam entre estados. Não mosaicar ou comparar como cobertura nacional uniforme sem harmonização cartográfica e metodológica.",TODAY],
["DP000121","DR0074","Geomorfologia por Estado — mapas temáticos do IBGE","Geomorfologia por Estado","Mapas Ambientais por Unidade da Federação","map_layer_collection","Coleção oficial de mapas geomorfológicos em diferentes escalas com recortes por Unidade da Federação, representando formas e compartimentos do relevo em estados selecionados.","Geomorphology | Physical geography | Environmental mapping","geomorfologia | relevo | mapas estaduais | unidades da federação | IBGE","Acre, Amapá, Amazonas, Maranhão, Mato Grosso, Pará, Rondônia, Roraima e Tocantins conforme página oficial","parcial","mapas por Unidade da Federação","varia por estado e edição","edições históricas variáveis por estado","por edição cartográfica","irregular","ativo","coleção por estado disponível no portal","family_level","https://www.ibge.gov.br/geociencias/cartas-e-mapas/mapas-estaduais/16028-geomorfologia-do-estado-de-ro-rr-to-ac-am-ma-mt-e-pa.html","https://www.ibge.gov.br/geociencias/cartas-e-mapas/mapas-estaduais/16028-geomorfologia-do-estado-de-ro-rr-to-ac-am-ma-mt-e-pa.html","derivado","Escalas, legendas, datas e métodos variam entre estados. As unidades geomorfológicas devem ser interpretadas na escala e na edição originais.",TODAY],
["DP000122","DR0074","Pedologia por Estado — mapas exploratórios de solos do IBGE","Pedologia por Estado","Mapas Ambientais por Unidade da Federação","map_layer_collection","Coleção oficial de mapas exploratórios de solos em diferentes escalas, com recortes por Unidade da Federação e downloads separados por estado.","Soil science | Geosciences | Environmental mapping","pedologia | solos | mapas estaduais | unidades da federação | levantamento exploratório | IBGE","estados selecionados, incluindo Acre, Amapá, Amazonas, Maranhão, Mato Grosso, Pará, Rio Grande do Sul, Rondônia, Roraima e Tocantins conforme acesso oficial","parcial","mapas por Unidade da Federação","varia por estado e edição","edições históricas variáveis por estado","por edição cartográfica","irregular","ativo","coleção exploratória por estado disponível no portal","family_level","https://www.ibge.gov.br/geociencias/cartas-e-mapas/mapas-estaduais/15828-pedologia-do-estado-de-ro-rr-to-ac-am-ap-ma-mt-pa-e-rs.html","https://www.ibge.gov.br/geociencias/cartas-e-mapas/mapas-estaduais/15828-pedologia-do-estado-de-ro-rr-to-ac-am-ap-ma-mt-pa-e-rs.html","derivado","São mapas exploratórios e heterogêneos em escala e data; não equivalem a levantamento pedológico detalhado ou cobertura nacional contemporânea.",TODAY],
["DP000123","DR0074","Vegetação por Estado — mapas temáticos do IBGE","Vegetação por Estado","Mapas Ambientais por Unidade da Federação","map_layer_collection","Coleção oficial de mapas de vegetação em diferentes escalas com recortes por Unidade da Federação para estados selecionados.","Vegetation science | Biogeography | Ecology | Environmental mapping","vegetação | fitogeografia | mapas estaduais | unidades da federação | IBGE","Acre, Amapá, Amazonas, Maranhão, Mato Grosso, Pará, Rondônia, Roraima e Tocantins conforme página oficial","parcial","mapas por Unidade da Federação","varia por estado e edição","edições históricas variáveis por estado","por edição cartográfica","irregular","ativo","coleção por estado disponível no portal","family_level","https://www.ibge.gov.br/geociencias/informacoes-ambientais/vegetacao/22460-vegetacao-por-estado.html?lang=pt-BR","https://www.ibge.gov.br/geociencias/informacoes-ambientais/vegetacao/22460-vegetacao-por-estado.html?lang=pt-BR","derivado","A coleção reúne mapas de diferentes épocas e escalas e não deve ser confundida com cobertura e uso da terra observados numa data comum ou com uma série temporal harmonizada.",TODAY],
["DP000124","DR0073","Sistema Brasileiro de Classificação de Relevo — publicações e desenvolvimento","SBCR","Sistema Brasileiro de Classificação de Relevo","catalog","Ambiente oficial do Sistema Brasileiro de Classificação de Relevo, iniciativa do IBGE com SGB/CPRM, UGB e pesquisadores para desenvolver uma estrutura taxonômica comum, padronizar conceitos e recomendar a representação do relevo brasileiro; reúne workshops, reuniões, excursões técnicas e publicações do desenvolvimento do sistema.","Geomorphology | Physical geography | Geoscience methodology","SBCR | classificação do relevo | taxonomia | geomorfologia | padronização | IBGE | SGB | UGB","Brasil","sim","sistema classificatório | relatórios | publicações técnicas","não se aplica como resolução espacial única","desenvolvimento contínuo desde 2020; publicações verificadas até 2026","por publicação ou etapa de desenvolvimento","irregular","ativo","4º Workshop / publicações disponíveis em 2026","external_index","https://www.ibge.gov.br/geociencias/informacoes-ambientais/geomorfologia/28098-sistema-brasileiro-de-classificacao-de-relevo.html","https://www.ibge.gov.br/geociencias/informacoes-ambientais/geomorfologia/28098-sistema-brasileiro-de-classificacao-de-relevo.html","agregador","O SBCR é um sistema classificatório em desenvolvimento e um conjunto de publicações técnicas, não uma camada observacional única. Versões e recomendações devem ser citadas conforme a publicação utilizada.",TODAY],
]

dists = [
["DD000135","DP000119","Hidrogeologia 1:250.000 — acesso oficial e downloads","https://www.ibge.gov.br/geociencias/informacoes-ambientais/geologia/15824-hidrogeologia.html","mapas e arquivos geoespaciais; formatos variam por item","HTTPS / download","navegador web","sim","não","seleção manual por carta, estado ou região conforme item","licença específica dos arquivos não confirmada nesta auditoria; observar termos do IBGE","desconhecido","por carta/recorte disponível","A página oficial separa cartas 1:250.000, mapas estaduais e mapas regionais; não generalizar escala ou formato entre itens.",TODAY],
["DD000136","DP000120","Geologia por Estado — downloads oficiais","https://www.ibge.gov.br/geociencias/cartas-e-mapas/mapas-estaduais/15823-geologia-do-estado-ro-rr-to-ac-am-ap-ma-mt-e-pa.html","mapas e arquivos para download; formato varia por estado","HTTPS / download","navegador web","sim","não","seleção manual por Unidade da Federação","licença específica dos arquivos não confirmada nesta auditoria; observar termos do IBGE","desconhecido","por estado","Página oficial oferece acesso separado por estado; verificar formato, escala e edição do arquivo escolhido.",TODAY],
["DD000137","DP000121","Geomorfologia por Estado — downloads oficiais","https://www.ibge.gov.br/geociencias/cartas-e-mapas/mapas-estaduais/16028-geomorfologia-do-estado-de-ro-rr-to-ac-am-ma-mt-e-pa.html","mapas e arquivos para download; formato varia por estado","HTTPS / download","navegador web","sim","não","seleção manual por Unidade da Federação","licença específica dos arquivos não confirmada nesta auditoria; observar termos do IBGE","desconhecido","por estado","Página oficial oferece acesso separado por estado; preservar escala, legenda e edição do item usado.",TODAY],
["DD000138","DP000122","Pedologia por Estado — downloads oficiais","https://www.ibge.gov.br/geociencias/cartas-e-mapas/mapas-estaduais/15828-pedologia-do-estado-de-ro-rr-to-ac-am-ap-ma-mt-pa-e-rs.html","mapas e arquivos para download; formato varia por estado","HTTPS / download","navegador web","sim","não","seleção manual por Unidade da Federação","licença específica dos arquivos não confirmada nesta auditoria; observar termos do IBGE","desconhecido","por estado","Coleção exploratória; verificar escala, ano, legenda e formato do arquivo selecionado.",TODAY],
["DD000139","DP000123","Vegetação por Estado — downloads oficiais","https://www.ibge.gov.br/geociencias/informacoes-ambientais/vegetacao/22460-vegetacao-por-estado.html?lang=pt-BR","mapas e arquivos para download; formato varia por estado","HTTPS / download","navegador web","sim","não","seleção manual por Unidade da Federação","licença específica dos arquivos não confirmada nesta auditoria; observar termos do IBGE","desconhecido","por estado","Página oficial oferece acesso por estado; verificar escala, data, legenda e formato do item selecionado.",TODAY],
["DD000140","DP000124","SBCR — publicações, relatórios e materiais técnicos","https://www.ibge.gov.br/geociencias/informacoes-ambientais/geomorfologia/28098-sistema-brasileiro-de-classificacao-de-relevo.html","HTML | PDF e publicações conforme edição","HTTPS","navegador web","sim","não","consulta por edição, workshop, reunião ou excursão técnica","licença específica de cada publicação deve ser verificada no item","desconhecido","por publicação","A página é um índice institucional de documentos do desenvolvimento do SBCR; não representa distribuição de uma camada geoespacial única.",TODAY],
]

def read_ids(path, col):
    with path.open(encoding="utf-8-sig", newline="") as f:
        return {r[col] for r in csv.DictReader(f)}

pids = read_ids(P, "product_id")
dids = read_ids(D, "distribution_id")
if pids.intersection(r[0] for r in products):
    raise SystemExit("product_id collision")
if dids.intersection(r[0] for r in dists):
    raise SystemExit("distribution_id collision")

with P.open("a", encoding="utf-8", newline="") as f:
    w = csv.writer(f, lineterminator="\n")
    w.writerows(products)
with D.open("a", encoding="utf-8", newline="") as f:
    w = csv.writer(f, lineterminator="\n")
    w.writerows(dists)
print(f"Appended {len(products)} products and {len(dists)} distributions")
