#!/usr/bin/env python3
import csv
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
P=ROOT/'data/data_products.csv'; D=ROOT/'data/product_distributions.csv'; TODAY='2026-08-15'
products=[
["DP000125","DR0070","Amazônia Legal — recorte territorial oficial, edição 2024","Amazônia Legal 2024","Estrutura Territorial — Recortes Legais e Institucionais","dataset","Edição 2024 do recorte geográfico da Amazônia Legal disponibilizado pelo IBGE, identificando municípios, limites e sedes vinculados à área de atuação da SUDAM definida em legislação; a edição incorpora a divisão territorial vigente para a divulgação.","Territorial analysis | Environmental policy | Regional planning | Socioecological systems","Amazônia Legal | SUDAM | recorte legal | municípios | limites | planejamento regional | IBGE","Amazônia Legal brasileira — 773 municípios conforme edição 2024","sim","polígonos de limites | municípios | sedes municipais | tabelas","limites derivados da malha territorial da edição; não corresponde a uma resolução ecológica","edição 2024; mapa PDF corrigido em 23/07/2025 sem alteração dos vetores","por edição territorial","conforme atualização legal e da divisão territorial","ativo","2024 — arquivos vetoriais e tabelas; mapa PDF corrigido em 23/07/2025","complete","https://www.ibge.gov.br/geociencias/cartas-e-mapas/mapas-regionais/15819-amazonia-legal.html?lang=pt-BR","https://www.ibge.gov.br/geociencias/cartas-e-mapas/mapas-regionais/15819-amazonia-legal.html?lang=pt-BR","derivado","Amazônia Legal é um recorte legal e institucional, distinto do Bioma Amazônia e da bacia amazônica. Atualizações podem refletir mudanças territoriais sem mudança da delimitação legal. A correção de 23/07/2025 afetou apenas o mapa PDF, não os vetores.",TODAY],
["DP000126","DR0074","Terras e Aldeias Indígenas nos Biomas Brasileiros — 1:5.000.000 — 2008","Terras e Aldeias Indígenas 2008","Mapas Socioambientais Históricos do Brasil","map_layer_collection","Mapa histórico do IBGE de terras e aldeias indígenas nos biomas brasileiros, acompanhado de relações de aldeias, áreas indígenas delimitadas e áreas sem delimitação, com referência de 2008; inclui também representação de terras indígenas e ocupação da Amazônia Legal.","Indigenous geography | Environmental justice | Conservation | Socioecological systems","terras indígenas | aldeias indígenas | biomas | Amazônia Legal | povos indígenas | 2008 | IBGE","Brasil — biomas brasileiros; informações de referência de 2008","sim","mapa temático | relações tabulares associadas","escala 1:5.000.000","2008","edição cartográfica histórica","sem periodicidade inferida","arquivado","2008 — 1:5.000.000","complete","https://www.ibge.gov.br/geociencias/cartas-e-mapas/redes-geograficas/15970-terras-e-aldeias-indigenas-nos-biomas-brasileiros.html","https://www.ibge.gov.br/geociencias/cartas-e-mapas/redes-geograficas/15970-terras-e-aldeias-indigenas-nos-biomas-brasileiros.html","derivado","Produto histórico: limites, situação jurídica, nomes e localização de terras e aldeias podem ter mudado substancialmente desde 2008. Não usar como cadastro contemporâneo de terras indígenas ou população indígena.",TODAY],
]
dists=[
["DD000141","DP000125","Amazônia Legal 2024 — vetores, tabelas e mapa oficial","https://www.ibge.gov.br/geociencias/cartas-e-mapas/mapas-regionais/15819-amazonia-legal.html?lang=pt-BR","SHP | XLS | ODS | PDF","HTTPS / download","navegador web","sim","não","downloads públicos por tipo de arquivo","licença específica dos arquivos não confirmada nesta auditoria; observar termos do IBGE","desconhecido","por tipo de arquivo","A página oferece municípios, limites e sedes em Shapefile e tabelas XLS/ODS; o mapa PDF foi substituído em 23/07/2025 por correção gráfica que não comprometeu os vetores.",TODAY],
["DD000142","DP000126","Terras e Aldeias Indígenas nos Biomas Brasileiros — mapa 2008","https://www.ibge.gov.br/geociencias/cartas-e-mapas/redes-geograficas/15970-terras-e-aldeias-indigenas-nos-biomas-brasileiros.html","PDF","HTTPS / download","navegador web","sim","não","download público do mapa histórico","licença específica do arquivo não confirmada nesta auditoria; observar termos do IBGE","desconhecido","não","Distribuição cartográfica histórica em PDF, escala 1:5.000.000; não representa situação territorial indígena atual.",TODAY],
]
def ids(path,col):
    with path.open(encoding='utf-8-sig',newline='') as f: return {r[col] for r in csv.DictReader(f)}
pids=ids(P,'product_id'); dids=ids(D,'distribution_id')
if pids & {r[0] for r in products}: raise SystemExit('product collision')
if dids & {r[0] for r in dists}: raise SystemExit('distribution collision')
with P.open('a',encoding='utf-8',newline='') as f: csv.writer(f,lineterminator='\n').writerows(products)
with D.open('a',encoding='utf-8',newline='') as f: csv.writer(f,lineterminator='\n').writerows(dists)
print('Appended 2 products and 2 distributions')
