from pathlib import Path
import csv
ROOT=Path(__file__).resolve().parents[1]
P=ROOT/'data/data_products.csv'; D=ROOT/'data/product_distributions.csv'
products=[
['DP000074','DR0056','Áreas Urbanizadas do Brasil — edição 2019','Áreas Urbanizadas 2019','Áreas Urbanizadas','dataset','Mapeamento nacional das áreas urbanizadas do Brasil obtido por interpretação de imagens de satélite, destinado a representar, mensurar e analisar a distribuição espacial do fenômeno urbano.','Urban geography | Land use and land cover | Remote sensing | Territorial analysis','áreas urbanizadas | expansão urbana | manchas urbanas | sensoriamento remoto | IBGE','Brasil','sim','polígonos vetoriais | mapas','varia conforme edição e sensor; a série histórica inclui 20 m em 2005–2007 e 5 m em 2011–2014','edições históricas até 2019; edição 2022 ainda não confirmada como publicada em 2026-08-14','por edição','irregular','ativo','2019 — edição nacional publicada; 2022 adiada para agosto de 2026','complete','https://www.ibge.gov.br/geociencias/cartas-e-mapas/redes-geograficas/15789-areas-urbanizadas.html','https://www.ibge.gov.br/geociencias/cartas-e-mapas/redes-geograficas/15789-areas-urbanizadas.html','derivado','Mudanças de sensores, resolução e critérios tornam inadequada a comparação direta de áreas entre algumas edições. A edição 2022 foi adiada para agosto de 2026 e não foi tratada como publicada sem evidência material de acesso ao produto.','2026-08-14'],
['DP000075','DR0052','Suscetibilidade a Deslizamentos do Brasil — primeira aproximação','Suscetibilidade a Deslizamentos','Macrocaracterização dos Recursos Naturais do Brasil','dataset','Mapa nacional informativo de suscetibilidade a deslizamentos, construído a partir de bases de geologia, geomorfologia, pedologia, vegetação, uso e cobertura da terra e fontes externas.','Geomorphology | Natural hazards | Environmental mapping | Territorial analysis','deslizamentos | suscetibilidade | relevo | solos | geologia | IBGE','Brasil','sim','célula raster | polígonos vetoriais | mapa nacional','compatível com escala 1:1.000.000','primeira aproximação publicada em 2019','não se aplica','por edição','ativo','primeira aproximação — 2019','complete','https://www.ibge.gov.br/geociencias/informacoes-ambientais/geomorfologia/24252-macrocaracterizacao-dos-recursos-naturais-do-brasil.html?edicao=26063','https://www.ibge.gov.br/geociencias/informacoes-ambientais/geomorfologia/24252-macrocaracterizacao-dos-recursos-naturais-do-brasil.html?edicao=26063','derivado','Produto de macroescala e caráter informativo; o IBGE explicita que não deve ser usado para planejamento ou gestão local, obras de engenharia, nem substituir cartografia de maior detalhe.','2026-08-14'],
['DP000076','DR0052','Potencialidade Agrícola Natural das Terras do Brasil','Potencialidade Agrícola Natural','Macrocaracterização dos Recursos Naturais do Brasil','dataset','Mapeamento nacional que classifica terras em cinco categorias de potencialidade e limitação natural ao uso agrícola, relacionando classes de solos e relevo e apresentando estatísticas territoriais.','Soil science | Agricultural geography | Environmental mapping | Territorial analysis','potencialidade agrícola | solos | relevo | terras | agricultura | IBGE','Brasil','sim','polígonos vetoriais | mapa nacional | estatísticas regionais e por UF','macroescala nacional; consultar metadados e nota metodológica da edição','edição publicada em 2022','não se aplica','por edição','ativo','2022','complete','https://www.ibge.gov.br/geociencias/informacoes-ambientais/geologia/24252-macrocaracterizacao-dos-recursos-naturais-do-brasil.html?lang=pt-BR','https://www.ibge.gov.br/geociencias/informacoes-ambientais/geologia/24252-macrocaracterizacao-dos-recursos-naturais-do-brasil.html?lang=pt-BR','derivado','As cinco classes expressam potencialidade natural em escala de síntese e não incorporam, por si só, viabilidade econômica, infraestrutura, manejo, restrições legais ou aptidão detalhada de propriedades locais.','2026-08-14']]
dists=[
['DD000090','DP000074','IBGE — Áreas Urbanizadas','https://www.ibge.gov.br/geociencias/cartas-e-mapas/redes-geograficas/15789-areas-urbanizadas.html','vetor | mapas | publicação; varia por edição','HTTP download','navegador web | SIG','sim','não','downloads públicos conforme edição publicada','não localizada especificamente nesta rodada; observar termos de uso do IBGE','sim','por edição | recorte territorial conforme arquivo','A edição 2022 foi adiada de julho para agosto de 2026; em 2026-08-14 não foi encontrada evidência material suficiente para tratá-la como já publicada.','2026-08-14'],
['DD000091','DP000075','IBGE — Suscetibilidade a Deslizamentos','https://www.ibge.gov.br/geociencias/informacoes-ambientais/geomorfologia/24252-macrocaracterizacao-dos-recursos-naturais-do-brasil.html?edicao=26063','Shapefile | TIF | PDF | aplicação web','HTTP download','navegador web | SIG | BDiA','sim','não','download público pela página oficial/FTP','não localizada especificamente nesta rodada; observar termos de uso do IBGE','sim','arquivo nacional | visualização em aplicações web','Compatível com escala 1:1.000.000; produto informativo e inadequado para planejamento local ou obras de engenharia.','2026-08-14'],
['DD000092','DP000076','IBGE — Potencialidade Agrícola Natural das Terras','https://www.ibge.gov.br/geociencias/informacoes-ambientais/geologia/24252-macrocaracterizacao-dos-recursos-naturais-do-brasil.html?lang=pt-BR','Shapefile | PDF | publicação | aplicação web','HTTP download','navegador web | SIG | BDiA','sim','não','download público pela página oficial/FTP','não localizada especificamente nesta rodada; observar termos de uso do IBGE','sim','base nacional | estatísticas por Grandes Regiões e UF','Base vetorial oficial acompanha mapa, livro, folder, nota metodológica e aplicações web.','2026-08-14']]
def append(path, rows, idcol=0):
    existing={r[idcol] for r in csv.reader(path.open(encoding='utf-8')) if r}
    todo=[r for r in rows if r[idcol] not in existing]
    if todo:
        with path.open('a',newline='',encoding='utf-8') as f: csv.writer(f,lineterminator='\n').writerows(todo)
append(P,products); append(D,dists)
