from pathlib import Path
import csv

ROOT = Path(__file__).resolve().parents[1]
products_path = ROOT / 'data/data_products.csv'
dists_path = ROOT / 'data/product_distributions.csv'

with products_path.open(encoding='utf-8', newline='') as f:
    products = list(csv.DictReader(f)); pfields = list(products[0].keys())
with dists_path.open(encoding='utf-8', newline='') as f:
    dists = list(csv.DictReader(f)); dfields = list(dists[0].keys())

existing_names = {r['product_name'] for r in products}
existing_pids = {r['product_id'] for r in products}
existing_dids = {r['distribution_id'] for r in dists}

new_products = [
{
'product_id':'DP000077','resource_id':'DR0058','product_name':'Território e Meio Ambiente — Estatísticas por Macrorregiões Hidrográficas 2025','product_acronym':'TMA MacroRH 2025','product_family':'Estatísticas ambientais integradas por Macrorregiões Hidrográficas','product_kind':'dataset','product_description':'Base integrada do IBGE que caracteriza as 12 Macrorregiões Hidrográficas do Brasil por informações de geologia, geomorfologia, pedologia, vegetação, cobertura e uso da terra, biomas e população.','research_areas':'Environmental science | Hydrology | Socioecological systems | Territorial analysis','keywords':'macrorregiões hidrográficas | geologia | geomorfologia | solos | vegetação | uso da terra | população | IBGE','geographic_coverage':'12 Macrorregiões Hidrográficas do Brasil','covers_brazil':'sim','spatial_support':'Macrorregião Hidrográfica | tabelas e estatísticas territoriais','spatial_resolution':'agregação por Macrorregião Hidrográfica; varia conforme variável de origem','temporal_coverage':'edição 2025; referências temporais variam entre variáveis integradas','temporal_resolution':'varia conforme variável de origem','update_frequency':'por edição','product_status':'ativo','version_or_collection':'2025','enumeration_scope':'complete','product_page_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/estatisticas-e-indicadores-ambientais/45353-territorio-e-meio-ambiente-estatisticas-por-macrorregioes-hidrograficas.html','methodology_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/estatisticas-e-indicadores-ambientais/45353-territorio-e-meio-ambiente-estatisticas-por-macrorregioes-hidrograficas.html','primary_or_derived':'derivado','limitations':'Integra variáveis produzidas com referências temporais, escalas e metodologias distintas; não interpretar a base como série temporal homogênea nem atribuir causalidade entre dimensões agregadas.','last_verified':'2026-08-14'
},
{
'product_id':'DP000078','resource_id':'DR0057','product_name':'Domínios e Regiões Naturais Terrestres dos Biomas do Brasil — 2025','product_acronym':'Domínios e Regiões Naturais 2025','product_family':'Regionalização natural dos biomas brasileiros','product_kind':'dataset','product_description':'Regionalização natural experimental do IBGE que delimita 46 Domínios Naturais e 271 Regiões Naturais terrestres dos seis biomas brasileiros com base em atributos físico-bióticos integrados.','research_areas':'Ecology | Biogeography | Physical geography | Environmental statistics','keywords':'biomas | domínios naturais | regiões naturais | regionalização | paisagens | BDiA | IBGE','geographic_coverage':'Brasil terrestre, incluindo ilhas oceânicas conforme produto','covers_brazil':'sim','spatial_support':'polígonos vetoriais | Domínios Naturais | Regiões Naturais','spatial_resolution':'base vetorial compatível com escala 1:250.000; mapas de síntese em 1:5.000.000 e 1:18.000.000','temporal_coverage':'edição publicada em 2025','temporal_resolution':'não se aplica','update_frequency':'experimental; por edição','product_status':'experimental','version_or_collection':'2025 — Informações Geocientíficas Experimentais','enumeration_scope':'complete','product_page_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/vegetacao/15842-biomas.html','methodology_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/vegetacao/15842-biomas.html','primary_or_derived':'derivado','limitations':'Produto explicitamente experimental; as unidades naturais não substituem limites político-administrativos nem devem ser tratadas como classificação causal ou definitiva de ecossistemas.','last_verified':'2026-08-14'
},
{
'product_id':'DP000079','resource_id':'DR0056','product_name':'Monitoramento da Cobertura e Uso da Terra do Brasil — série 2000–2020','product_acronym':'Monitoramento CUT 2000–2020','product_family':'Monitoramento da Cobertura e Uso da Terra','product_kind':'dataset_series','product_description':'Série do IBGE que mapeia e quantifica cobertura e uso da terra no território nacional a partir de interpretação de imagens de satélite e disseminação em Grade Estatística.','research_areas':'Land use and land cover | Environmental monitoring | Remote sensing | Environmental accounting','keywords':'cobertura da terra | uso da terra | mudanças territoriais | grade estatística | Landsat | IBGE','geographic_coverage':'Brasil e Unidades da Federação','covers_brazil':'sim','spatial_support':'Grade Estatística | vetores nacionais e por UF | tabelas','spatial_resolution':'unidade de análise de 1 km² na Grade Estatística; interpretar insumos e representação conforme metodologia','temporal_coverage':'2000, 2010, 2012, 2014, 2016, 2018 e 2020 na série revisada publicada','temporal_resolution':'bienal nas edições recentes; intervalos maiores no início da série','update_frequency':'bienal','product_status':'ativo','version_or_collection':'série revisada em 2022; arquivos por UF corrigidos em 2024 sem alteração dos dados','enumeration_scope':'complete','product_page_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/cobertura-e-uso-da-terra/15831-cobertura-e-uso-da-terra-do-brasil.html','methodology_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/cobertura-e-uso-da-terra/15831-cobertura-e-uso-da-terra-do-brasil.html','primary_or_derived':'derivado','limitations':'A série passou por revisões metodológicas retroativas, incluindo mudança de MODIS para Landsat 8, revisão de classes e compatibilização com outras bases do IBGE; análises temporais devem usar a série revisada e documentar a edição.','last_verified':'2026-08-14'
}
]

new_dists = [
{'distribution_id':'DD000093','product_id':'DP000077','distribution_name':'IBGE — TMA MacroRH 2025 — base e tabelas','access_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/estatisticas-e-indicadores-ambientais/45353-territorio-e-meio-ambiente-estatisticas-por-macrorregioes-hidrograficas.html','format':'XLS | ODS | PDF','access_protocol':'HTTP download','access_tool':'navegador web | planilha','free_download':'sim','authentication_required':'não','access_conditions':'downloads públicos pela página oficial','license':'não localizada especificamente nesta rodada; observar termos de uso do IBGE e das fontes integradas','provider_attribution_required':'sim','subset_support':'base completa | tabelas por tema/recorte','notes':'Integra estatísticas ambientais e populacionais das 12 Macrorregiões Hidrográficas; preservar fonte e referência temporal de cada variável.','last_verified':'2026-08-14'},
{'distribution_id':'DD000094','product_id':'DP000078','distribution_name':'IBGE — Domínios e Regiões Naturais 2025 — vetores, mapas e tabelas','access_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/vegetacao/15842-biomas.html','format':'vetor | XLSX | PDF','access_protocol':'HTTP download','access_tool':'navegador web | SIG | planilha','free_download':'sim','authentication_required':'não','access_conditions':'downloads públicos pela página oficial','license':'não localizada especificamente nesta rodada; observar termos de uso do IBGE','provider_attribution_required':'sim','subset_support':'Domínios | Regiões | simbologia | dicionário de dados','notes':'Disponibiliza vetor, tabelas de Domínios e Regiões, simbologia, dicionário de dados e mapas; produto classificado como Informação Geocientífica Experimental.','last_verified':'2026-08-14'},
{'distribution_id':'DD000095','product_id':'DP000079','distribution_name':'IBGE — Monitoramento CUT — vetores e tabelas','access_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/cobertura-e-uso-da-terra/15831-cobertura-e-uso-da-terra-do-brasil.html','format':'vetor | ODS | XLS | PDF','access_protocol':'HTTP download','access_tool':'navegador web | SIG | planilha','free_download':'sim','authentication_required':'não','access_conditions':'downloads públicos por edição; arquivos nacionais e por UF conforme página','license':'não localizada especificamente nesta rodada; observar termos de uso do IBGE','provider_attribution_required':'sim','subset_support':'Brasil | Unidades da Federação | edição/ano','notes':'A série revisada retroage mudanças metodológicas; arquivos por UF da edição 2020 foram substituídos em 18/07/2024 por correção de configuração interna sem alteração de dados ou geometrias.','last_verified':'2026-08-14'}
]

for row in new_products:
    assert row['product_id'] not in existing_pids, row['product_id']
    assert row['product_name'] not in existing_names, row['product_name']
    assert set(row) == set(pfields), row['product_id']
for row in new_dists:
    assert row['distribution_id'] not in existing_dids, row['distribution_id']
    assert set(row) == set(dfields), row['distribution_id']

with products_path.open('a', encoding='utf-8', newline='') as f:
    w = csv.DictWriter(f, fieldnames=pfields, lineterminator='\n'); w.writerows(new_products)
with dists_path.open('a', encoding='utf-8', newline='') as f:
    w = csv.DictWriter(f, fieldnames=dfields, lineterminator='\n'); w.writerows(new_dists)
print('Added 3 products and 3 distributions; known CUT 1:250.000 duplicate intentionally skipped')
