#!/usr/bin/env python3
import csv
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
TODAY='2026-08-14'

RES=ROOT/'data/data_resources.csv'
PROD=ROOT/'data/data_products.csv'
DIST=ROOT/'data/product_distributions.csv'

def header(path):
    with path.open(encoding='utf-8-sig', newline='') as f:
        return next(csv.reader(f))

def ids(path, col):
    with path.open(encoding='utf-8-sig', newline='') as f:
        return {r[col] for r in csv.DictReader(f)}

def append_dicts(path, rows):
    fields=header(path)
    with path.open('a', encoding='utf-8', newline='') as f:
        w=csv.DictWriter(f, fieldnames=fields, lineterminator='\n')
        for row in rows:
            assert set(row)==set(fields), (path, set(fields)-set(row), set(row)-set(fields))
            w.writerow(row)

assert len(ids(RES,'resource_id'))==59
assert len(ids(PROD,'product_id'))==48
assert len(ids(DIST,'distribution_id'))==59
assert 'DR0060' not in ids(RES,'resource_id')
assert 'DP000049' not in ids(PROD,'product_id')
assert 'DD000060' not in ids(DIST,'distribution_id')

new_sources=[{
'resource_id':'DR0060','resource_name':'Biodiversidade — IBGE','acronym':'Biodiversidade IBGE','official_identity':'Tema de informações geocientíficas sobre biodiversidade do IBGE','description':'Conjunto institucional de produtos geocientíficos do IBGE sobre biodiversidade, incluindo avaliação da cobertura e permanência dos dados de ocorrência de espécies disponíveis no Brasil.','homepage_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/biodiversidade.html','data_access_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/biodiversidade/38371-avaliacao-dos-dados-sobre-a-biodiversidade-brasileira.html','research_areas':'Biodiversidade e Conservação | Sensoriamento Remoto e Geoinformação | Infraestruturas e Ciência de Dados','keywords':'biodiversidade | ocorrência de espécies | cobertura de dados | SiBBr | grade estatística | municípios','data_product_types':'indicadores | vetores | publicação | mapas','data_formats':'formatos vetoriais e PDF; variam conforme edição','visualization_types':'mapas | publicação | downloads','geographic_coverage':'Brasil','covers_brazil':'sim','spatial_resolution':'grade estatística de 50 km e municípios no produto 2025','temporal_coverage':'edições 2022 e 2025 verificadas','temporal_resolution':'por edição','data_sources':'SiBBr | bases cartográficas e estatísticas do IBGE','free_download':'sim','access_conditions':'downloads públicos na página do produto','programmatic_access':'não','access_protocols':'HTTP download','authentication_required':'não','access_documentation_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/biodiversidade/38371-avaliacao-dos-dados-sobre-a-biodiversidade-brasileira.html','license':'observar termos de uso dos dados do IBGE e metadados do arquivo','institutional_status':'público','owner_or_manager':'IBGE','academic_uses':'Avaliar lacunas, cobertura espacial e permanência de acesso a dados de ocorrência de espécies para pesquisa e governança da informação ambiental.','limitations':'Indicadores medem características da disponibilidade dos dados de ocorrência e não representam diretamente riqueza, abundância ou estado de conservação das espécies.','academic_evidence_type':'documentação técnica oficial','academic_evidence_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/biodiversidade/38371-avaliacao-dos-dados-sobre-a-biodiversidade-brasileira.html','academic_evidence_note':'A edição 2025 analisa dados nacionais de nove grupos taxonômicos disponíveis no SiBBr e disponibiliza indicadores em grade estatística de 50 km e municípios.','verification_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/biodiversidade/38371-avaliacao-dos-dados-sobre-a-biodiversidade-brasileira.html','last_verified':TODAY}]

products=[
{'product_id':'DP000049','resource_id':'DR0060','product_name':'Avaliação dos Dados sobre a Biodiversidade Brasileira — edição 2025','product_acronym':'Biodiversidade IBGE 2025','product_family':'Avaliação da cobertura dos dados de ocorrência de espécies','product_kind':'dataset','product_description':'Indicadores experimentais do IBGE sobre cobertura e permanência de acesso aos dados nacionais de ocorrência de espécies disponíveis no SiBBr, calculados para nove grupos taxonômicos.','research_areas':'Biodiversity informatics | Conservation | Geospatial analysis | Data quality','keywords':'ocorrência de espécies | lacunas | cobertura | SiBBr | municípios | grade 50 km','geographic_coverage':'Brasil','covers_brazil':'sim','spatial_support':'grade estatística de 50 km | municípios','spatial_resolution':'50 km na grade; município no recorte administrativo','temporal_coverage':'base disponível em 2025; comparação com edição baseada em 2022','temporal_resolution':'por edição','update_frequency':'por edição','product_status':'experimental','version_or_collection':'2025','enumeration_scope':'complete','product_page_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/biodiversidade/38371-avaliacao-dos-dados-sobre-a-biodiversidade-brasileira.html','methodology_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/biodiversidade/38371-avaliacao-dos-dados-sobre-a-biodiversidade-brasileira.html','primary_or_derived':'derivado','limitations':'Os indicadores descrevem disponibilidade/cobertura dos registros e não devem ser usados como estimativas diretas de riqueza, abundância ou distribuição real sem considerar viés amostral e detectabilidade.','last_verified':TODAY},
{'product_id':'DP000050','resource_id':'DR0010','product_name':'MapBiomas Cobertura e Uso da Terra — Coleção 10.1','product_acronym':'MapBiomas LULC 10.1','product_family':'Mapas anuais de cobertura e uso da terra','product_kind':'dataset_series','product_description':'Série anual de mapas de cobertura e uso da terra do Brasil da Coleção 10.1, com correções históricas e cobertura de 1985 a 2024.','research_areas':'Land use and land cover | Remote sensing | Landscape ecology | Environmental monitoring','keywords':'uso da terra | cobertura da terra | Landsat | 30 m | série anual | MapBiomas','geographic_coverage':'Brasil','covers_brazil':'sim','spatial_support':'célula raster','spatial_resolution':'30 m','temporal_coverage':'1985–2024','temporal_resolution':'anual','update_frequency':'coleção anual com revisões','product_status':'ativo','version_or_collection':'Coleção 10.1','enumeration_scope':'complete','product_page_url':'https://brasil.mapbiomas.org/colecoes-mapbiomas/','methodology_url':'https://brasil.mapbiomas.org/metodo_cobertura_e_uso/','primary_or_derived':'derivado','limitations':'Coleções incorporam revisões metodológicas e correções históricas; registrar coleção, versão e legenda. A Coleção 10.1 corrigiu dados históricos específicos e pixels sem informação em determinadas áreas.','last_verified':TODAY},
{'product_id':'DP000051','resource_id':'DR0010','product_name':'MapBiomas Fogo — Coleção 5','product_acronym':'MapBiomas Fogo 5','product_family':'Mapeamento de cicatrizes e dinâmica do fogo','product_kind':'dataset_series','product_description':'Mapeamento anual e mensal de cicatrizes de fogo no Brasil, incluindo área queimada, tamanho e severidade potencial das cicatrizes, frequência, última ocorrência e intervalos de retorno.','research_areas':'Fire ecology | Remote sensing | Environmental monitoring | Land use','keywords':'fogo | área queimada | cicatriz | frequência | Landsat | 30 m','geographic_coverage':'Brasil','covers_brazil':'sim','spatial_support':'célula raster | cicatrizes vetoriais conforme produto','spatial_resolution':'30 m para mapeamento Landsat','temporal_coverage':'1985–2025','temporal_resolution':'mensal | anual | métricas por período','update_frequency':'anual; monitoramento complementar mensal','product_status':'ativo','version_or_collection':'Coleção 5','enumeration_scope':'family_level','product_page_url':'https://brasil.mapbiomas.org/mapbiomas-fogo/','methodology_url':'https://brasil.mapbiomas.org/mapbiomas-fogo/','primary_or_derived':'derivado','limitations':'Cicatriz de fogo e foco de calor são estimandos distintos. Métricas acumuladas, frequência e severidade potencial não devem ser tratadas como equivalentes à área queimada anual.','last_verified':TODAY},
{'product_id':'DP000052','resource_id':'DR0010','product_name':'MapBiomas Solo — Coleção 3 beta: estoque de carbono orgânico do solo','product_acronym':'MapBiomas Solo 3 COS','product_family':'Mapeamento de propriedades e carbono do solo','product_kind':'dataset_series','product_description':'Série anual de mapas de estoque de carbono orgânico do solo na camada de 0–30 cm do Brasil, em toneladas por hectare, produzida pela Coleção 3 beta do MapBiomas Solo.','research_areas':'Soil science | Carbon cycle | Remote sensing | Environmental modelling','keywords':'carbono orgânico do solo | COS | 0-30 cm | 30 m | MapBiomas Solo','geographic_coverage':'Brasil','covers_brazil':'sim','spatial_support':'célula raster','spatial_resolution':'30 m','temporal_coverage':'1985–2024','temporal_resolution':'anual','update_frequency':'por coleção','product_status':'beta','version_or_collection':'Coleção 3 beta','enumeration_scope':'complete','product_page_url':'https://brasil.mapbiomas.org/dados-mapbiomas-solo/','methodology_url':'https://brasil.mapbiomas.org/metodo-mapbiomas-solo/','primary_or_derived':'modelado','limitations':'O produto é preditivo e depende do modelo e covariáveis. A documentação alerta para artefato entre 2021 e 2022 que produz queda artificial na série de carbono; tendências no final da série exigem cautela.','last_verified':TODAY},
{'product_id':'DP000053','resource_id':'DR0013','product_name':'speciesLink — registros de biodiversidade','product_acronym':'speciesLink Ocorrências','product_family':'Registros de coleções biológicas e ocorrências','product_kind':'dataset_series','product_description':'Registros de biodiversidade integrados pela rede speciesLink, pesquisáveis por taxonomia, localidade e outros filtros e provenientes de coleções científicas participantes.','research_areas':'Biodiversity informatics | Taxonomy | Biogeography | Natural history collections','keywords':'ocorrências | coleções | espécimes | taxonomia | georreferenciamento | speciesLink','geographic_coverage':'Brasil e América do Sul conforme coleção','covers_brazil':'sim','spatial_support':'registro de ocorrência ou espécime; coordenadas quando disponíveis','spatial_resolution':'pontual quando georreferenciado; precisão varia por registro','temporal_coverage':'histórica ao presente conforme coleção','temporal_resolution':'por registro','update_frequency':'contínua conforme provedores','product_status':'ativo','version_or_collection':'rede corrente','enumeration_scope':'external_index','product_page_url':'https://specieslink.net/search/','methodology_url':'https://specieslink.net/ws/1.0/','primary_or_derived':'agregador','limitations':'Qualidade taxonômica, georreferenciamento, completude, licença e condições de uso variam por coleção; preservar instituição, coleção e registro de origem.','last_verified':TODAY},
{'product_id':'DP000054','resource_id':'DR0013','product_name':'speciesLink — catálogo de instituições e coleções participantes','product_acronym':'speciesLink Coleções','product_family':'Metadados de coleções biológicas','product_kind':'federated_catalog','product_description':'Catálogo da rede com instituições, coleções, status de conexão, localização, volume de registros, georreferenciamento, imagens e atualização.','research_areas':'Biodiversity informatics | Collection management | Data infrastructure','keywords':'coleções biológicas | instituições | metadados | atualização | acervo','geographic_coverage':'instituições e coleções participantes; forte cobertura brasileira','covers_brazil':'sim','spatial_support':'instituição | coleção | subcoleção','spatial_resolution':'não se aplica','temporal_coverage':'estado corrente e datas de adesão/atualização','temporal_resolution':'por atualização','update_frequency':'contínua','product_status':'ativo','version_or_collection':'network manager corrente','enumeration_scope':'external_index','product_page_url':'https://specieslink.net/network-manager','methodology_url':'https://specieslink.net/ws/1.0/','primary_or_derived':'agregador','limitations':'Métricas de registros online, georreferenciados e imagens representam estado do compartilhamento na rede e não o tamanho total ou a qualidade científica completa de cada coleção.','last_verified':TODAY},
{'product_id':'DP000055','resource_id':'DR0014','product_name':'SiBBr — registros de ocorrência, coleções e datasets de biodiversidade','product_acronym':'SiBBr Biodiversidade','product_family':'Infraestrutura nacional de dados de biodiversidade','product_kind':'federated_catalog','product_description':'Infraestrutura nacional que integra registros de espécies, coleções biológicas, datasets, monitoramento e informações sobre distribuição geográfica da biodiversidade brasileira.','research_areas':'Biodiversity informatics | Conservation | Biogeography | Data infrastructure','keywords':'SiBBr | espécies | ocorrência | coleções | datasets | biodiversidade','geographic_coverage':'Brasil, com integração de registros nacionais e internacionais pertinentes','covers_brazil':'sim','spatial_support':'ocorrências | datasets | coleções | espécies','spatial_resolution':'varia por dataset e registro','temporal_coverage':'histórica ao presente conforme fonte','temporal_resolution':'por registro ou dataset','update_frequency':'contínua conforme publicadores','product_status':'ativo','version_or_collection':'portal corrente','enumeration_scope':'external_index','product_page_url':'https://www.sibbr.gov.br/','methodology_url':'https://www.sibbr.gov.br/','primary_or_derived':'agregador','limitations':'Parte dos dados também é publicada no GBIF; evitar dupla contagem e preservar publicador, dataset, licença, precisão espacial e data de extração.','last_verified':TODAY},
{'product_id':'DP000056','resource_id':'DR0014','product_name':'SiBBr / GBIF Metabarcoding Data Toolkit — Brasil','product_acronym':'SiBBr MDT','product_family':'Dados de metabarcoding ambiental','product_kind':'federated_catalog','product_description':'Ferramenta associada ao SiBBr para organização e publicação de conjuntos de dados genéticos de metabarcoding obtidos de amostras ambientais como solo, água e sedimentos.','research_areas':'Molecular ecology | Biodiversity monitoring | Environmental DNA | Data publishing','keywords':'metabarcoding | eDNA | DNA ambiental | solo | água | sedimento | GBIF','geographic_coverage':'Brasil conforme datasets publicados','covers_brazil':'sim','spatial_support':'amostra ambiental | dataset','spatial_resolution':'varia por amostra e dataset','temporal_coverage':'varia por dataset','temporal_resolution':'por evento de amostragem','update_frequency':'contínua conforme publicação','product_status':'piloto/ativo','version_or_collection':'GBIF Metabarcoding Data Programme — toolkit corrente','enumeration_scope':'external_index','product_page_url':'https://mdt.sibbr.gov.br/','methodology_url':'https://mdt.sibbr.gov.br/','primary_or_derived':'agregador','limitations':'Resultados moleculares dependem de protocolo de amostragem, marcador, pipeline bioinformático e base taxonômica; presença de sequência não equivale automaticamente a abundância ou presença de organismo vivo no local.','last_verified':TODAY},
{'product_id':'DP000057','resource_id':'DR0017','product_name':'HidroWeb — séries históricas de estações convencionais','product_acronym':'HidroWeb Históricas','product_family':'Rede Hidrometeorológica Nacional — séries convencionais','product_kind':'dataset_series','product_description':'Séries históricas das estações hidrométricas convencionais da base HIDRO, incluindo chuva, cota, vazão, sedimentos, qualidade da água, descarga e outros tipos documentados.','research_areas':'Hydrology | Water resources | Climatology | Environmental monitoring','keywords':'HidroWeb | chuva | cota | vazão | sedimentos | qualidade da água | estações','geographic_coverage':'Brasil','covers_brazil':'sim','spatial_support':'estação hidrométrica | bacia','spatial_resolution':'ponto de estação','temporal_coverage':'histórica; varia por estação e variável','temporal_resolution':'varia por série; convencional e agregações derivadas','update_frequency':'contínua conforme operação e consolidação','product_status':'ativo','version_or_collection':'HidroWeb v3 / base HIDRO corrente','enumeration_scope':'family_level','product_page_url':'https://www.snirh.gov.br/hidroweb/serieshistoricas','methodology_url':'https://www.gov.br/ana/pt-br/assuntos/monitoramento-e-eventos-criticos/monitoramento-hidrologico/orientacoes-manuais/manuais-de-sistemas-e-servicos-de-disponibilizacao-de-dados-hidrologicos','primary_or_derived':'primário','limitations':'Falhas, mudanças de estação, consistência e períodos efetivos variam; códigos de municípios da base HIDRO não são necessariamente os códigos IBGE. API impõe limites de período por endpoint.','last_verified':TODAY},
{'product_id':'DP000058','resource_id':'DR0017','product_name':'HidroWebservice — séries telemétricas e HidroSat','product_acronym':'HidroWebservice','product_family':'API de dados hidrológicos telemétricos e satelitais','product_kind':'data_service','product_description':'API oficial da ANA para consulta automatizada de inventário e séries telemétricas, dados adotados e brutos, estações virtuais HidroSat e séries convencionais selecionadas.','research_areas':'Hydrology | Environmental data infrastructure | Real-time monitoring','keywords':'API | telemetria | HidroSat | chuva | nível | vazão | ANA','geographic_coverage':'Brasil conforme rede e estações virtuais cadastradas','covers_brazil':'sim','spatial_support':'estação telemétrica | estação virtual | série temporal','spatial_resolution':'ponto/estação; depende do produto HidroSat','temporal_coverage':'varia por estação e serviço','temporal_resolution':'subdiária e outras frequências conforme endpoint','update_frequency':'operacional','product_status':'ativo','version_or_collection':'Hidro Webservice v1.0.3984.2 verificado em 2026','enumeration_scope':'complete','product_page_url':'https://www.ana.gov.br/hidrowebservice/swagger-ui/index.html','methodology_url':'https://www.gov.br/ana/pt-br/assuntos/monitoramento-e-eventos-criticos/monitoramento-hidrologico/orientacoes-manuais/manuais/manual-hidrowebservice_publica.pdf/view','primary_or_derived':'serviço','limitations':'Acesso automatizado requer credenciais solicitadas à ANA. Endpoints limitam a janela temporal por requisição; dados telemétricos podem incluir valores brutos e adotados, que devem ser distinguidos.','last_verified':TODAY},
{'product_id':'DP000059','resource_id':'DR0018','product_name':'BDMEP — séries históricas meteorológicas do INMET','product_acronym':'BDMEP Séries','product_family':'Banco de Dados Meteorológicos do INMET','product_kind':'dataset_series','product_description':'Séries meteorológicas históricas de estações automáticas e convencionais do INMET, com seleção de dados horários, diários ou mensais e variáveis por estação.','research_areas':'Meteorology | Climatology | Environmental monitoring | Agroclimatology','keywords':'INMET | estação meteorológica | temperatura | precipitação | umidade | vento | séries históricas','geographic_coverage':'Brasil conforme rede de estações','covers_brazil':'sim','spatial_support':'estação meteorológica','spatial_resolution':'ponto de estação','temporal_coverage':'varia por estação e data de início de operação','temporal_resolution':'horária | diária | mensal','update_frequency':'contínua conforme rede e processamento','product_status':'ativo','version_or_collection':'BDMEP corrente','enumeration_scope':'family_level','product_page_url':'https://bdmep.inmet.gov.br/','methodology_url':'https://bdmep.inmet.gov.br/','primary_or_derived':'primário','limitations':'Cobertura temporal e completude variam por estação; solicitações pelo BDMEP passam por fila e confirmação por e-mail, e o link de dados gerado expira após 48 horas.','last_verified':TODAY}
]

distributions=[
{'distribution_id':'DD000060','product_id':'DP000049','distribution_name':'IBGE — página e downloads da edição 2025','access_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/biodiversidade/38371-avaliacao-dos-dados-sobre-a-biodiversidade-brasileira.html','format':'vetores | PDF | documentação; conforme arquivo','access_protocol':'HTTP download','access_tool':'navegador web | SIG','free_download':'sim','authentication_required':'não','access_conditions':'download público pela página oficial','license':'observar termos de uso dos dados do IBGE e metadados do arquivo','provider_attribution_required':'sim','subset_support':'por produto/arquivo','notes':'A edição 2025 disponibiliza indicadores em grade estatística de 50 km e municípios.','last_verified':TODAY},
{'distribution_id':'DD000061','product_id':'DP000050','distribution_name':'MapBiomas — plataforma de cobertura e uso','access_url':'https://plataforma.brasil.mapbiomas.org/','format':'visualização | estatísticas | exportação','access_protocol':'HTTPS web','access_tool':'navegador web','free_download':'sim','authentication_required':'parcial','access_conditions':'consulta pública; algumas operações podem depender de serviços Google','license':'CC BY; atribuição requerida conforme termos do MapBiomas','provider_attribution_required':'sim','subset_support':'territorial | classe | ano','notes':'Registrar explicitamente Coleção 10.1, legenda e ano ao extrair dados.','last_verified':TODAY},
{'distribution_id':'DD000062','product_id':'DP000050','distribution_name':'MapBiomas LULC 10.1 — catálogo de assets e downloads','access_url':'https://brasil.mapbiomas.org/colecoes-mapbiomas/','format':'GeoTIFF | Google Earth Engine assets | estatísticas','access_protocol':'HTTP download | Google Earth Engine','access_tool':'navegador web | GEE','free_download':'sim','authentication_required':'parcial','access_conditions':'download direto público; GEE requer conta/projeto habilitado','license':'CC BY; atribuição requerida conforme termos do MapBiomas','provider_attribution_required':'sim','subset_support':'ano | recorte via GEE','notes':'A página oficial documenta o asset da Coleção 10.1 e links de download direto.','last_verified':TODAY},
{'distribution_id':'DD000063','product_id':'DP000051','distribution_name':'MapBiomas Fogo — Coleção 5','access_url':'https://brasil.mapbiomas.org/mapbiomas-fogo/','format':'mapas | estatísticas | downloads | documentação','access_protocol':'HTTPS web | downloads','access_tool':'navegador web | SIG','free_download':'sim','authentication_required':'não','access_conditions':'acesso público aos produtos e documentação','license':'CC BY; atribuição requerida conforme termos do MapBiomas','provider_attribution_required':'sim','subset_support':'ano | mês | métrica | território','notes':'Coleção 5 cobre 1985–2025 e distingue dados anuais, mensais e métricas por período.','last_verified':TODAY},
{'distribution_id':'DD000064','product_id':'DP000052','distribution_name':'MapBiomas Solo 3 — página de dados','access_url':'https://brasil.mapbiomas.org/dados-mapbiomas-solo/','format':'GeoTIFF | GEE assets | TXT | CSV | documentação','access_protocol':'HTTP download | Google Earth Engine','access_tool':'navegador web | GEE | SIG','free_download':'sim','authentication_required':'parcial','access_conditions':'downloads públicos; GEE requer conta/projeto habilitado','license':'CC BY para os repositórios documentados','provider_attribution_required':'sim','subset_support':'ano | propriedade | profundidade conforme produto','notes':'COS anual 0–30 cm a 30 m; a mesma coleção também contém granulometria, textura e pedregosidade, que não são este produto de COS.','last_verified':TODAY},
{'distribution_id':'DD000065','product_id':'DP000053','distribution_name':'speciesLink — busca de registros','access_url':'https://specieslink.net/search/','format':'visualização | exportação tabular; varia por ferramenta','access_protocol':'HTTPS web','access_tool':'navegador web','free_download':'sim','authentication_required':'parcial','access_conditions':'condições adicionais podem existir por coleção','license':'varia por coleção; observar política da rede e provedor','provider_attribution_required':'sim','subset_support':'taxonomia | coleção | geografia | campos','notes':'A rede agrega dados de coleções independentes; preservar condições e citação da coleção provedora.','last_verified':TODAY},
{'distribution_id':'DD000066','product_id':'DP000053','distribution_name':'speciesLink API v1.0 — registros','access_url':'https://specieslink.net/ws/1.0/','format':'JSON','access_protocol':'REST API | HTTP GET','access_tool':'API client | R/Python','free_download':'sim','authentication_required':'parcial','access_conditions':'API documentada; apikey pode ser requerida para operações','license':'varia por coleção; observar política da rede e provedor','provider_attribution_required':'sim','subset_support':'filtros | paginação | agrupamentos','notes':'A API documenta filtros, paginação, campos retornados e agrupamentos para registros.','last_verified':TODAY},
{'distribution_id':'DD000067','product_id':'DP000054','distribution_name':'speciesLink — Network Manager','access_url':'https://specieslink.net/network-manager','format':'catálogo web | tabela','access_protocol':'HTTPS web','access_tool':'navegador web','free_download':'sim','authentication_required':'não','access_conditions':'consulta pública','license':'metadados públicos da rede; condições dos dados permanecem por coleção','provider_attribution_required':'sim','subset_support':'filtros por instituição, coleção, status, país e métricas','notes':'Exibe estado, localização, volume de registros e atualização de coleções/subcoleções conectadas.','last_verified':TODAY},
{'distribution_id':'DD000068','product_id':'DP000055','distribution_name':'SiBBr — portal nacional de biodiversidade','access_url':'https://www.sibbr.gov.br/','format':'portal | ocorrências | datasets | coleções | mapas','access_protocol':'HTTPS web','access_tool':'navegador web','free_download':'sim','authentication_required':'parcial','access_conditions':'dados abertos; condições e licenças variam por dataset','license':'varia por dataset/publicador','provider_attribution_required':'sim','subset_support':'taxonomia | dataset | geografia conforme módulo','notes':'SiBBr é nó nacional do GBIF; evitar dupla contagem de datasets replicados entre infraestruturas.','last_verified':TODAY},
{'distribution_id':'DD000069','product_id':'DP000056','distribution_name':'SiBBr Metabarcoding Data Toolkit','access_url':'https://mdt.sibbr.gov.br/','format':'datasets | metadados | API conforme toolkit','access_protocol':'HTTPS web','access_tool':'navegador web','free_download':'sim','authentication_required':'parcial','access_conditions':'consulta pública; publicação/gestão de datasets pode exigir login','license':'varia por dataset','provider_attribution_required':'sim','subset_support':'por dataset','notes':'Toolkit em desenvolvimento no programa piloto de dados de metabarcoding do GBIF.','last_verified':TODAY},
{'distribution_id':'DD000070','product_id':'DP000057','distribution_name':'HidroWeb — Séries Históricas','access_url':'https://www.snirh.gov.br/hidroweb/serieshistoricas','format':'downloads e tabelas; formatos variam por módulo','access_protocol':'HTTPS web | download','access_tool':'navegador web','free_download':'sim','authentication_required':'não','access_conditions':'consulta e download públicos','license':'informações públicas da ANA; observar termos do portal e metadados','provider_attribution_required':'sim','subset_support':'estação | bacia | UF | município | período','notes':'A interface permite busca por tipo e código de estação, bacia, sub-bacia, rio, UF, município, responsável e operador.','last_verified':TODAY},
{'distribution_id':'DD000071','product_id':'DP000058','distribution_name':'ANA Hidro Webservice — Swagger/API','access_url':'https://www.ana.gov.br/hidrowebservice/swagger-ui/index.html','format':'JSON | respostas REST','access_protocol':'REST API','access_tool':'API client | Swagger | R/Python','free_download':'sim','authentication_required':'sim','access_conditions':'credenciais devem ser solicitadas à ANA; limites de período variam por endpoint','license':'conteúdo institucional ANA; manual do portal sob CC BY-ND 3.0','provider_attribution_required':'sim','subset_support':'estação | período | variável | inventário','notes':'Documentação verificada inclui endpoints para chuva, cota, vazão, sedimentos, qualidade da água, telemetria e HidroSat.','last_verified':TODAY},
{'distribution_id':'DD000072','product_id':'DP000059','distribution_name':'INMET BDMEP — solicitação de séries','access_url':'https://bdmep.inmet.gov.br/','format':'CSV','access_protocol':'HTTPS web | entrega por link','access_tool':'navegador web | e-mail','free_download':'sim','authentication_required':'parcial','access_conditions':'solicitação requer e-mail, confirmação e fila de processamento; link expira em 48 h','license':'dados públicos do INMET; licença específica deve ser confirmada para reutilização','provider_attribution_required':'sim','subset_support':'tipo de estação | período | variável | região | estação','notes':'O sistema oferece seleção de dados horários, diários e mensais, automáticos ou convencionais.','last_verified':TODAY}
]

append_dicts(RES,new_sources)
append_dicts(PROD,products)
append_dicts(DIST,distributions)

assert len(ids(RES,'resource_id'))==60
assert len(ids(PROD,'product_id'))==59
assert len(ids(DIST,'distribution_id'))==72
assert ids(PROD,'product_id').issuperset({r['product_id'] for r in products})
assert ids(DIST,'distribution_id').issuperset({r['distribution_id'] for r in distributions})
print('materialized', len(new_sources), len(products), len(distributions))
