#!/usr/bin/env python3
import csv
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; TODAY='2026-08-14'
P=ROOT/'data/data_products.csv'; D=ROOT/'data/product_distributions.csv'
def head(p):
    with p.open(encoding='utf-8-sig',newline='') as f:return next(csv.reader(f))
def count(p):
    with p.open(encoding='utf-8-sig',newline='') as f:return sum(1 for _ in csv.DictReader(f))
def append(p,rows):
    fields=head(p)
    with p.open('a',encoding='utf-8',newline='') as f:
        w=csv.DictWriter(f,fieldnames=fields,lineterminator='\n')
        for r in rows: assert set(r)==set(fields); w.writerow(r)
assert count(P)==59 and count(D)==72
products=[
{'product_id':'DP000060','resource_id':'DR0010','product_name':'MapBiomas Água — Coleção 5','product_acronym':'MapBiomas Água 5','product_family':'Dinâmica da superfície de água','product_kind':'dataset_series','product_description':'Mapas anuais e mensais da superfície de água no Brasil para análise de dinâmica, permanência e mudanças de corpos hídricos ao longo de 1985–2025.','research_areas':'Hydrology | Remote sensing | Climate impacts | Environmental monitoring','keywords':'superfície de água | rios | lagos | reservatórios | dinâmica hídrica | MapBiomas Água','geographic_coverage':'Brasil','covers_brazil':'sim','spatial_support':'célula raster | estatísticas territoriais','spatial_resolution':'herdada do produto de mapeamento; consultar metadados da Coleção 5','temporal_coverage':'1985–2025','temporal_resolution':'mensal | anual','update_frequency':'por coleção; atualização periódica','product_status':'ativo','version_or_collection':'Coleção 5','enumeration_scope':'family_level','product_page_url':'https://brasil.mapbiomas.org/lancamentos/','methodology_url':'https://brasil.mapbiomas.org/','primary_or_derived':'derivado','limitations':'Superfície de água mapeada por sensoriamento remoto não equivale diretamente a vazão, volume armazenado ou qualidade da água; distinguir ocorrência, permanência e mudanças conforme a métrica utilizada.','last_verified':TODAY},
{'product_id':'DP000061','resource_id':'DR0010','product_name':'MapBiomas Módulo Urbano — Coleção 10','product_acronym':'MapBiomas Urbano 10','product_family':'Áreas urbanizadas e contexto físico-ambiental urbano','product_kind':'dataset_series','product_description':'Mapeamento detalhado das áreas urbanizadas do Brasil entre 1985 e 2024, com dados de urbanização, vegetação urbana, expansão por períodos e relações com declividade e proximidade de drenagens.','research_areas':'Urban ecology | Land use | Climate adaptation | Remote sensing | Territorial planning','keywords':'áreas urbanizadas | vegetação urbana | expansão urbana | declividade | drenagem | risco','geographic_coverage':'Brasil','covers_brazil':'sim','spatial_support':'célula raster | município | regiões metropolitanas e recortes urbanos conforme módulo','spatial_resolution':'varia conforme camada do módulo; consultar asset e ATBD','temporal_coverage':'1985–2024 para áreas urbanizadas; outras camadas conforme módulo','temporal_resolution':'anual | períodos de 5 anos | camada estática conforme variável','update_frequency':'por coleção','product_status':'ativo','version_or_collection':'Coleção 10','enumeration_scope':'family_level','product_page_url':'https://brasil.mapbiomas.org/modulo-urbano/','methodology_url':'https://brasil.mapbiomas.org/modulo-urbano/','primary_or_derived':'derivado','limitations':'Camadas de declividade, HAND, vegetação e períodos de expansão têm significados, escalas e temporalidades distintas; proximidade de drenagem e alta declividade são fatores de exposição física, não estimativas diretas de risco de desastre.','last_verified':TODAY},
{'product_id':'DP000062','resource_id':'DR0010','product_name':'MapBiomas Degradação da Vegetação Nativa — versão 2','product_acronym':'MapBiomas Degradação v2','product_family':'Vetores de degradação da vegetação nativa','product_kind':'map_layer_collection','product_description':'Conjunto de camadas e estatísticas sobre vetores de degradação da vegetação nativa, incluindo fragmentação, borda, fogo, isolamento, idade da vegetação secundária e, para recortes específicos, distúrbio de dossel e corte seletivo.','research_areas':'Landscape ecology | Forest degradation | Fire ecology | Conservation | Remote sensing','keywords':'degradação | fragmentação | borda | fogo | isolamento | vegetação secundária | corte seletivo','geographic_coverage':'Brasil; distúrbio de dossel e corte seletivo beta restritos à Amazônia Legal','covers_brazil':'sim','spatial_support':'célula raster | fragmento | estatísticas territoriais','spatial_resolution':'varia por vetor; consultar asset e documentação','temporal_coverage':'1986–2023 para o conjunto nacional; 1988–2024 para distúrbio de dossel e corte seletivo beta','temporal_resolution':'anual ou métrica por período conforme vetor','update_frequency':'por versão do módulo','product_status':'ativo','version_or_collection':'versão 2 | alinhada à Coleção 10.1 para diversos vetores','enumeration_scope':'family_level','product_page_url':'https://brasil.mapbiomas.org/dados-do-modulo-mapbiomas-degradacao/','methodology_url':'https://brasil.mapbiomas.org/metodo-degradacao/','primary_or_derived':'derivado','limitations':'Os vetores representam dimensões distintas de exposição/degradação potencial e não devem ser somados como um único índice sem regra explícita. Distúrbio de dossel e corte seletivo estão em versão beta e têm cobertura territorial e temporal próprias.','last_verified':TODAY}
]
dists=[
{'distribution_id':'DD000073','product_id':'DP000060','distribution_name':'MapBiomas Água 5 — plataforma e lançamento','access_url':'https://brasil.mapbiomas.org/lancamentos/','format':'mapas | gráficos | estatísticas | downloads','access_protocol':'HTTPS web','access_tool':'navegador web | plataforma MapBiomas','free_download':'sim','authentication_required':'não','access_conditions':'acesso público e gratuito','license':'CC BY; atribuição da fonte requerida pelos termos do MapBiomas','provider_attribution_required':'sim','subset_support':'ano | mês | território | métrica','notes':'Coleção 5 lançada em 16/06/2026, com dados anuais e mensais de superfície de água de 1985 a 2025.','last_verified':TODAY},
{'distribution_id':'DD000074','product_id':'DP000060','distribution_name':'MapBiomas Água — destaques Coleção 5','access_url':'https://brasil.mapbiomas.org/destaques/','format':'PDF | material de síntese | DOI','access_protocol':'HTTPS web | DOI','access_tool':'navegador web','free_download':'sim','authentication_required':'não','access_conditions':'download público','license':'CC BY; atribuição requerida','provider_attribution_required':'sim','subset_support':'não se aplica','notes':'Página oficial publica os destaques da Coleção 5 do Mapeamento Anual de Superfície de Água com DOI próprio.','last_verified':TODAY},
{'distribution_id':'DD000075','product_id':'DP000061','distribution_name':'MapBiomas Módulo Urbano — plataforma','access_url':'https://plataforma.brasil.mapbiomas.org/urbano','format':'mapa interativo | gráficos | tabelas','access_protocol':'HTTPS web','access_tool':'navegador web','free_download':'sim','authentication_required':'não','access_conditions':'consulta pública','license':'CC BY; atribuição requerida pelos termos do MapBiomas','provider_attribution_required':'sim','subset_support':'ano | território | variável urbana','notes':'Permite consultar urbanização, vegetação urbana e variáveis de contexto físico no módulo urbano.','last_verified':TODAY},
{'distribution_id':'DD000076','product_id':'DP000061','distribution_name':'MapBiomas Módulo Urbano — assets Google Earth Engine','access_url':'https://brasil.mapbiomas.org/modulo-urbano/','format':'Google Earth Engine assets | estatísticas','access_protocol':'Google Earth Engine | HTTPS web','access_tool':'GEE | navegador web','free_download':'sim','authentication_required':'parcial','access_conditions':'página pública; uso do GEE requer conta/projeto habilitado','license':'CC BY; atribuição requerida pelos termos do MapBiomas','provider_attribution_required':'sim','subset_support':'camada | território | período conforme asset','notes':'A página documenta assets separados para HAND, declividade, períodos de expansão e vegetação urbana; os identificadores internos dos assets não substituem a versão científica do módulo.','last_verified':TODAY},
{'distribution_id':'DD000077','product_id':'DP000062','distribution_name':'MapBiomas Degradação v2 — plataforma e dados','access_url':'https://brasil.mapbiomas.org/dados-do-modulo-mapbiomas-degradacao/','format':'mapas | tabelas | gráficos | assets GEE','access_protocol':'HTTPS web | Google Earth Engine','access_tool':'navegador web | GEE','free_download':'sim','authentication_required':'parcial','access_conditions':'consulta pública; GEE requer conta/projeto habilitado','license':'CC BY; citação da fonte requerida','provider_attribution_required':'sim','subset_support':'vetor | bioma | estado | município | áreas protegidas | outros recortes','notes':'Versão 2 documenta vetores nacionais de 1986–2023 e camadas beta de distúrbio de dossel/corte seletivo para Amazônia Legal entre 1988 e 2024.','last_verified':TODAY},
{'distribution_id':'DD000078','product_id':'DP000062','distribution_name':'MapBiomas Degradação — estatísticas territoriais','access_url':'https://brasil.mapbiomas.org/estatisticas/','format':'tabelas | arquivos estatísticos','access_protocol':'HTTPS web | download','access_tool':'navegador web | planilha/R/Python','free_download':'sim','authentication_required':'não','access_conditions':'download público','license':'CC BY; atribuição requerida pelos termos do MapBiomas','provider_attribution_required':'sim','subset_support':'vetor | bioma | estado | município | bacia | área protegida','notes':'Estatísticas incluem fragmentação, morfologia, borda, fogo, isolamento e idade da vegetação secundária em múltiplos recortes territoriais.','last_verified':TODAY}
]
append(P,products); append(D,dists)
assert count(P)==62 and count(D)==78
print('materialized 3 products 6 distributions')
