from pathlib import Path

root=Path(__file__).resolve().parents[1]
p=root/'data/data_products.csv'
d=root/'data/product_distributions.csv'
pt=p.read_text(encoding='utf-8')
dt=d.read_text(encoding='utf-8')
assert 'DP000086' in pt and 'DP000087' not in pt
assert 'DD000102' in dt and 'DD000103' not in dt
products=[
'DP000087,DR0064,Contas de Ecossistemas — Uso da Terra nos Biomas Brasileiros 2000–2018,Uso da Terra Biomas 2000–2018,Contas de Extensão dos Ecossistemas,indicator_family,"Conta experimental de extensão dos ecossistemas que analisa áreas naturais e antropizadas e suas conversões nos seis biomas terrestres brasileiros entre 2000 e 2018.",Ecosystem accounting | Land use | Conservation | Environmental statistics,extensão dos ecossistemas | biomas | áreas naturais | áreas antropizadas | mudanças de uso da terra,Brasil por seis biomas terrestres,sim,bioma | célula de grade | classe de cobertura e uso,grade territorial estatística de 1 km² usada nas contas; vetores e tabelas por bioma,2000–2018,anos selecionados da série e indicadores de mudança,experimental; edição específica,experimental,2000–2018; publicado em 2020,complete,https://www.ibge.gov.br/geociencias/informacoes-ambientais/estatisticas-e-indicadores-ambientais/28920-contas-de-ecossistemas.html?edicao=28921,https://www.ibge.gov.br/geociencias/informacoes-ambientais/estatisticas-e-indicadores-ambientais/28920-contas-de-ecossistemas.html?edicao=28921&t=acesso-ao-produto,derivado,"A conta deriva do Monitoramento da Cobertura e Uso da Terra e usa grade estatística; mudanças de extensão são aproximações de condição e não equivalem a medidas diretas de integridade ecológica.",2026-08-15',
'DP000088,DR0064,Contas de Ecossistemas — Uso da Terra nos Biomas Brasileiros 2018–2020,Uso da Terra Biomas 2018–2020,Contas de Extensão dos Ecossistemas,indicator_family,"Atualização experimental das Contas de Extensão dos Ecossistemas com síntese das áreas naturais e antropizadas e mudanças de uso da terra nos biomas brasileiros entre 2018 e 2020.",Ecosystem accounting | Land use | Conservation | Environmental statistics,extensão dos ecossistemas | biomas | áreas naturais | áreas antropizadas | 2018-2020,Brasil por seis biomas terrestres,sim,bioma | célula de grade | classe de cobertura e uso,grade territorial estatística de 1 km² conforme nota técnica,2018–2020,biênio,experimental; edição específica,experimental,2018–2020; divulgado em 2022,complete,https://www.ibge.gov.br/estatisticas/multidominio/meio-ambiente/28920-contas-de-ecossistemas.html?edicao=35140,https://www.ibge.gov.br/estatisticas/multidominio/meio-ambiente/28920-contas-de-ecossistemas.html?edicao=35140,derivado,"Complementa a edição 2000–2018 e utiliza dados mais recentes do Monitoramento da Cobertura e Uso da Terra; efeitos de borda da grade de 1 km² geram pequenas diferenças em relação às áreas oficiais dos biomas.",2026-08-15',
'DP000089,DR0064,Contas de Ecossistemas — Espécies Ameaçadas de Extinção no Brasil 2014,Espécies Ameaçadas 2014,Contas de Espécies Ameaçadas,indicator_family,"Síntese experimental das listas oficiais de fauna e flora ameaçadas, com números de espécies por categoria de ameaça, bioma e tipo de ambiente para o ano de referência 2014.",Biodiversity conservation | Ecosystem accounting | Threat assessment | Environmental statistics,espécies ameaçadas | fauna | flora | biomas | IUCN | ICMBio | CNCFlora,Brasil | biomas | ambientes terrestre água doce e marinho,sim,espécie | categoria de ameaça | bioma | ambiente,agregação por bioma e ambiente; não é mapa de ocorrência individual,2014,ano de referência,experimental; edição específica,experimental,2014; publicado em 2020,complete,https://www.ibge.gov.br/estatisticas/multidominio/meio-ambiente/28920-contas-de-ecossistemas.html?edicao=28973,https://www.ibge.gov.br/estatisticas/multidominio/meio-ambiente/28920-contas-de-ecossistemas.html?edicao=28973,derivado,"Baseia-se nas listas oficiais e no estado de conservação disponível; números de espécies ameaçadas não medem abundância populacional, tendência demográfica ou risco local sem dados adicionais.",2026-08-15',
'DP000090,DR0064,Contas de Ecossistemas — Espécies Ameaçadas de Extinção no Brasil 2022,Espécies Ameaçadas 2022,Contas de Espécies Ameaçadas,indicator_family,"Atualização das estatísticas de espécies ameaçadas com dados mais recentes das listas oficiais divulgadas pelo Ministério do Meio Ambiente, mantendo a metodologia da edição de 2014.",Biodiversity conservation | Ecosystem accounting | Threat assessment | Environmental statistics,espécies ameaçadas | fauna | flora | biomas | MMA | ICMBio | CNCFlora,Brasil | biomas | ambientes terrestre água doce e marinho,sim,espécie | categoria de ameaça | bioma | ambiente,agregação por bioma e ambiente; resultados tabulados no SIDRA,2022,ano de referência,por atualização das listas oficiais,experimental,2022 — atualização da série,complete,https://www.ibge.gov.br/geociencias/informacoes-ambientais/estudos-ambientais/28920-contas-de-ecossistemas.html,https://www.ibge.gov.br/geociencias/informacoes-ambientais/estudos-ambientais/28920-contas-de-ecossistemas.html,derivado,"A metodologia declarada pelo IBGE não mudou em relação à edição de 2014, mas a base oficial de espécies ameaçadas foi atualizada; comparações devem preservar universo avaliado e listas vigentes em cada referência.",2026-08-15'
]
dists=[
'DD000103,DP000087,IBGE — Contas de Extensão 2000–2018 — SIDRA vetores mapas e tabelas,https://www.ibge.gov.br/geociencias/informacoes-ambientais/estatisticas-e-indicadores-ambientais/28920-contas-de-ecossistemas.html?edicao=28921&t=acesso-ao-produto,SIDRA | XLSX | ODS | Shapefile | PDF | PNG,HTTP download | SIDRA,navegador web | planilha | SIG,sim,não,downloads públicos da edição e tabelas no SIDRA,licença específica dos dados não localizada nesta auditoria; observar termos do IBGE,sim,bioma | classe | período | indicador,"Inclui Contas da Terra por bioma, Contas de Extensão 2000–2018, vetores e Indicador de Intensidade de Mudanças; preservar a definição de cada indicador.",2026-08-15',
'DD000104,DP000088,IBGE — Contas de Extensão 2018–2020 — SIDRA e publicação,https://www.ibge.gov.br/estatisticas/multidominio/meio-ambiente/28920-contas-de-ecossistemas.html?edicao=35140,SIDRA | publicação | downloads conforme edição,HTTP download | SIDRA,navegador web | planilha,sim,não,consulta pública no SIDRA e downloads da edição,licença específica dos dados não localizada nesta auditoria; observar termos do IBGE,sim,bioma | classe | período,"Nota técnica informa efeito de borda da grade territorial estatística de 1 km² e inclusão das 12 milhas do mar territorial nas áreas calculadas.",2026-08-15',
'DD000105,DP000089,IBGE — Espécies Ameaçadas 2014 — publicação e downloads,https://www.ibge.gov.br/estatisticas/multidominio/meio-ambiente/28920-contas-de-ecossistemas.html?edicao=28973,PDF | tabelas e downloads conforme edição,HTTP download,navegador web | planilha,sim,não,downloads públicos da edição,licença específica dos dados não localizada nesta auditoria; observar termos do IBGE,sim,categoria de ameaça | bioma | ambiente,"Resultados derivam das listas oficiais de ICMBio e CNCFlora/JBRJ e devem ser interpretados como síntese de estado de conservação, não como inventário de ocorrências.",2026-08-15',
'DD000106,DP000090,IBGE — Espécies Ameaçadas 2022 — SIDRA,https://www.ibge.gov.br/geociencias/informacoes-ambientais/estudos-ambientais/28920-contas-de-ecossistemas.html,SIDRA | tabelas web,HTTPS web | SIDRA,navegador web | SIDRA,sim,não,resultados tabulados disponíveis no SIDRA,licença específica da tabela não localizada nesta auditoria; observar termos do IBGE,sim,categoria de ameaça | bioma | ambiente | grupo,"A atualização de 2022 complementa a série de 2014 com listas mais recentes do MMA; preservar ano de referência e universo de espécies avaliadas.",2026-08-15'
]
with p.open('a',encoding='utf-8') as f:
    for x in products: f.write(x+'\n')
with d.open('a',encoding='utf-8') as f:
    for x in dists: f.write(x+'\n')
