#!/usr/bin/env python3
import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TODAY = '2026-08-14'

PRODUCTS = [
{
'product_id':'DP000063','resource_id':'DR0006','product_name':'Painel do Fogo — eventos de incêndio e queimadas','product_acronym':'Painel do Fogo','product_family':'Monitoramento operacional de eventos de fogo','product_kind':'dataset_series','product_description':'Plataforma operacional do CENSIPAM que integra detecções de múltiplos satélites para delimitar eventos de fogo, atualizar perímetros e status e apoiar priorização e acionamento de equipes de combate.','research_areas':'Fire ecology | Environmental monitoring | Remote sensing | Disaster management','keywords':'eventos de fogo | incêndios | queimadas | satélite | Amazônia | CENSIPAM','geographic_coverage':'Brasil, com uso operacional prioritário na Amazônia e outros biomas monitorados','covers_brazil':'sim','spatial_support':'evento de fogo | perímetro | município | estado','spatial_resolution':'depende dos sensores e camadas integradas','temporal_coverage':'monitoramento corrente; boletins preservam histórico recente de eventos','temporal_resolution':'quase em tempo real | boletins periódicos','update_frequency':'operacional','product_status':'ativo','version_or_collection':'Painel do Fogo corrente','enumeration_scope':'family_level','product_page_url':'https://www.gov.br/censipam/pt-br/atuacao/painel-do-fogo','methodology_url':'https://www.gov.br/censipam/pt-br/atuacao/painel-do-fogo','primary_or_derived':'derivado','limitations':'Evento de fogo integra detecções e informação contextual; não equivale a uma contagem simples de focos de calor nem a área queimada consolidada. Registrar data, status, sensores e camadas territoriais usados.','last_verified':TODAY},
{
'product_id':'DP000064','resource_id':'DR0006','product_name':'SIPAMHidro — monitoramento hidrometeorológico da Amazônia Legal','product_acronym':'SIPAMHidro','product_family':'Monitoramento hidrológico e meteorológico','product_kind':'dataset_series','product_description':'Sistema do CENSIPAM para acompanhamento de níveis de rios, chuva, condições meteorológicas e indicadores críticos, com suporte à avaliação de eventos extremos e elaboração de boletins hidrometeorológicos.','research_areas':'Hydrology | Meteorology | Climate impacts | Disaster risk','keywords':'SIPAMHidro | níveis de rios | chuva | hidrologia | radar | Amazônia','geographic_coverage':'Amazônia Legal','covers_brazil':'sim','spatial_support':'estações | rios | radar | recortes territoriais','spatial_resolution':'varia por estação, radar e camada','temporal_coverage':'monitoramento corrente; histórico varia por rede e produto','temporal_resolution':'subdiária a mensal conforme componente','update_frequency':'operacional e periódica','product_status':'ativo','version_or_collection':'SIPAMHidro corrente','enumeration_scope':'family_level','product_page_url':'https://www.gov.br/censipam/pt-br/atuacao/portal-de-servicos','methodology_url':'https://www.gov.br/censipam/pt-br/atuacao/monitoramento-de-eventos-extremos','primary_or_derived':'misto','limitations':'O sistema combina observações, produtos de radar, diagnósticos e prognósticos com periodicidades distintas. Preservar origem, estação/camada, timestamp e natureza observada ou prevista de cada variável.','last_verified':TODAY},
{
'product_id':'DP000065','resource_id':'DR0006','product_name':'API de Meteorologia CENSIPAM v1','product_acronym':'API Meteorologia CENSIPAM','product_family':'Acesso programático a dados meteorológicos','product_kind':'data_service','product_description':'API OAS 3.0 do CENSIPAM para consulta programática de dados meteorológicos, incluindo previsão do tempo e dados de Estações Meteorológicas de Superfície.','research_areas':'Meteorology | Environmental data infrastructure | Operational forecasting','keywords':'API | meteorologia | previsão | EMS | CENSIPAM | OAS','geographic_coverage':'cobertura conforme estações e produtos do CENSIPAM','covers_brazil':'sim','spatial_support':'estação | localidade | resposta de serviço','spatial_resolution':'herdada do dado consultado','temporal_coverage':'corrente; varia por endpoint','temporal_resolution':'varia por endpoint','update_frequency':'operacional','product_status':'ativo','version_or_collection':'v1 | OAS 3.0','enumeration_scope':'complete','product_page_url':'https://panorama.sipam.gov.br/api/meteorologia/v1','methodology_url':'https://panorama.sipam.gov.br/api/meteorologia/v1','primary_or_derived':'serviço','limitations':'O acesso exige solicitação prévia e duas chaves exclusivas; previsão e observação de estação são categorias diferentes e devem ser preservadas no uso analítico.','last_verified':TODAY},
{
'product_id':'DP000066','resource_id':'DR0007','product_name':'UrbVerde — cobertura vegetal urbana','product_acronym':'UrbVerde Vegetação','product_family':'Vegetação urbana e desigualdade ambiental','product_kind':'dataset_series','product_description':'Mapas e estatísticas intraurbanas de cobertura vegetal com acompanhamento anual e comparação territorial, incluindo métricas por setores censitários e exportação tabular quando disponível.','research_areas':'Urban ecology | Vegetation science | Environmental justice | Remote sensing','keywords':'cobertura vegetal | vegetação urbana | setores censitários | desigualdade ambiental | UrbVerde','geographic_coverage':'Brasil conforme municípios processados; origem histórica no estado de São Paulo','covers_brazil':'sim','spatial_support':'setor censitário | território urbano | município','spatial_resolution':'intraurbana; depende da camada e sensor','temporal_coverage':'série anual conforme município e camada','temporal_resolution':'anual','update_frequency':'anual conforme processamento da plataforma','product_status':'ativo','version_or_collection':'plataforma corrente 2026','enumeration_scope':'family_level','product_page_url':'https://urbverde.iau.usp.br/mapa','methodology_url':'https://urbverde.iau.usp.br/mapa','primary_or_derived':'derivado','limitations':'Cobertura vegetal é derivada de sensoriamento remoto e não equivale automaticamente a qualidade ecológica, biodiversidade ou acesso público a áreas verdes. Registrar ano, recorte e metodologia da camada.','last_verified':TODAY},
{
'product_id':'DP000067','resource_id':'DR0007','product_name':'UrbVerde — temperatura de superfície e ilha de calor','product_acronym':'UrbVerde Temperatura','product_family':'Clima urbano e temperatura de superfície','product_kind':'dataset_series','product_description':'Mapas e estatísticas anuais de temperatura de superfície urbana, incluindo médias, máximas, amplitude e indicadores relacionados à ilha de calor e vulnerabilidade populacional.','research_areas':'Urban climate | Climate adaptation | Remote sensing | Public health','keywords':'temperatura de superfície | ilha de calor | Landsat | vulnerabilidade | clima urbano','geographic_coverage':'Brasil conforme municípios processados','covers_brazil':'sim','spatial_support':'pixel | setor censitário | território urbano | município','spatial_resolution':'30 m para a camada de temperatura documentada com Landsat 8/9','temporal_coverage':'anos processados pela plataforma; metodologia anual','temporal_resolution':'anual','update_frequency':'anual conforme processamento','product_status':'ativo','version_or_collection':'plataforma corrente 2026','enumeration_scope':'family_level','product_page_url':'https://urbverde.iau.usp.br/mapa?category=climate&layer=surface_temp&viewMode=map','methodology_url':'https://urbverde.iau.usp.br/mapa?category=climate&layer=surface_temp&viewMode=map','primary_or_derived':'derivado','limitations':'Temperatura de superfície terrestre não é temperatura do ar. A metodologia usa Landsat 8/9 a 30 m e janelas sazonais específicas; comparações exigem preservar ano-base e procedimento de composição.','last_verified':TODAY},
{
'product_id':'DP000068','resource_id':'DR0007','product_name':'UrbVerde — Índice de Desigualdade Socioambiental','product_acronym':'IDSA UrbVerde','product_family':'Desigualdade socioambiental urbana','product_kind':'indicator_family','product_description':'Indicador espacial da desigualdade socioambiental associado à distribuição intraurbana de condições ambientais e sociais, disponibilizado em mapa e tabela por recortes urbanos.','research_areas':'Environmental justice | Urban ecology | Socioecological systems | Public policy','keywords':'desigualdade socioambiental | IDSA | vulnerabilidade | vegetação | setores censitários','geographic_coverage':'Brasil conforme municípios processados','covers_brazil':'sim','spatial_support':'setor censitário | município','spatial_resolution':'intraurbana','temporal_coverage':'varia conforme ano-base disponível','temporal_resolution':'anual quando disponibilizado','update_frequency':'conforme atualização da plataforma','product_status':'ativo','version_or_collection':'plataforma corrente 2026','enumeration_scope':'complete','product_page_url':'https://urbverde.iau.usp.br/mapa?layer=idsa&viewMode=map','methodology_url':'https://urbverde.iau.usp.br/mapa?layer=idsa&viewMode=map','primary_or_derived':'derivado','limitations':'Índice composto não deve ser interpretado como medida direta de causalidade ou de bem-estar individual; componentes, ano e unidade espacial devem ser preservados.','last_verified':TODAY},
{
'product_id':'DP000069','resource_id':'DR0007','product_name':'UrbVerde — Painel Políticas Públicas e riscos climáticos','product_acronym':'UrbVerde Políticas Públicas','product_family':'Indicadores para planejamento climático municipal','product_kind':'indicator_family','product_description':'Painel beta voltado ao acompanhamento anual de dados urbanos, ambientais e riscos climáticos para apoiar planos climáticos municipais, com indicadores como risco climático a arboviroses e vulnerabilidade alimentar e nutricional.','research_areas':'Climate adaptation | Public health | Urban planning | Environmental justice','keywords':'riscos climáticos | arboviroses | vulnerabilidade alimentar | planos climáticos | municípios','geographic_coverage':'municípios do ABC Paulista na versão beta verificada','covers_brazil':'sim','spatial_support':'setor censitário | município','spatial_resolution':'intraurbana','temporal_coverage':'anos inseridos no painel; 2024 verificado em camadas consultadas','temporal_resolution':'anual','update_frequency':'em desenvolvimento','product_status':'experimental','version_or_collection':'beta 2026','enumeration_scope':'family_level','product_page_url':'https://urbverde.iau.usp.br/mapa?viewMode=policies','methodology_url':'https://urbverde.iau.usp.br/mapa?viewMode=policies','primary_or_derived':'derivado','limitations':'Painel explicitamente beta e, na versão verificada, restrito ao ABC Paulista; indicadores ainda estão sendo inseridos. Não generalizar disponibilidade ou desempenho para todos os municípios brasileiros.','last_verified':TODAY},
{
'product_id':'DP000070','resource_id':'DR0055','product_name':'OICS — Banco de Soluções para Cidades Sustentáveis','product_acronym':'OICS Soluções','product_family':'Soluções de inovação urbana sustentável','product_kind':'federated_catalog','product_description':'Catálogo curado de modelos replicáveis de alternativas sustentáveis para desafios urbanos, organizado por temas como água, energia, mobilidade, ambiente construído, resíduos sólidos e soluções baseadas na natureza.','research_areas':'Urban sustainability | Nature-based solutions | Innovation | Public policy','keywords':'soluções urbanas | inovação | sustentabilidade | SbN | energia | água | mobilidade','geographic_coverage':'Brasil como foco de aplicação; soluções podem ter referências e casos internacionais','covers_brazil':'sim','spatial_support':'registro de solução | aplicabilidade por porte e contexto territorial','spatial_resolution':'não se aplica','temporal_coverage':'conteúdo corrente da plataforma','temporal_resolution':'não se aplica','update_frequency':'curadoria contínua ou irregular','product_status':'ativo','version_or_collection':'catálogo corrente 2026','enumeration_scope':'external_index','product_page_url':'https://oics.cgee.org.br/solucoes-e-casos/solucoes','methodology_url':'https://oics.cgee.org.br/pt/-/observat%C3%B3rio-de-inova%C3%A7%C3%A3o-para-cidades-sustent%C3%A1veis','primary_or_derived':'agregador','limitations':'Registros são produtos de conhecimento aplicado, não observações ambientais homogêneas. Nível de maturidade, aplicabilidade, indicadores de desempenho e evidências devem ser avaliados por solução.','last_verified':TODAY},
{
'product_id':'DP000071','resource_id':'DR0055','product_name':'OICS — Estudos de Caso','product_acronym':'OICS Casos','product_family':'Aplicações práticas de soluções sustentáveis','product_kind':'federated_catalog','product_description':'Catálogo de aplicações práticas de soluções de sustentabilidade urbana, documentando contexto, resultados esperados ou observados, replicabilidade, referências e anexos.','research_areas':'Urban sustainability | Implementation science | Public policy | Innovation','keywords':'estudos de caso | cidades sustentáveis | implementação | replicabilidade | inovação','geographic_coverage':'Brasil e casos internacionais conforme registro','covers_brazil':'sim','spatial_support':'localidade do caso | registro documental','spatial_resolution':'não se aplica','temporal_coverage':'varia por estudo de caso','temporal_resolution':'não se aplica','update_frequency':'curadoria contínua ou irregular','product_status':'ativo','version_or_collection':'catálogo corrente 2026','enumeration_scope':'external_index','product_page_url':'https://oics.cgee.org.br/solucoes-e-casos/casos','methodology_url':'https://oics.cgee.org.br/pt/-/observat%C3%B3rio-de-inova%C3%A7%C3%A3o-para-cidades-sustent%C3%A1veis','primary_or_derived':'agregador','limitations':'Casos têm contextos, métricas e desenhos de avaliação heterogêneos; não sintetizar desempenho entre casos sem harmonizar método, baseline e resultado reportado.','last_verified':TODAY},
{
'product_id':'DP000072','resource_id':'DR0055','product_name':'OICS — Tipologias territoriais e Mapa Interativo','product_acronym':'OICS Tipologias','product_family':'Caracterização territorial para sustentabilidade urbana','product_kind':'indicator_family','product_description':'Sistema SIG Web que caracteriza cidades-regiões por tipologias construídas a partir de indicadores, dados geográficos e índices sociodemográficos e ambientais, conectando características territoriais a soluções sustentáveis.','research_areas':'Territorial analysis | Urban sustainability | Socioecological systems | GIS','keywords':'tipologias | cidades-regiões | indicadores | dados geográficos | SIG Web | sustentabilidade','geographic_coverage':'Brasil','covers_brazil':'sim','spatial_support':'cidade-região | camadas e indicadores territoriais','spatial_resolution':'varia conforme indicador e dado geográfico','temporal_coverage':'varia conforme indicador de origem','temporal_resolution':'varia conforme indicador','update_frequency':'conforme atualização dos indicadores e da plataforma','product_status':'ativo','version_or_collection':'mapa interativo corrente 2026','enumeration_scope':'family_level','product_page_url':'https://oics.cgee.org.br/mapa-interativo','methodology_url':'https://oics.cgee.org.br/mapa-interativo','primary_or_derived':'derivado','limitations':'Tipologias integram indicadores e dados com escalas e referências temporais distintas; não tratá-las como observações primárias ou como classificação causal da sustentabilidade municipal.','last_verified':TODAY},
]

DISTS = [
('DD000079','DP000063','Painel do Fogo — interface operacional','https://panorama.sipam.gov.br/painel-do-fogo/','visualização web','HTTP','navegador web','sim','não','consulta pública','não localizada','sim','filtros territoriais e temporais','Interface operacional; usar página institucional do CENSIPAM para interpretação e finalidade.'),
('DD000080','DP000064','PANORAMA / SIPAMHidro','https://panorama.sipam.gov.br/','visualização web e dados heterogêneos','HTTP','navegador web','parcial','não','consulta conforme módulo','não localizada','sim','conforme módulo','Dados e ferramentas hidrometeorológicas são heterogêneos; preservar a origem de cada camada.'),
('DD000081','DP000065','API Meteorologia CENSIPAM v1','https://panorama.sipam.gov.br/api/meteorologia/v1','JSON','REST API','cliente HTTP','sim','sim','solicitação de acesso; duas chaves exclusivas','não localizada','sim','por endpoint e parâmetros','Documentação OAS 3.0 expõe endpoints de previsão e EMS; autenticação é obrigatória após concessão.'),
('DD000082','DP000066','UrbVerde — mapa e exportação de cobertura vegetal','https://urbverde.iau.usp.br/mapa','mapa web | CSV | PNG','HTTP','navegador web','sim','não','exportação depende da camada e município','termos de uso da UrbVerde','sim','ano | município | recorte','A plataforma oferece exportação tabular em camadas consultadas; disponibilidade pode variar.'),
('DD000083','DP000067','UrbVerde — temperatura de superfície','https://urbverde.iau.usp.br/mapa?category=climate&layer=surface_temp&viewMode=map','mapa web | CSV | PNG','HTTP','navegador web','sim','não','consulta e exportação pela interface','termos de uso da UrbVerde','sim','ano | município | recorte','Camada documentada com Landsat 8/9 a 30 m; temperatura de superfície não equivale à temperatura do ar.'),
('DD000084','DP000068','UrbVerde — IDSA','https://urbverde.iau.usp.br/mapa?layer=idsa&viewMode=map','mapa web | CSV | PNG','HTTP','navegador web','sim','não','consulta e exportação pela interface','termos de uso da UrbVerde','sim','ano | município | setor','Exportação CSV observada na interface para o índice.'),
('DD000085','DP000069','UrbVerde — Painel Políticas Públicas beta','https://urbverde.iau.usp.br/mapa?viewMode=policies','mapa web | CSV | PNG','HTTP','navegador web','sim','não','versão beta; cobertura restrita ao ABC Paulista na verificação','termos de uso da UrbVerde','sim','indicador | ano | município','Não assumir disponibilidade nacional do painel beta.'),
('DD000086','DP000070','OICS — catálogo de soluções','https://oics.cgee.org.br/solucoes-e-casos/solucoes','conteúdo web estruturado','HTTP','navegador web','não','não','consulta pública por navegação e filtros','não localizada','sim','tema | tipo de inovação | aplicabilidade','Cada solução possui página própria com informações, indicadores de desempenho, referências e anexos.'),
('DD000087','DP000071','OICS — catálogo de estudos de caso','https://oics.cgee.org.br/solucoes-e-casos/casos','conteúdo web estruturado','HTTP','navegador web','não','não','consulta pública por navegação e filtros','não localizada','sim','tema | solução | localização','Casos são registros documentais heterogêneos e não constituem um dataset observacional uniforme.'),
('DD000088','DP000072','OICS — Mapa Interativo','https://oics.cgee.org.br/mapa-interativo','SIG Web | mapas | indicadores','HTTP','navegador web','não','não','consulta pública pelo SIG Web','não localizada','sim','tipologia | indicador | cidade-região','O mapa integra tipologias, indicadores, dados geográficos e soluções; preservar a fonte original de cada indicador quando usada quantitativamente.'),
]

pf = ROOT/'data/data_products.csv'
df = ROOT/'data/product_distributions.csv'
with pf.open(encoding='utf-8-sig', newline='') as f:
    rows=list(csv.DictReader(f))
assert len(rows)==62 and rows[-1]['product_id']=='DP000062'
fields=list(rows[0].keys())
for p in PRODUCTS:
    assert set(p)==set(fields), (p['product_id'], set(fields)-set(p), set(p)-set(fields))
with pf.open('a',encoding='utf-8',newline='') as f:
    w=csv.DictWriter(f,fieldnames=fields,lineterminator='\n')
    for p in PRODUCTS: w.writerow(p)

with df.open(encoding='utf-8-sig', newline='') as f:
    drows=list(csv.DictReader(f))
assert len(drows)==78 and drows[-1]['distribution_id']=='DD000078'
dfields=list(drows[0].keys())
with df.open('a',encoding='utf-8',newline='') as f:
    w=csv.DictWriter(f,fieldnames=dfields,lineterminator='\n')
    for vals in DISTS:
        row=dict(zip(dfields[:-1], vals))
        row['last_verified']=TODAY
        assert set(row)==set(dfields)
        w.writerow(row)

print(f'Added {len(PRODUCTS)} products and {len(DISTS)} distributions')
