#!/usr/bin/env python3
import csv
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROD = ROOT / 'data' / 'data_products.csv'
DIST = ROOT / 'data' / 'product_distributions.csv'

products = [
['DP000713','DR0123','BDC — classificação LULC Landsat-8 da Amazônia','BDC LULC L8 Amazon','Brazil Data Cube — classificações LULC','dataset_series','Mapa classificado de uso e cobertura da terra para o bioma Amazônia gerado pelo Brazil Data Cube a partir de séries temporais Landsat-8/OLI e métodos de aprendizado de máquina.','Land use and land cover | Forest ecology | Remote sensing | Environmental monitoring','Landsat-8 | OLI | LULC | classification | Amazon | machine learning','Bioma Amazônia — Brasil','sim','célula raster classificada | coleção STAC','30 m','coleção histórica; consultar itens/metadados STAC','produto classificado por período da coleção','sem atualização confirmada','ativo','LCC_L8_30_16D_STK_Amazonia-TC-1','complete','https://data.inpe.br/bdc/stac/v1/collections/LCC_L8_30_16D_STK_Amazonia-TC-1','https://data.inpe.br/bdc/classificacoes-de-uso-e-cobertura-da-terra/','derivado','Classificação derivada de cubos Landsat-8 e amostras de treinamento; classes e acurácia dependem do modelo, amostras e período. Não tratar como observação de campo, TerraClass ou PRODES.','2026-08-18'],
['DP000714','DR0123','BDC — classificação LULC Landsat-8 da Caatinga','BDC LULC L8 Caatinga','Brazil Data Cube — classificações LULC','dataset_series','Mapa classificado de uso e cobertura da terra para o bioma Caatinga gerado pelo Brazil Data Cube a partir de séries temporais Landsat-8/OLI e aprendizado de máquina.','Land use and land cover | Remote sensing | Environmental monitoring','Landsat-8 | OLI | LULC | classification | Caatinga | machine learning','Bioma Caatinga — Brasil','sim','célula raster classificada | coleção STAC','30 m','coleção histórica; consultar itens/metadados STAC','produto classificado por período da coleção','sem atualização confirmada','ativo','LCC_L8_30_16D_STK_Caatinga-1','complete','https://data.inpe.br/bdc/stac/v1/collections/LCC_L8_30_16D_STK_Caatinga-1','https://brazil-data-cube.github.io/products/classifications.html','derivado','Classificação derivada; não inferir condição ecológica local sem considerar legenda, amostras, período e desempenho por classe. Não é observação independente das imagens/cubos de origem.','2026-08-18'],
['DP000715','DR0123','BDC — classificação LULC Landsat-8 do Cerrado','BDC LULC L8 Cerrado','Brazil Data Cube — classificações LULC','dataset_series','Mapa classificado de uso e cobertura da terra para o bioma Cerrado gerado pelo Brazil Data Cube a partir de séries temporais Landsat-8/OLI e aprendizado de máquina.','Land use and land cover | Savanna ecology | Remote sensing | Environmental monitoring','Landsat-8 | OLI | LULC | classification | Cerrado | machine learning','Bioma Cerrado — Brasil','sim','célula raster classificada | coleção STAC','30 m','coleção histórica; consultar itens/metadados STAC','produto classificado por período da coleção','sem atualização confirmada','ativo','LCC_L8_30_16D_STK_Cerrado-1','complete','https://data.inpe.br/bdc/stac/v1/collections/LCC_L8_30_16D_STK_Cerrado-1','https://data.inpe.br/bdc/classificacoes-de-uso-e-cobertura-da-terra/','derivado','Classificação derivada de séries temporais e amostras de treinamento; não confundir com TerraClass Cerrado, MapBiomas ou observação de campo. Comparações exigem compatibilidade de legenda e período.','2026-08-18'],
['DP000716','DR0123','BDC — classificação LULC Landsat-8 da Mata Atlântica','BDC LULC L8 Mata Atlantica','Brazil Data Cube — classificações LULC','dataset_series','Mapa classificado de uso e cobertura da terra para o bioma Mata Atlântica gerado pelo Brazil Data Cube a partir de séries temporais Landsat-8/OLI e aprendizado de máquina.','Land use and land cover | Forest ecology | Remote sensing | Environmental monitoring','Landsat-8 | OLI | LULC | classification | Atlantic Forest | machine learning','Bioma Mata Atlântica — Brasil','sim','célula raster classificada | coleção STAC','30 m','coleção histórica; consultar itens/metadados STAC','produto classificado por período da coleção','sem atualização confirmada','ativo','LCC_L8_30_16D_STK_MataAtlantica-1','complete','https://data.inpe.br/bdc/stac/v1/collections/LCC_L8_30_16D_STK_MataAtlantica-1','https://brazil-data-cube.github.io/products/classifications.html','derivado','Produto classificado derivado; não pressupor atualização corrente, equivalência de classes com outros programas ou acurácia espacial uniforme em todo o bioma.','2026-08-18'],
['DP000717','DR0123','BDC — classificação LULC Landsat-8 do Pampa','BDC LULC L8 Pampa','Brazil Data Cube — classificações LULC','dataset_series','Mapa classificado de uso e cobertura da terra para o bioma Pampa gerado pelo Brazil Data Cube a partir de séries temporais Landsat-8/OLI e aprendizado de máquina.','Land use and land cover | Grassland ecology | Remote sensing | Environmental monitoring','Landsat-8 | OLI | LULC | classification | Pampa | machine learning','Bioma Pampa — Brasil','sim','célula raster classificada | coleção STAC','30 m','coleção histórica; consultar itens/metadados STAC','produto classificado por período da coleção','sem atualização confirmada','ativo','LCC_L8_30_16D_STK_Pampa-1','complete','https://data.inpe.br/bdc/stac/v1/collections/LCC_L8_30_16D_STK_Pampa-1','https://brazil-data-cube.github.io/products/classifications.html','derivado','Classificação derivada; classes campestres e agrícolas dependem da legenda e do treinamento. Não usar como substituto automático de levantamentos de campo ou de outras séries LULC.','2026-08-18'],
['DP000718','DR0123','BDC — classificação LULC Landsat-8 do Pantanal','BDC LULC L8 Pantanal','Brazil Data Cube — classificações LULC','dataset_series','Mapa classificado de uso e cobertura da terra para o bioma Pantanal gerado pelo Brazil Data Cube a partir de séries temporais Landsat-8/OLI e aprendizado de máquina.','Land use and land cover | Wetland ecology | Remote sensing | Environmental monitoring','Landsat-8 | OLI | LULC | classification | Pantanal | machine learning','Bioma Pantanal — Brasil','sim','célula raster classificada | coleção STAC','30 m','coleção histórica; consultar itens/metadados STAC','produto classificado por período da coleção','sem atualização confirmada','ativo','LCC_L8_30_16D_STK_Pantanal-1','complete','https://data.inpe.br/bdc/stac/v1/collections/LCC_L8_30_16D_STK_Pantanal-1','https://data.inpe.br/bdc/classificacoes-de-uso-e-cobertura-da-terra/','derivado','Classificação derivada; dinâmica de inundação e sazonalidade podem afetar separabilidade das classes. Não interpretar classe como condição hidrológica instantânea.','2026-08-18'],
['DP000719','DR0123','BDC — classificação LULC Sentinel-2 da Amazônia','BDC LULC S2 Amazon','Brazil Data Cube — classificações LULC','dataset_series','Mapa classificado de uso e cobertura da terra para o bioma Amazônia gerado pelo Brazil Data Cube com séries temporais Sentinel-2/MSI e aprendizado de máquina.','Land use and land cover | Forest ecology | Remote sensing | Environmental monitoring','Sentinel-2 | MSI | LULC | classification | Amazon | machine learning','Bioma Amazônia — Brasil','sim','célula raster classificada | coleção STAC','10 m','coleção histórica; consultar itens/metadados STAC','produto classificado por período da coleção','sem atualização confirmada','ativo','LCC_S2_10_16D_STK_Amazonia-1','complete','https://data.inpe.br/bdc/stac/v1/collections/LCC_S2_10_16D_STK_Amazonia-1','https://brazil-data-cube.github.io/products/classifications.html','derivado','Classificação derivada de Sentinel-2; não é observação independente das imagens/cubos de origem e não deve ser tratada como equivalente à classificação Landsat sem harmonizar legenda, resolução, amostras e período.','2026-08-18'],
['DP000720','DR0123','Brazil Data Cube — cubo Landsat multissensor mensal histórico','LANDSAT-MOZ 1M','Brazil Data Cube — cubos Landsat','dataset_series','Cubo multidimensional Landsat histórico do Brazil Data Cube composto por melhor pixel em janelas temporais mensais/bimestrais conforme a versão, integrando sensores de diferentes missões Landsat em grade BDC_MOZ.','Remote sensing | Land use and land cover | Vegetation dynamics | Environmental monitoring','Landsat | TM | ETM | OLI | data cube | LCF | monthly | BDC_MOZ','Brasil conforme cobertura da coleção','sim','célula raster | cubo multidimensional','30 m','coleção histórica; consultar metadados STAC','composição temporal da coleção','coleção histórica','ativo','LANDSAT-MOZ_30_1M_STK-1','complete','https://data.inpe.br/bdc/stac/v1/collections/LANDSAT-MOZ_30_1M_STK-1','https://data.inpe.br/bdc/cubo-de-dados/','derivado','Cubo composto a partir de múltiplas plataformas Landsat; sensores, disponibilidade e qualidade variam no tempo. LCF/STK seleciona pixels e não representa aquisição sinótica. A documentação atual apresenta discrepância entre o nome 1M e tabela que descreve 2 meses; manter a coleção pelo ID e consultar metadados antes de análise temporal.','2026-08-18']]

dists = [
['DD000743','DP000713','BDC LULC Landsat Amazônia — STAC','https://data.inpe.br/bdc/stac/v1/collections/LCC_L8_30_16D_STK_Amazonia-TC-1','raster classificado / assets STAC','STAC API / HTTPS','cliente STAC | GIS | Python','sim','não','consulta por coleção/item/asset','verificar termos da coleção','sim','por item/asset','Classificação BDC da Amazônia derivada de série Landsat-8; consultar legenda e metadados do item.','2026-08-18'],
['DD000744','DP000714','BDC LULC Landsat Caatinga — STAC','https://data.inpe.br/bdc/stac/v1/collections/LCC_L8_30_16D_STK_Caatinga-1','raster classificado / assets STAC','STAC API / HTTPS','cliente STAC | GIS | Python','sim','não','consulta por coleção/item/asset','verificar termos da coleção','sim','por item/asset','Classificação BDC da Caatinga; consultar legenda, período e metadados do item.','2026-08-18'],
['DD000745','DP000715','BDC LULC Landsat Cerrado — STAC','https://data.inpe.br/bdc/stac/v1/collections/LCC_L8_30_16D_STK_Cerrado-1','raster classificado / assets STAC','STAC API / HTTPS','cliente STAC | GIS | Python','sim','não','consulta por coleção/item/asset','verificar termos da coleção','sim','por item/asset','Classificação BDC do Cerrado; distinta do TerraClass e de outras séries LULC.','2026-08-18'],
['DD000746','DP000716','BDC LULC Landsat Mata Atlântica — STAC','https://data.inpe.br/bdc/stac/v1/collections/LCC_L8_30_16D_STK_MataAtlantica-1','raster classificado / assets STAC','STAC API / HTTPS','cliente STAC | GIS | Python','sim','não','consulta por coleção/item/asset','verificar termos da coleção','sim','por item/asset','Classificação BDC da Mata Atlântica; consultar legenda e metadados da coleção.','2026-08-18'],
['DD000747','DP000717','BDC LULC Landsat Pampa — STAC','https://data.inpe.br/bdc/stac/v1/collections/LCC_L8_30_16D_STK_Pampa-1','raster classificado / assets STAC','STAC API / HTTPS','cliente STAC | GIS | Python','sim','não','consulta por coleção/item/asset','verificar termos da coleção','sim','por item/asset','Classificação BDC do Pampa; consultar legenda, treinamento e metadados.','2026-08-18'],
['DD000748','DP000718','BDC LULC Landsat Pantanal — STAC','https://data.inpe.br/bdc/stac/v1/collections/LCC_L8_30_16D_STK_Pantanal-1','raster classificado / assets STAC','STAC API / HTTPS','cliente STAC | GIS | Python','sim','não','consulta por coleção/item/asset','verificar termos da coleção','sim','por item/asset','Classificação BDC do Pantanal; sazonalidade e inundação devem ser consideradas.','2026-08-18'],
['DD000749','DP000719','BDC LULC Sentinel-2 Amazônia — STAC','https://data.inpe.br/bdc/stac/v1/collections/LCC_S2_10_16D_STK_Amazonia-1','raster classificado / assets STAC','STAC API / HTTPS','cliente STAC | GIS | Python','sim','não','consulta por coleção/item/asset','verificar termos da coleção','sim','por item/asset','Classificação BDC Sentinel-2 da Amazônia a 10 m; não equiparar automaticamente à série Landsat.','2026-08-18'],
['DD000750','DP000720','LANDSAT-MOZ — STAC/COG','https://data.inpe.br/bdc/stac/v1/collections/LANDSAT-MOZ_30_1M_STK-1','Cloud Optimized GeoTIFF / assets STAC','STAC API / HTTPS range requests','cliente STAC | GIS | Python','sim','não','consulta por coleção/item/asset','verificar termos da coleção','sim','por item/asset','Cubo Landsat multissensor histórico; usar metadados da coleção para resolver periodicidade e proveniência por período.','2026-08-18']]

for path, rows, idcol, expected_max in [(PROD, products, 'product_id', 'DP000712'), (DIST, dists, 'distribution_id', 'DD000742')]:
    with path.open('r', encoding='utf-8-sig', newline='') as f:
        reader = csv.DictReader(f)
        existing = list(reader)
        fields = reader.fieldnames
    ids = {r[idcol] for r in existing}
    if expected_max not in ids:
        raise SystemExit(f'Baseline guard failed for {path}: {expected_max} absent')
    incoming_ids = {r[0] for r in rows}
    if ids & incoming_ids:
        raise SystemExit(f'Duplicate incoming IDs in {path}: {sorted(ids & incoming_ids)}')
    if path == PROD:
        existing_urls = {r['product_page_url'] for r in existing if r.get('product_page_url')}
        dup_urls = existing_urls & {r[19] for r in rows}
        if dup_urls:
            raise SystemExit(f'Product URL already catalogued: {sorted(dup_urls)}')
    with path.open('a', encoding='utf-8', newline='') as f:
        w = csv.writer(f, lineterminator='\n')
        w.writerows(rows)

# Structural read-back before derived rebuild.
with PROD.open(encoding='utf-8-sig', newline='') as f:
    p = list(csv.DictReader(f))
with DIST.open(encoding='utf-8-sig', newline='') as f:
    d = list(csv.DictReader(f))
pids = [r['product_id'] for r in p]
dids = [r['distribution_id'] for r in d]
if len(pids) != len(set(pids)) or len(dids) != len(set(dids)):
    raise SystemExit('ID uniqueness failure')
if not set(r['product_id'] for r in d).issubset(set(pids)):
    raise SystemExit('Distribution FK failure')
for x in [f'DP{i:06d}' for i in range(713,721)]:
    if x not in pids: raise SystemExit(f'Missing {x}')
for x in [f'DD{i:06d}' for i in range(743,751)]:
    if x not in dids: raise SystemExit(f'Missing {x}')
print('OK append', len(products), len(dists), len(p), len(d))
