from pathlib import Path
import csv

ROOT = Path(__file__).resolve().parents[1]
TODAY = '2026-08-15'

def append_dicts(path, rows, id_field):
    with path.open(encoding='utf-8', newline='') as f:
        reader = csv.DictReader(f)
        fields = reader.fieldnames
        existing = list(reader)
    ids = {r[id_field] for r in existing}
    for row in rows:
        if row[id_field] in ids:
            raise SystemExit(f'duplicate {id_field}: {row[id_field]}')
        missing = set(fields) - set(row)
        extra = set(row) - set(fields)
        if missing or extra:
            raise SystemExit(f'{path.name}: missing={missing} extra={extra}')
        existing.append(row)
    with path.open('w', encoding='utf-8', newline='') as f:
        w = csv.DictWriter(f, fieldnames=fields, lineterminator='\n')
        w.writeheader(); w.writerows(existing)

resources = [
{
'resource_id':'DR0063','resource_name':'Informações Geocientíficas Experimentais — IBGE','acronym':'IGE IBGE','official_identity':'Linha institucional de Informações Geocientíficas Experimentais do IBGE','description':'Coleção institucional de estudos e produtos geocientíficos experimentais ainda em avaliação de metodologia, harmonização, cobertura ou qualidade, publicados para escrutínio e uso cauteloso.','homepage_url':'https://www.ibge.gov.br/geociencias/investigacoes-experimentais-geo/informacoes-geocientificas-experimentais.html','data_access_url':'https://www.ibge.gov.br/geociencias/investigacoes-experimentais-geo/informacoes-geocientificas-experimentais.html','research_areas':'Ciências Ambientais e Ecologia | Sensoriamento Remoto e Geoinformação | Planejamento Territorial e Políticas Públicas','keywords':'IBGE | estatísticas experimentais | geociências | indicadores ambientais | serviços ecossistêmicos','data_product_types':'estudos experimentais | indicadores | vetores | tabelas | publicações','data_formats':'varia conforme o produto; inclui SHP | XLSX | PDF | SIDRA','visualization_types':'mapas | tabelas | publicações; varia conforme produto','geographic_coverage':'Brasil; produtos-piloto podem cobrir localidades específicas','covers_brazil':'sim','spatial_resolution':'varia conforme produto','temporal_coverage':'varia conforme produto','temporal_resolution':'varia conforme produto','data_sources':'bases e pesquisas do IBGE | literatura científica | fontes oficiais complementares conforme estudo','free_download':'parcial','access_conditions':'consulta pública; downloads e tabelas conforme produto','programmatic_access':'desconhecido','access_protocols':'HTTP download | SIDRA conforme produto','authentication_required':'não','access_documentation_url':'https://www.ibge.gov.br/geociencias/investigacoes-experimentais-geo/informacoes-geocientificas-experimentais.html','license':'licença específica deve ser verificada em cada produto; não inferida da página agregadora','institutional_status':'público','owner_or_manager':'IBGE','academic_uses':'Testar e analisar novos indicadores, métodos e recortes ambientais e socioecológicos com explicitação do caráter experimental.','limitations':'Produtos experimentais não atingiram necessariamente maturidade completa de metodologia, harmonização ou cobertura; não generalizar além do escopo documentado.','academic_evidence_type':'documentação técnica oficial','academic_evidence_url':'https://www.ibge.gov.br/geociencias/investigacoes-experimentais-geo/informacoes-geocientificas-experimentais.html','academic_evidence_note':'A página oficial lista explicitamente os produtos em andamento e orienta uso cauteloso por estarem em teste e avaliação.','verification_url':'https://www.ibge.gov.br/geociencias/investigacoes-experimentais-geo/informacoes-geocientificas-experimentais.html','last_verified':TODAY},
{
'resource_id':'DR0064','resource_name':'Contas de Ecossistemas — IBGE','acronym':'Contas de Ecossistemas','official_identity':'Contas Econômicas Ambientais | Contas de Ecossistemas do IBGE','description':'Família de contas ambientais e estudos experimentais que integram informações ecológicas e econômicas segundo a estrutura de contabilidade do capital natural e recomendações do SEEA.','homepage_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/estatisticas-e-indicadores-ambientais/28920-contas-de-ecossistemas.html','data_access_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/estatisticas-e-indicadores-ambientais/28920-contas-de-ecossistemas.html','research_areas':'Ciências Ambientais e Ecologia | Recursos Hídricos e Oceanografia | Planejamento Territorial e Políticas Públicas','keywords':'contas de ecossistemas | capital natural | serviços ecossistêmicos | SEEA | biomas | água','data_product_types':'contas ambientais | indicadores | tabelas | publicações experimentais','data_formats':'XLSX | PDF | tabelas e downloads; varia conforme edição','visualization_types':'tabelas | gráficos | publicações','geographic_coverage':'Brasil e biomas brasileiros; recortes variam conforme conta','covers_brazil':'sim','spatial_resolution':'varia conforme conta e insumos','temporal_coverage':'varia conforme conta','temporal_resolution':'anos de referência ou períodos específicos','data_sources':'pesquisas do IBGE | ANA | SNIS | Sistema de Contas Nacionais | outras bases oficiais conforme conta','free_download':'sim','access_conditions':'consulta e downloads públicos conforme edição','programmatic_access':'desconhecido','access_protocols':'HTTP download | tabelas; varia conforme produto','authentication_required':'não','access_documentation_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/estatisticas-e-indicadores-ambientais/28920-contas-de-ecossistemas.html','license':'licença específica do dado não localizada nesta auditoria; observar termos do IBGE e da edição','institutional_status':'público','owner_or_manager':'IBGE','academic_uses':'Analisar capital natural, condição de ecossistemas, provisão de serviços e relações entre ambiente e economia em recortes nacionais e por bioma.','limitations':'As contas combinam bases, métodos e anos de referência distintos; resultados experimentais não devem ser tratados como observações primárias homogêneas.','academic_evidence_type':'documentação técnica oficial','academic_evidence_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/estatisticas-e-indicadores-ambientais/28920-contas-de-ecossistemas.html','academic_evidence_note':'A documentação oficial identifica a família de Contas de Ecossistemas e suas edições experimentais, com publicações e downloads.','verification_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/estatisticas-e-indicadores-ambientais/28920-contas-de-ecossistemas.html','last_verified':TODAY}
]

products = [
{'product_id':'DP000082','resource_id':'DR0063','product_name':'Proposta Metodológica para Identificação e Mapeamento de Áreas Verdes Urbanas no Brasil','product_acronym':'Áreas Verdes Urbanas','product_family':'Informações Geocientíficas Experimentais','product_kind':'dataset','product_description':'Estudo experimental do IBGE que propõe metodologia para identificar e mapear áreas verdes urbanas, com teste-piloto e arquivos vetoriais para Guarulhos (SP) e Palmas (TO).','research_areas':'Urban ecology | Remote sensing | Environmental planning | Ecosystem services','keywords':'áreas verdes urbanas | cobertura vegetal | ODS 11 | Guarulhos | Palmas | IBGE','geographic_coverage':'Guarulhos (SP) e Palmas (TO) no teste-piloto','covers_brazil':'sim','spatial_support':'polígonos vetoriais | áreas urbanizadas piloto','spatial_resolution':'conforme metodologia e arquivos shapefile do piloto','temporal_coverage':'edição publicada em 2025','temporal_resolution':'não se aplica','update_frequency':'experimental; sem periodicidade estabelecida','product_status':'experimental','version_or_collection':'2025 — teste-piloto','enumeration_scope':'complete','product_page_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/cobertura-e-uso-da-terra/44390-proposta-metodologica-para-identificacao-e-mapeamento-de-areas-verdes-urbanas-no-brasil.html','methodology_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/cobertura-e-uso-da-terra/44390-proposta-metodologica-para-identificacao-e-mapeamento-de-areas-verdes-urbanas-no-brasil.html','primary_or_derived':'derivado','limitations':'Produto experimental e piloto restrito a Guarulhos e Palmas; não extrapolar estatísticas, desempenho ou cobertura para todas as cidades brasileiras.','last_verified':TODAY},
{'product_id':'DP000083','resource_id':'DR0063','product_name':'Contribuição dos Polinizadores para as Produções Agrícola e Extrativista do Brasil — 1981–2023','product_acronym':'Contribuição dos Polinizadores','product_family':'Informações Geocientíficas Experimentais','product_kind':'indicator_family','product_description':'Estudo experimental que combina PAM, PEVS e taxas de dependência de polinização animal da literatura para estimar a contribuição dos polinizadores ao valor da produção agrícola e extrativista.','research_areas':'Ecosystem services | Agriculture | Biodiversity | Ecological economics','keywords':'polinização | serviços ecossistêmicos | PAM | PEVS | agricultura | extrativismo','geographic_coverage':'Brasil | Grandes Regiões | UFs | Municípios; Biomas para 2023','covers_brazil':'sim','spatial_support':'unidades territoriais estatísticas | culturas e produtos','spatial_resolution':'Brasil a município; bioma apenas para 2023 conforme publicação','temporal_coverage':'PAM 1975–2023; PEVS 1981–2023; indicador de contribuição 1996–2023','temporal_resolution':'anual','update_frequency':'experimental; periodicidade futura não estabelecida','product_status':'experimental','version_or_collection':'1981–2023; publicação 2025','enumeration_scope':'complete','product_page_url':'https://www.ibge.gov.br/estatisticas/economicas/contas-nacionais/43948-contribuicao-dos-polinizadores-para-as-producoes-agricola-e-extrativista-do-brasil.html','methodology_url':'https://www.ibge.gov.br/estatisticas/economicas/contas-nacionais/43948-contribuicao-dos-polinizadores-para-as-producoes-agricola-e-extrativista-do-brasil.html','primary_or_derived':'derivado','limitations':'Indicador depende das taxas de dependência de polinização atribuídas por produto com base na literatura; não mede diretamente abundância de polinizadores nem causalidade ecológica local.','last_verified':TODAY},
{'product_id':'DP000084','resource_id':'DR0064','product_name':'Contas de Ecossistemas — Produtos Florestais Não Madeireiros 2006–2016','product_acronym':'PFNM 2006–2016','product_family':'Contas de Ecossistemas','product_kind':'indicator_family','product_description':'Estatística experimental sobre evolução física e monetária de produtos florestais não madeireiros por bioma e valoração experimental do serviço ecossistêmico de provisão.','research_areas':'Ecosystem services | Forest economics | Ecological economics | Conservation','keywords':'produtos florestais não madeireiros | PFNM | biomas | provisão | valoração | PEVS | PAM','geographic_coverage':'Brasil por biomas brasileiros','covers_brazil':'sim','spatial_support':'bioma | produto florestal | estatísticas agregadas','spatial_resolution':'biomas brasileiros','temporal_coverage':'2006–2016','temporal_resolution':'anos de referência e índices no período conforme tabela','update_frequency':'experimental; edição específica','product_status':'experimental','version_or_collection':'2006–2016; publicado em 2021','enumeration_scope':'complete','product_page_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/estatisticas-e-indicadores-ambientais/28920-contas-de-ecossistemas.html?edicao=30514','methodology_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/estatisticas-e-indicadores-ambientais/28920-contas-de-ecossistemas.html?edicao=30514','primary_or_derived':'derivado','limitations':'Combina PEVS, PAM, Censo Agropecuário e Contas Nacionais; a valoração é experimental e não equivale a preço de mercado integral do ecossistema ou biodiversidade.','last_verified':TODAY},
{'product_id':'DP000085','resource_id':'DR0064','product_name':'Contas de Ecossistemas — Condição dos Corpos Hídricos 2010–2017','product_acronym':'Condição Hídrica 2010–2017','product_family':'Contas de Ecossistemas','product_kind':'indicator_family','product_description':'Estatísticas experimentais de condição dos corpos hídricos que integram captação de água, estados químico e físico e espécies aquáticas ameaçadas, com recorte por biomas.','research_areas':'Freshwater ecology | Hydrology | Ecosystem accounting | Conservation','keywords':'corpos hídricos | condição | captação | qualidade da água | espécies ameaçadas | biomas','geographic_coverage':'Brasil por biomas; balanço de microbacias conforme estudo','covers_brazil':'sim','spatial_support':'bioma | microbacia | indicadores agregados','spatial_resolution':'varia por indicador e base de origem','temporal_coverage':'2010–2017; balanço hídrico com ano de referência 2016','temporal_resolution':'anos selecionados conforme indicador','update_frequency':'experimental; edição específica','product_status':'experimental','version_or_collection':'2010–2017; publicado em 2021','enumeration_scope':'complete','product_page_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/estatisticas-e-indicadores-ambientais/28920-contas-de-ecossistemas.html?edicao=30518','methodology_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/estatisticas-e-indicadores-ambientais/28920-contas-de-ecossistemas.html?edicao=30518','primary_or_derived':'derivado','limitations':'Integra bases abióticas, bióticas e de captação com escalas e anos distintos; condição ecológica não deve ser reduzida a um único indicador nem interpretada causalmente sem análise adicional.','last_verified':TODAY},
{'product_id':'DP000086','resource_id':'DR0064','product_name':'Contas de Ecossistemas — Valoração do Serviço de Provisão de Água Azul 2013–2017','product_acronym':'Água Azul 2013–2017','product_family':'Contas de Ecossistemas','product_kind':'indicator_family','product_description':'Estudo experimental que estima o valor do serviço ecossistêmico de provisão de água azul utilizado pela atividade de captação, tratamento e distribuição de água por abordagem de valor residual.','research_areas':'Ecosystem services | Water economics | Ecological economics | Environmental accounting','keywords':'água azul | provisão | valoração | valor residual | saneamento | capital natural','geographic_coverage':'Brasil e Grandes Regiões conforme bases integradas','covers_brazil':'sim','spatial_support':'atividade econômica | agregações territoriais e temporais do estudo','spatial_resolution':'agregada; conforme ANA, SNIS e Contas Nacionais','temporal_coverage':'2013–2017','temporal_resolution':'anual conforme bases integradas','update_frequency':'experimental; edição específica','product_status':'experimental','version_or_collection':'2013–2017; publicado e corrigido em 2021','enumeration_scope':'complete','product_page_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/estatisticas-e-indicadores-ambientais/28920-contas-de-ecossistemas.html','methodology_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/estatisticas-e-indicadores-ambientais/28920-contas-de-ecossistemas.html','primary_or_derived':'derivado','limitations':'Valoração experimental por valor residual para a atividade de captação, tratamento e distribuição de água; não representa valor econômico total da água ou dos ecossistemas. A publicação teve correção de unidade de medida em 04/05/2021.','last_verified':TODAY}
]

dists = [
{'distribution_id':'DD000098','product_id':'DP000082','distribution_name':'Áreas Verdes Urbanas — arquivos shapefile do teste-piloto','access_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/cobertura-e-uso-da-terra/44390-proposta-metodologica-para-identificacao-e-mapeamento-de-areas-verdes-urbanas-no-brasil.html','format':'Shapefile (ZIP)','access_protocol':'HTTP download','access_tool':'navegador web','free_download':'sim','authentication_required':'não','access_conditions':'download público na página do produto','license':'licença específica do arquivo não localizada nesta auditoria; observar termos do IBGE','provider_attribution_required':'sim','subset_support':'por cidade piloto conforme arquivos publicados','notes':'Arquivos correspondem ao teste-piloto de Guarulhos e Palmas; não representam uma camada nacional de áreas verdes urbanas.','last_verified':TODAY},
{'distribution_id':'DD000099','product_id':'DP000083','distribution_name':'Contribuição dos Polinizadores — tabelas SIDRA e publicação','access_url':'https://www.ibge.gov.br/estatisticas/economicas/contas-nacionais/43948-contribuicao-dos-polinizadores-para-as-producoes-agricola-e-extrativista-do-brasil.html','format':'SIDRA | PDF','access_protocol':'HTTPS web | SIDRA','access_tool':'navegador web | SIDRA','free_download':'sim','authentication_required':'não','access_conditions':'consulta pública; desagregações conforme tabela publicada','license':'licença específica da tabela não localizada nesta auditoria; observar termos do IBGE','provider_attribution_required':'sim','subset_support':'Brasil | Grandes Regiões | UFs | Municípios; culturas/produtos; Biomas em 2023','notes':'O produto informa valores do indicador no SIDRA; preservar série, recorte territorial e tipo de produto/cultura usados.','last_verified':TODAY},
{'distribution_id':'DD000100','product_id':'DP000084','distribution_name':'PFNM 2006–2016 — publicação e downloads','access_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/estatisticas-e-indicadores-ambientais/28920-contas-de-ecossistemas.html?edicao=30514','format':'PDF | arquivos de download conforme edição','access_protocol':'HTTP download','access_tool':'navegador web','free_download':'sim','authentication_required':'não','access_conditions':'downloads públicos da edição','license':'licença específica dos dados não localizada nesta auditoria; observar termos do IBGE','provider_attribution_required':'sim','subset_support':'por bioma e produto conforme tabelas da publicação','notes':'Distinguir produção física/monetária dos índices e da valoração experimental do serviço de provisão.','last_verified':TODAY},
{'distribution_id':'DD000101','product_id':'DP000085','distribution_name':'Condição dos Corpos Hídricos 2010–2017 — publicação e downloads','access_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/estatisticas-e-indicadores-ambientais/28920-contas-de-ecossistemas.html?edicao=30518','format':'PDF | arquivos de download conforme edição','access_protocol':'HTTP download','access_tool':'navegador web','free_download':'sim','authentication_required':'não','access_conditions':'downloads públicos da edição','license':'licença específica dos dados não localizada nesta auditoria; observar termos do IBGE','provider_attribution_required':'sim','subset_support':'por bioma/indicador conforme publicação','notes':'Indicadores têm fontes e anos de referência distintos; registrar indicador, recorte e ano em qualquer extração analítica.','last_verified':TODAY},
{'distribution_id':'DD000102','product_id':'DP000086','distribution_name':'Valoração da Provisão de Água Azul 2013–2017 — publicação corrigida','access_url':'https://www.ibge.gov.br/geociencias/informacoes-ambientais/estatisticas-e-indicadores-ambientais/28920-contas-de-ecossistemas.html','format':'PDF | arquivos de download conforme edição','access_protocol':'HTTP download','access_tool':'navegador web','free_download':'sim','authentication_required':'não','access_conditions':'consulta e download públicos; usar versão substituída após correção de 04/05/2021','license':'licença específica dos dados não localizada nesta auditoria; observar termos do IBGE','provider_attribution_required':'sim','subset_support':'conforme tabelas e agregações do estudo','notes':'Usar a publicação corrigida: o IBGE substituiu o arquivo após corrigir dois erros de digitação relativos à unidade de medida na página 26.','last_verified':TODAY}
]

append_dicts(ROOT/'data/data_resources.csv', resources, 'resource_id')
append_dicts(ROOT/'data/data_products.csv', products, 'product_id')
append_dicts(ROOT/'data/product_distributions.csv', dists, 'distribution_id')
print('materialized', len(resources), len(products), len(dists))
