#!/usr/bin/env python3
import csv
import json
from pathlib import Path

TODAY = "2026-08-15"
ROOT = Path(__file__).resolve().parents[1]


def append_rows(path, rows, id_field):
    path = ROOT / path
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        fields = reader.fieldnames
        existing = {r[id_field] for r in reader}
    wanted = [r[id_field] for r in rows]
    dup = sorted(set(wanted) & existing)
    if dup:
        raise SystemExit(f"Refusing duplicate {id_field}: {dup}")
    if len(wanted) != len(set(wanted)):
        raise SystemExit(f"Duplicate IDs inside batch for {id_field}")
    with path.open("a", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields, lineterminator="\n")
        for row in rows:
            missing = set(fields) - set(row)
            extra = set(row) - set(fields)
            if missing or extra:
                raise SystemExit(f"Schema mismatch {path}: missing={missing}, extra={extra}")
            writer.writerow(row)

sources = [
{
"resource_id":"DR0069","resource_name":"Malhas Territoriais — IBGE","acronym":"Malhas IBGE","official_identity":"Tema institucional de malhas territoriais da Diretoria de Geociências do IBGE","description":"Representações cartográficas oficiais da estrutura territorial brasileira, incluindo a Malha Municipal Digital e outras malhas territoriais de referência.","homepage_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/malhas-territoriais.html","data_access_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/malhas-territoriais/15774-malhas.html","research_areas":"Sensoriamento Remoto e Geoinformação | Planejamento Territorial e Políticas Públicas","keywords":"malha municipal | limites | municípios | unidades da federação | SIRGAS 2000 | IBGE","data_product_types":"malhas vetoriais | documentação técnica","data_formats":"SHP | PDF | formatos adicionais conforme produto","visualization_types":"mapas | arquivos vetoriais","geographic_coverage":"Brasil","covers_brazil":"sim","spatial_resolution":"unidades territoriais político-administrativas; precisão e escala dependem do produto","temporal_coverage":"edições anuais e censitárias conforme produto","temporal_resolution":"por edição","data_sources":"Base Territorial do IBGE | legislação e atualizações territoriais estaduais | geotecnologias","free_download":"sim","access_conditions":"downloads públicos","programmatic_access":"desconhecido","access_protocols":"HTTP download","authentication_required":"não","access_documentation_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/malhas-territoriais/15774-malhas.html","license":"licença específica deve ser verificada no produto; não inferida nesta auditoria","institutional_status":"público","owner_or_manager":"IBGE — Diretoria de Geociências","academic_uses":"Geoprocessamento, integração de estatísticas, análise territorial, planejamento e delimitação de unidades administrativas.","limitations":"As malhas representam a estrutura territorial de uma edição; alterações legais, judiciais e cartográficas entre anos exigem registrar a versão utilizada.","academic_evidence_type":"documentação técnica oficial","academic_evidence_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/malhas-territoriais/15774-malhas.html","academic_evidence_note":"A página oficial descreve a Malha Municipal Digital 2025, unidades territoriais, SIRGAS 2000, formato Shapefile e documentação técnica/legal.","verification_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/malhas-territoriais/15774-malhas.html","last_verified":TODAY
},
{
"resource_id":"DR0070","resource_name":"Estrutura Territorial — IBGE","acronym":"Estrutura Territorial IBGE","official_identity":"Tema institucional do IBGE sobre a estrutura territorial legal brasileira e sua divisão político-administrativa","description":"Conjunto institucional de informações oficiais sobre estrutura territorial, áreas e recortes político-administrativos brasileiros ao longo do tempo.","homepage_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/estrutura-territorial.html","data_access_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/estrutura-territorial/2225-np-areas-dos-municipios/15761-areas-dos-municipios.html","research_areas":"Planejamento Territorial e Políticas Públicas | Sensoriamento Remoto e Geoinformação","keywords":"estrutura territorial | áreas territoriais | limites | municípios | IBGE","data_product_types":"tabelas territoriais | cadastros | documentação legal | mapas","data_formats":"XLS | ODS | PDF | varia conforme produto","visualization_types":"tabelas | mapas","geographic_coverage":"Brasil","covers_brazil":"sim","spatial_resolution":"unidades político-administrativas e outros recortes conforme produto","temporal_coverage":"edições históricas e atuais conforme produto","temporal_resolution":"por edição; vários produtos anuais","data_sources":"Base Territorial do IBGE | legislação | limites oficiais | geotecnologias","free_download":"sim","access_conditions":"consulta e downloads públicos conforme produto","programmatic_access":"desconhecido","access_protocols":"HTTP download","authentication_required":"não","access_documentation_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/estrutura-territorial/2225-np-areas-dos-municipios/15761-areas-dos-municipios.html","license":"licença específica deve ser verificada por produto; não inferida nesta auditoria","institutional_status":"público","owner_or_manager":"IBGE — Diretoria de Geociências","academic_uses":"Análises territoriais e socioambientais que dependem de áreas oficiais, limites, códigos e estrutura político-administrativa.","limitations":"Mudanças legais, judiciais e melhorias cartográficas podem alterar áreas e recortes entre edições; não assumir estabilidade temporal dos limites.","academic_evidence_type":"documentação técnica oficial","academic_evidence_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/estrutura-territorial/2225-np-areas-dos-municipios/15761-areas-dos-municipios.html","academic_evidence_note":"A documentação oficial das Áreas Territoriais explicita revisão anual, data de referência, legislação, derivação da Malha Municipal Digital e downloads tabulares.","verification_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/estrutura-territorial/2225-np-areas-dos-municipios/15761-areas-dos-municipios.html","last_verified":TODAY
},
{
"resource_id":"DR0071","resource_name":"Divisão Regional — IBGE","acronym":"Divisão Regional IBGE","official_identity":"Tema institucional de divisões, recortes e referenciais territoriais da Diretoria de Geociências do IBGE","description":"Família de produtos que organiza recortes territoriais legais e institucionais para análise geográfica, planejamento e integração espacial de estatísticas oficiais.","homepage_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/divisao-regional.html","data_access_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/divisao-regional.html","research_areas":"Planejamento Territorial e Políticas Públicas | Geografia | Sensoriamento Remoto e Geoinformação","keywords":"divisão regional | recortes territoriais | DTB | quadro geográfico | regiões metropolitanas | IBGE","data_product_types":"cadastros territoriais | recortes geográficos | geosserviços | tabelas | mapas","data_formats":"SHP | KML | CSV | GeoJSON | XLS | ODS | PDF | varia conforme produto","visualization_types":"mapas | tabelas | Plataforma Geográfica Interativa","geographic_coverage":"Brasil","covers_brazil":"sim","spatial_resolution":"recortes nacionais, regionais, municipais e intramunicipais conforme produto","temporal_coverage":"múltiplas versões históricas e correntes","temporal_resolution":"por versão/edição","data_sources":"recortes legais | recortes institucionais do IBGE | registros administrativos territoriais","free_download":"sim","access_conditions":"consulta, geosserviços e downloads públicos conforme produto","programmatic_access":"parcial","access_protocols":"HTTP download | WMS e outros serviços conforme recorte","authentication_required":"não","access_documentation_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/divisao-regional.html","license":"licença específica deve ser verificada por produto e distribuição","institutional_status":"público","owner_or_manager":"IBGE — Diretoria de Geociências","academic_uses":"Regionalização, integração de estatísticas, estudos socioecológicos, planejamento territorial e comparação entre recortes geográficos.","limitations":"Recortes têm fundamentos legais ou metodológicos diferentes e versões próprias; pertencimento a uma mesma plataforma não implica comparabilidade sem verificar definição e vigência.","academic_evidence_type":"documentação técnica oficial","academic_evidence_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/divisao-regional.html","academic_evidence_note":"A página oficial caracteriza a Divisão Regional e lista DTB, Quadro Geográfico de Referência e demais recortes territoriais como produtos distintos.","verification_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/divisao-regional.html","last_verified":TODAY
}
]

products = [
{
"product_id":"DP000098","resource_id":"DR0069","product_name":"Malha Municipal Digital — 2025","product_acronym":"MMD 2025","product_family":"Malhas Territoriais","product_kind":"dataset","product_description":"Malha vetorial oficial da Divisão Político-Administrativa Brasileira em 2025, com municípios e demais unidades territoriais de referência, em SIRGAS 2000.","research_areas":"GIS | Cartography | Territorial analysis | Population geography","keywords":"malha municipal | 2025 | municípios | SIRGAS 2000 | limites | IBGE","geographic_coverage":"Brasil; arquivos nacionais e por Unidade da Federação conforme unidade territorial","covers_brazil":"sim","spatial_support":"polígonos vetoriais de unidades territoriais","spatial_resolution":"unidades político-administrativas; 5573 geocódigos na MMD 2025, dos quais 5569 são municípios","temporal_coverage":"estrutura político-administrativa vigente na edição 2025","temporal_resolution":"edição anual","update_frequency":"anual","product_status":"ativo","version_or_collection":"2025","enumeration_scope":"complete","product_page_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/malhas-territoriais/15774-malhas.html","methodology_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/malhas-territoriais/15774-malhas.html","primary_or_derived":"derivado","limitations":"Os 5573 geocódigos não equivalem a 5573 municípios: incluem 5569 municípios, Distrito Federal, Distrito Estadual de Fernando de Noronha e duas Áreas Estaduais Operacionais. Registrar a edição para análises temporais.","last_verified":TODAY
},
{
"product_id":"DP000099","resource_id":"DR0070","product_name":"Áreas Territoriais — 2025","product_acronym":"Áreas Territoriais 2025","product_family":"Áreas Territoriais","product_kind":"dataset_series","product_description":"Valores oficiais reprocessados das áreas territoriais dos municípios, Distrito Federal, Fernando de Noronha e agregações superiores, derivados da Malha Municipal Digital 2025.","research_areas":"Territorial analysis | GIS | Population geography | Environmental statistics","keywords":"área territorial | municípios | km2 | 2025 | limites | IBGE","geographic_coverage":"Brasil | Grandes Regiões | Unidades da Federação | Municípios | Regiões Geográficas Imediatas e Intermediárias","covers_brazil":"sim","spatial_support":"unidades territoriais tabuladas","spatial_resolution":"município e agregações territoriais oficiais","temporal_coverage":"quadro territorial vigente em 30/04/2025; valores publicados em março de 2026","temporal_resolution":"edição anual","update_frequency":"anual","product_status":"ativo","version_or_collection":"2025; Portaria IBGE nº 441 de 13/03/2026","enumeration_scope":"complete","product_page_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/estrutura-territorial/2225-np-areas-dos-municipios/15761-areas-dos-municipios.html","methodology_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/estrutura-territorial/2225-np-areas-dos-municipios/15761-areas-dos-municipios.html","primary_or_derived":"derivado","limitations":"Valores dependem da edição da Malha Municipal Digital, alterações legais/judiciais e melhorias cartográficas. Pequenas diferenças em somatórios podem ocorrer por arredondamento; não misturar edições sem registrar a referência territorial.","last_verified":TODAY
},
{
"product_id":"DP000100","resource_id":"DR0071","product_name":"Divisão Territorial Brasileira — 2025","product_acronym":"DTB 2025","product_family":"Divisão Territorial Brasileira","product_kind":"dataset_series","product_description":"Relação oficial anual de municípios, distritos e subdistritos, com geocódigos, hierarquia administrativa e alterações em relação à edição anterior.","research_areas":"Territorial analysis | Population geography | Public administration | GIS","keywords":"DTB | municípios | distritos | subdistritos | geocódigos | 2025 | IBGE","geographic_coverage":"Brasil","covers_brazil":"sim","spatial_support":"unidades administrativas tabuladas e códigos territoriais","spatial_resolution":"município | distrito | subdistrito; inclui hierarquia regional associada nas tabelas","temporal_coverage":"edição 2025; alterações registradas em relação a 2024","temporal_resolution":"edição anual","update_frequency":"anual","product_status":"ativo","version_or_collection":"2025","enumeration_scope":"complete","product_page_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/divisao-regional/23701-divisao-territorial-brasileira.html","methodology_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/divisao-regional/23701-divisao-territorial-brasileira.html","primary_or_derived":"derivado","limitations":"A DTB é cadastro/hierarquia territorial, não uma malha geométrica completa. Distritos e subdistritos dependem de representação cartográfica e informação encaminhada ao IBGE; usar a edição correspondente ao período analisado.","last_verified":TODAY
},
{
"product_id":"DP000101","resource_id":"DR0071","product_name":"Quadro Geográfico de Referência para Produção, Análise e Disseminação de Estatísticas — versão 2025","product_acronym":"QGR 2025","product_family":"Quadro Geográfico de Referência","product_kind":"catalog","product_description":"Referência nacional que organiza recortes territoriais legais e institucionais para relacionar e integrar espacialmente estatísticas dos censos e demais pesquisas do IBGE.","research_areas":"Territorial analysis | Spatial statistics | GIS | Public policy","keywords":"quadro geográfico | recortes territoriais | estatísticas | 2025 | SHP | WMS | IBGE","geographic_coverage":"Brasil; múltiplos recortes legais e institucionais","covers_brazil":"sim","spatial_support":"recortes territoriais em geometrias e listas de unidades; varia por recorte","spatial_resolution":"varia por recorte, do nacional a unidades municipais e intramunicipais","temporal_coverage":"múltiplas versões por recorte; versão 2025 disponível para numerosos recortes","temporal_resolution":"por versão do recorte","update_frequency":"variável por recorte","product_status":"ativo","version_or_collection":"2025 e versões históricas preservadas por recorte","enumeration_scope":"external_index","product_page_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/divisao-regional/24233-quadro-geografico-de-referencia-para-producao-analise-e-disseminacao-de-estatisticas.html","methodology_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/divisao-regional/24233-quadro-geografico-de-referencia-para-producao-analise-e-disseminacao-de-estatisticas.html","primary_or_derived":"agregador","limitations":"O QGR é um quadro de referência composto por recortes com fundamentos legais ou institucionais distintos, não um único dataset observacional. Versão, definição e vigência devem ser preservadas em cada recorte usado.","last_verified":TODAY
},
{
"product_id":"DP000102","resource_id":"DR0071","product_name":"Recortes Metropolitanos e Aglomerações Urbanas — 2025","product_acronym":"Recortes Metropolitanos 2025","product_family":"Recortes Metropolitanos e Aglomerações Urbanas","product_kind":"dataset_series","product_description":"Composição e recortes territoriais de Regiões Metropolitanas, RIDEs, Aglomerações Urbanas e categorias metropolitanas, com tabelas e geosserviços da edição 2025.","research_areas":"Urban studies | Territorial planning | Population geography | GIS","keywords":"regiões metropolitanas | RIDE | aglomerações urbanas | 2025 | municípios | IBGE","geographic_coverage":"Brasil; recortes metropolitanos e unidades relacionadas conforme legislação vigente","covers_brazil":"sim","spatial_support":"listas/agregados de municípios | recortes vetoriais em geosserviços","spatial_resolution":"municípios e agregados metropolitanos","temporal_coverage":"edição 2025","temporal_resolution":"edição anual","update_frequency":"anual","product_status":"ativo","version_or_collection":"2025","enumeration_scope":"complete","product_page_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/estrutura-territorial/18354-recortes-metropolitanos-e-aglomeracoes-urbanas.html","methodology_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/estrutura-territorial/18354-recortes-metropolitanos-e-aglomeracoes-urbanas.html","primary_or_derived":"derivado","limitations":"Recortes refletem instrumentos legais e classificações territoriais vigentes; composição pode mudar entre edições. Categoria metropolitana, aglomeração urbana e RIDE não são conceitos intercambiáveis.","last_verified":TODAY
},
{
"product_id":"DP000103","resource_id":"DR0063","product_name":"Proposta Metodológica para Classificação dos Espaços do Rural, do Urbano e da Natureza no Brasil — 2023","product_acronym":"Rural-Urbano-Natureza 2023","product_family":"Classificação Rural e Urbana","product_kind":"indicator_family","product_description":"Proposta geocientífica experimental que classifica áreas de ponderação brasileiras em 16 tipos distribuídos nas dimensões urbana, rural e natureza, integrando atributos morfológicos, funcionais, produtivos e ambientais.","research_areas":"Human geography | Land use | Socioecological systems | Territorial analysis","keywords":"rural | urbano | natureza | continuum | áreas de ponderação | fuzzy | tipologia | experimental","geographic_coverage":"Brasil","covers_brazil":"sim","spatial_support":"áreas de ponderação e unidades derivadas da análise","spatial_resolution":"intramunicipal por áreas de ponderação; resultados nacionais","temporal_coverage":"insumos com diferentes anos de referência; publicação experimental 2023","temporal_resolution":"estudo metodológico/edição","update_frequency":"experimental; sem frequência estável declarada","product_status":"experimental","version_or_collection":"2023 — proposta metodológica experimental","enumeration_scope":"complete","product_page_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/tipologias-do-territorio/15790-classificacao-rural-e-urbana.html","methodology_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/tipologias-do-territorio/15790-classificacao-rural-e-urbana.html","primary_or_derived":"derivado","limitations":"Produto explicitamente experimental; os 16 tipos são uma proposta metodológica e não uma divisão legal do território. Insumos têm anos e significados distintos, portanto a tipologia não deve ser tratada como observação direta de uma única variável.","last_verified":TODAY
}
]

dists = [
{
"distribution_id":"DD000114","product_id":"DP000098","distribution_name":"Malha Municipal Digital 2025 — downloads vetoriais","access_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/malhas-territoriais/15774-malhas.html","format":"Shapefile (SHP)","access_protocol":"HTTP download","access_tool":"navegador web | software SIG","free_download":"sim","authentication_required":"não","access_conditions":"arquivos nacionais e por UF/unidade territorial conforme página oficial","license":"licença específica do arquivo não localizada nesta auditoria","provider_attribution_required":"sim","subset_support":"por UF e por unidade territorial; também arquivos nacionais","notes":"SIRGAS 2000, coordenadas geográficas, UTF-8. Não confundir 5573 geocódigos com número de municípios.","last_verified":TODAY
},
{
"distribution_id":"DD000115","product_id":"DP000099","distribution_name":"Áreas Territoriais 2025 — tabelas oficiais","access_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/estrutura-territorial/2225-np-areas-dos-municipios/15761-areas-dos-municipios.html","format":"XLS | ODS","access_protocol":"HTTP download","access_tool":"navegador web | planilha","free_download":"sim","authentication_required":"não","access_conditions":"consulta e download públicos","license":"licença específica das tabelas não localizada nesta auditoria","provider_attribution_required":"sim","subset_support":"por nível geográfico nas planilhas e consulta web","notes":"Valores referem-se ao quadro territorial vigente em 30/04/2025 e derivam da Malha Municipal Digital 2025; pequenas diferenças de soma podem ocorrer por arredondamento.","last_verified":TODAY
},
{
"distribution_id":"DD000116","product_id":"DP000100","distribution_name":"DTB 2025 — tabelas da Divisão Territorial Brasileira","access_url":"https://geoftp.ibge.gov.br/organizacao_do_territorio/estrutura_territorial/divisao_territorial/2025/","format":"ZIP contendo XLS | ODS","access_protocol":"HTTP download","access_tool":"navegador web | planilha","free_download":"sim","authentication_required":"não","access_conditions":"arquivo público DTB_2025.zip e página oficial do produto","license":"licença específica das tabelas não localizada nesta auditoria","provider_attribution_required":"sim","subset_support":"tabelas separadas de municípios, distritos, subdistritos e alterações","notes":"Inclui geocódigos e hierarquia administrativa; não é substituto da geometria das malhas territoriais.","last_verified":TODAY
},
{
"distribution_id":"DD000117","product_id":"DP000101","distribution_name":"Quadro Geográfico de Referência — recortes e geosserviços","access_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/divisao-regional/24233-quadro-geografico-de-referencia-para-producao-analise-e-disseminacao-de-estatisticas.html","format":"SHP | KML | PNG | CSV | GeoJSON | WMS | SLD | metadados; disponibilidade varia por recorte","access_protocol":"HTTP download | WMS | plataforma web","access_tool":"Plataforma Geográfica Interativa | navegador web | SIG","free_download":"sim","authentication_required":"não","access_conditions":"acesso por recorte e versão","license":"licença específica deve ser verificada no recorte/distribuição selecionado","provider_attribution_required":"sim","subset_support":"por recorte territorial e versão","notes":"O portal é um índice de recortes territoriais; formatos e versões disponíveis variam entre recortes.","last_verified":TODAY
},
{
"distribution_id":"DD000118","product_id":"DP000102","distribution_name":"Recortes Metropolitanos 2025 — tabelas e geosserviços","access_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/estrutura-territorial/18354-recortes-metropolitanos-e-aglomeracoes-urbanas.html","format":"XLS | XLSX | ODS | geosserviços conforme recorte","access_protocol":"HTTP download | geosserviço","access_tool":"navegador web | SIG","free_download":"sim","authentication_required":"não","access_conditions":"downloads e geosserviços públicos","license":"licença específica dos arquivos não localizada nesta auditoria","provider_attribution_required":"sim","subset_support":"por tipo de recorte e composição municipal","notes":"Preservar o tipo jurídico/territorial e a edição; composição de RMs, RIDEs e aglomerações pode mudar.","last_verified":TODAY
},
{
"distribution_id":"DD000119","product_id":"DP000103","distribution_name":"Classificação Rural-Urbano-Natureza 2023 — publicação, tabelas e mapas","access_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/tipologias-do-territorio/15790-classificacao-rural-e-urbana.html","format":"XLSX | ODS | PDF","access_protocol":"HTTP download","access_tool":"navegador web | planilha | leitor PDF","free_download":"sim","authentication_required":"não","access_conditions":"publicação, tabelas e mapas públicos","license":"licença específica dos arquivos não localizada nesta auditoria","provider_attribution_required":"sim","subset_support":"tabelas temáticas e resultados por áreas de ponderação","notes":"Produto experimental; inclui tabelas de variáveis componentes, medidas fuzzy e tipologia final. Não usar como classificação legal rural/urbana.","last_verified":TODAY
}
]

append_rows("data/data_resources.csv", sources, "resource_id")
append_rows("data/data_products.csv", products, "product_id")
append_rows("data/product_distributions.csv", dists, "distribution_id")

p = ROOT / "data/brazil_scope_priorities.json"
registry = json.loads(p.read_text(encoding="utf-8"))
p0 = next(t for t in registry["tiers"] if t["priority_tier"] == "P0")
for rid in ["DR0069", "DR0070", "DR0071"]:
    if rid not in p0["resource_ids"]:
        p0["resource_ids"].append(rid)
registry["reviewed_at"] = TODAY
p.write_text(json.dumps(registry, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

print(f"Materialized {len(sources)} sources, {len(products)} products, {len(dists)} distributions")
