#!/usr/bin/env python3
import csv
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
P=ROOT/'data'/'data_products.csv'
D=ROOT/'data'/'product_distributions.csv'
DATE='2026-08-18'

products=[
['DP000687','DR0123','CBERS-4/MUX — Level-2-DN','CB4 MUX L2-DN','BIG — CBERS-4/MUX','dataset_series','Cenas CBERS-4/MUX Level-2 em número digital com correções radiométrica e geométrica de sistema nas quatro bandas visível/NIR.','Remote sensing | Land use and land cover | Environmental monitoring','CBERS-4 | MUX | Level-2 | digital number | multispectral','Brasil e demais áreas imageadas/disponíveis na coleção','sim','cena raster | coleção STAC','20 m','2014-12-08–2026-07-05 na coleção STAC verificada','por aquisição','conforme aquisição','ativo','CB4-MUX-L2-DN-1 v1','complete','https://data.inpe.br/bdc/stac/v1/collections/CB4-MUX-L2-DN-1','https://data.inpe.br/dados/cbers-4/','primário','L2-DN não equivale a reflectância de superfície nem a ortorretificação Level-4; valores em DN exigem processamento apropriado para análises radiométricas quantitativas.',DATE],
['DP000688','DR0123','CBERS-4/MUX — Level-4-DN ortorretificado','CB4 MUX L4-DN','BIG — CBERS-4/MUX','dataset_series','Cenas CBERS-4/MUX Level-4 em número digital e ortorretificadas, com quatro bandas multiespectrais visível/NIR.','Remote sensing | Land use and land cover | Environmental monitoring','CBERS-4 | MUX | Level-4 | orthorectified | digital number','Brasil e demais áreas imageadas/disponíveis na coleção','sim','cena raster ortorretificada | coleção STAC','20 m','2014-12-09–2026-07-05 na coleção STAC verificada','por aquisição','conforme aquisição','ativo','CB4-MUX-L4-DN-1 v1','complete','https://data.inpe.br/bdc/stac/v1/collections/CB4-MUX-L4-DN-1','https://data.inpe.br/dados/cbers-4/','derivado','Ortorretificação melhora a geometria mas o produto permanece em DN; não interpretar como reflectância de superfície.',DATE],
['DP000689','DR0123','CBERS-4/MUX — Level-4-SR em COG','CB4 MUX L4-SR','BIG — CBERS-4/MUX','dataset_series','Cenas CBERS-4/MUX Level-4 em reflectância de superfície, ortorretificadas e distribuídas em Cloud Optimized GeoTIFF com CMASK.','Remote sensing | Land use and land cover | Vegetation dynamics | Environmental monitoring','CBERS-4 | MUX | Level-4 | surface reflectance | COG | CMASK','Brasil e parte da América do Sul conforme coleção','sim','cena raster COG | coleção STAC','20 m','2016-01-01–2026-05-31 na coleção STAC verificada','por aquisição','novas cenas documentadas mensalmente','ativo','CB4-MUX-L4-SR-1 v1','complete','https://data.inpe.br/bdc/stac/v1/collections/CB4-MUX-L4-SR-1','https://data.inpe.br/dados/cbers-4/','derivado','Reflectância de superfície é produto processado e deve ser usada com CMASK e metadados de aquisição; não somar com L2/L4-DN como observações independentes.',DATE],
['DP000690','DR0123','CBERS-4/MUX — cubo Level-4-SR LCF de 2 meses','CB4 MUX 2M','Brazil Data Cube — cubos CBERS-4/MUX','dataset_series','Cubo de observação da Terra sobre o Brasil derivado de reflectância de superfície CBERS-4/MUX, composto em janelas de dois meses pelo critério Least Cloud Cover First e distribuído em COG.','Remote sensing | Vegetation dynamics | Land use and land cover | Environmental monitoring','CBERS-4 | MUX | data cube | surface reflectance | LCF | 2 months | NDVI | EVI','Brasil','sim','célula raster | cubo multidimensional','20 m','2016-01-01–2026-04-30 na coleção STAC verificada','2 meses','conforme atualização dos insumos','ativo','CBERS4-MUX-2M-1 v1 / BDC_MD_V2','complete','https://data.inpe.br/bdc/stac/v1/collections/CBERS4-MUX-2M-1','https://data.inpe.br/dados/cbers-4/','derivado','LCF seleciona pixels dentro de uma janela temporal e não representa aquisição sinótica única; NDVI/EVI, ClearOB, TotalOB e Provenance são derivados/auxiliares e devem ser interpretados com a composição.',DATE],
['DP000691','DR0123','CBERS-4/WFI — Level-2-DN','CB4 WFI L2-DN','BIG — CBERS-4/WFI','dataset_series','Cenas CBERS-4/WFI Level-2 em número digital com correções radiométrica e geométrica de sistema nas quatro bandas visível/NIR.','Remote sensing | Land use and land cover | Environmental monitoring','CBERS-4 | WFI | Level-2 | digital number | wide field','Brasil e demais áreas imageadas/disponíveis na coleção','sim','cena raster | coleção STAC','64 m','2014-12-14–2026-07-05 na coleção STAC verificada','por aquisição','conforme aquisição','ativo','CB4-WFI-L2-DN-1 v1','complete','https://data.inpe.br/bdc/stac/v1/collections/CB4-WFI-L2-DN-1','https://data.inpe.br/dados/cbers-4/','primário','L2-DN não é reflectância de superfície nem produto ortorretificado final; cobertura ampla não garante observação válida livre de nuvens em cada passagem.',DATE],
['DP000692','DR0123','CBERS-4/WFI — Level-4-DN ortorretificado','CB4 WFI L4-DN','BIG — CBERS-4/WFI','dataset_series','Cenas CBERS-4/WFI Level-4 em número digital e ortorretificadas, mantendo quatro bandas visível/NIR.','Remote sensing | Land use and land cover | Environmental monitoring','CBERS-4 | WFI | Level-4 | orthorectified | digital number','Brasil e demais áreas imageadas/disponíveis na coleção','sim','cena raster ortorretificada | coleção STAC','64 m','2014–2026 conforme coleção STAC','por aquisição','conforme aquisição','ativo','CB4-WFI-L4-DN-1 v1','complete','https://data.inpe.br/bdc/stac/v1/collections/CB4-WFI-L4-DN-1','https://data.inpe.br/dados/cbers-4/','derivado','Produto ortorretificado continua em DN; não interpretar como reflectância de superfície nem duplicar com a versão SR da mesma aquisição.',DATE],
['DP000693','DR0123','CBERS-4/WFI — Level-4-SR em COG','CB4 WFI L4-SR','BIG — CBERS-4/WFI','dataset_series','Cenas CBERS-4/WFI Level-4 em reflectância de superfície, ortorretificadas e distribuídas em COG com quatro bandas e CMASK.','Remote sensing | Land use and land cover | Vegetation dynamics | Environmental monitoring','CBERS-4 | WFI | Level-4 | surface reflectance | COG | CMASK','Brasil e parte da América do Sul conforme coleção','sim','cena raster COG | coleção STAC','64 m','2016-01-01–2026-06-19 na coleção STAC verificada','por aquisição','novas cenas documentadas mensalmente','ativo','CB4-WFI-L4-SR-1 v1','complete','https://data.inpe.br/bdc/stac/v1/collections/CB4-WFI-L4-SR-1','https://data.inpe.br/dados/cbers-4/','derivado','Reflectância de superfície é produto processado; usar CMASK e metadados de aquisição. Não confundir com DN L2/L4.',DATE],
['DP000694','DR0123','CBERS-4/WFI — cubo Level-4-SR LCF de 16 dias','CB4 WFI 16D','Brazil Data Cube — cubos CBERS-4/WFI','dataset_series','Cubo de observação da Terra sobre o Brasil derivado de reflectância de superfície CBERS-4/WFI, composto a cada 16 dias pelo critério Least Cloud Cover First e distribuído em COG.','Remote sensing | Vegetation dynamics | Land use and land cover | Environmental monitoring','CBERS-4 | WFI | data cube | LCF | 16 days | NDVI | EVI','Brasil','sim','célula raster | cubo multidimensional','64 m','2016-01-01–2026-05-08 na coleção STAC verificada','16 dias','aproximadamente a cada 16 dias conforme insumos','ativo','CBERS4-WFI-16D-2 v2 / BDC_LG_V2','complete','https://data.inpe.br/bdc/stac/v1/collections/CBERS4-WFI-16D-2','https://data.inpe.br/dados/cbers-4/','derivado','LCF seleciona o melhor pixel da janela e não representa aquisição sinótica única; NDVI/EVI e camadas de observação/proveniência são derivados/auxiliares.',DATE],
['DP000695','DR0123','CBERS-4/PAN5M — Level-2-DN','CB4 PAN5M L2-DN','BIG — CBERS-4/PAN','dataset_series','Cenas pancromáticas CBERS-4/PAN5M Level-2 em número digital com correções radiométrica e geométrica de sistema.','Remote sensing | Cartography | Environmental monitoring','CBERS-4 | PAN | PAN5M | Level-2 | panchromatic | digital number','Brasil e demais áreas imageadas/disponíveis na coleção','sim','cena raster | coleção STAC','5 m','2014-12-09–2026-06-09 na coleção STAC verificada','por aquisição','conforme aquisição','ativo','CB4-PAN5M-L2-DN-1 v1','complete','https://data.inpe.br/bdc/stac/v1/collections/CB4-PAN5M-L2-DN-1','https://data.inpe.br/dados/cbers-4/','primário','Produto pancromático de 5 m em DN; não contém informação multiespectral equivalente às bandas PAN10M/MUX e não é ortorretificado Level-4.',DATE],
['DP000696','DR0123','CBERS-4/PAN5M — Level-4-DN ortorretificado','CB4 PAN5M L4-DN','BIG — CBERS-4/PAN','dataset_series','Cenas pancromáticas CBERS-4/PAN5M Level-4 em número digital e ortorretificadas.','Remote sensing | Cartography | Environmental monitoring','CBERS-4 | PAN | PAN5M | Level-4 | panchromatic | orthorectified','Brasil e demais áreas imageadas/disponíveis na coleção','sim','cena raster ortorretificada | coleção STAC','5 m','2014-12-09–2026-07-05 na coleção STAC verificada','por aquisição','conforme aquisição','ativo','CB4-PAN5M-L4-DN-1 v1','complete','https://data.inpe.br/bdc/stac/v1/collections/CB4-PAN5M-L4-DN-1','https://data.inpe.br/dados/cbers-4/','derivado','Ortorretificação não transforma DN em reflectância e a banda pancromática não deve ser interpretada como multiespectral.',DATE],
['DP000697','DR0123','CBERS-4/PAN10M — Level-2-DN','CB4 PAN10M L2-DN','BIG — CBERS-4/PAN','dataset_series','Cenas multiespectrais CBERS-4/PAN10M Level-2 em número digital nas bandas verde, vermelho e NIR, com correções radiométrica e geométrica de sistema.','Remote sensing | Cartography | Land use and land cover | Environmental monitoring','CBERS-4 | PAN | PAN10M | Level-2 | multispectral | digital number','Brasil e demais áreas imageadas/disponíveis na coleção','sim','cena raster | coleção STAC','10 m','2014-12-09–2026-07-26 na coleção STAC verificada','por aquisição','conforme aquisição','ativo','CB4-PAN10M-L2-DN-1 v1','complete','https://data.inpe.br/bdc/stac/v1/collections/CB4-PAN10M-L2-DN-1','https://data.inpe.br/dados/cbers-4/','primário','PAN10M é multiespectral verde/vermelho/NIR a 10 m e não equivale à banda pancromática PAN5M; Level-2 não é ortorretificação final.',DATE],
['DP000698','DR0123','CBERS-4/PAN10M — Level-4-DN ortorretificado','CB4 PAN10M L4-DN','BIG — CBERS-4/PAN','dataset_series','Cenas multiespectrais CBERS-4/PAN10M Level-4 em número digital, ortorretificadas, nas bandas verde, vermelho e NIR.','Remote sensing | Cartography | Land use and land cover | Environmental monitoring','CBERS-4 | PAN | PAN10M | Level-4 | multispectral | orthorectified','Brasil e demais áreas imageadas/disponíveis na coleção','sim','cena raster ortorretificada | coleção STAC','10 m','2014–2026 conforme coleção STAC','por aquisição','conforme aquisição','ativo','CB4-PAN10M-L4-DN-1 v1','complete','https://data.inpe.br/bdc/stac/v1/collections/CB4-PAN10M-L4-DN-1','https://data.inpe.br/dados/cbers-4/','derivado','Produto ortorretificado permanece em DN; PAN10M é multiespectral e não deve ser confundido com PAN5M pancromático.',DATE],
['DP000699','DR0123','CBERS-4/WFI — mosaico nacional de 3 meses 2020','CB4 WFI 3M Mosaic','Brazil Data Cube — mosaicos CBERS/WFI','dataset_series','Mosaico do Brasil em falsa cor derivado de mais de 1.200 cenas CBERS-4/WFI, composto por LCF para abril–junho de 2020 e distribuído em COG.','Remote sensing | Cartography | Environmental visualization','CBERS-4 | WFI | mosaic | LCF | 3 months | 2020','Brasil','sim','mosaico raster COG','64 m','2020-04-01–2020-06-30','mosaico único de período','produto histórico/estático','arquivado','mosaic-cbers4-brazil-3m-1 v1','complete','https://data.inpe.br/bdc/stac/v1/collections/mosaic-cbers4-brazil-3m-1','https://data.inpe.br/dados/cbers-4/','derivado','Mosaico demonstrativo de um intervalo de três meses em 2020; não representa estado atual, aquisição sinótica única ou série temporal contínua.',DATE],
['DP000700','DR0123','CBERS-4A/MUX — Level-4-SR em COG','CB4A MUX L4-SR','BIG — CBERS-4A/MUX','dataset_series','Cenas CBERS-4A/MUX Level-4 em reflectância de superfície, ortorretificadas e distribuídas em COG com quatro bandas e CMASK.','Remote sensing | Land use and land cover | Vegetation dynamics | Environmental monitoring','CBERS-4A | MUX | Level-4 | surface reflectance | COG | CMASK','Brasil e parte da América do Sul conforme coleção','sim','cena raster COG | coleção STAC','16 m','2026-01-01–2026-07-19 na coleção STAC verificada','por aquisição','conforme processamento/publicação','ativo','CB4A-MUX-L4-SR-1 v1','complete','https://data.inpe.br/bdc/stac/v1/collections/CB4A-MUX-L4-SR-1','https://data.inpe.br/dados/cbers-4a/','derivado','Reflectância de superfície é produto processado e não deve ser confundida com os produtos L2-DN e L4-DN já catalogados; usar CMASK e metadados de aquisição.',DATE],
]

dists=[]
def dist(did,pid,name,url,fmt,notes,tool='cliente STAC | navegador | GIS/Python',protocol='STAC API / HTTPS',subset='por cena, data, footprint e banda'):
    return [did,pid,name,url,fmt,protocol,tool,'sim','não','consulta por coleção/item/asset','CC BY 4.0','sim',subset,notes,DATE]

dists.extend([
dist('DD000717','DP000687','CBERS-4/MUX L2-DN — STAC','https://data.inpe.br/bdc/stac/v1/collections/CB4-MUX-L2-DN-1','GeoTIFF + XML + PNG thumbnail','Quatro bandas MUX a 20 m; nível L2-DN.'),
dist('DD000718','DP000688','CBERS-4/MUX L4-DN — STAC','https://data.inpe.br/bdc/stac/v1/collections/CB4-MUX-L4-DN-1','GeoTIFF + XML + PNG thumbnail','Quatro bandas MUX ortorretificadas a 20 m em DN.'),
dist('DD000719','DP000689','CBERS-4/MUX L4-SR — STAC/COG','https://data.inpe.br/bdc/stac/v1/collections/CB4-MUX-L4-SR-1','Cloud Optimized GeoTIFF','Reflectância de superfície MUX a 20 m com CMASK.','cliente STAC | GIS | Python','STAC API / HTTPS range requests','por cena, data, footprint e banda'),
dist('DD000720','DP000690','CBERS-4/MUX 2M LCF — STAC/COG','https://data.inpe.br/bdc/stac/v1/collections/CBERS4-MUX-2M-1','Cloud Optimized GeoTIFF','Inclui reflectância, CMASK, ClearOB, TotalOB, DayOfYear, NDVI e EVI.','cliente STAC | BDC Explorer | GIS/Python','STAC API / HTTPS range requests','por tile, janela bimestral e banda'),
dist('DD000721','DP000691','CBERS-4/WFI L2-DN — STAC','https://data.inpe.br/bdc/stac/v1/collections/CB4-WFI-L2-DN-1','GeoTIFF + XML + PNG thumbnail','Quatro bandas WFI a 64 m; nível L2-DN.'),
dist('DD000722','DP000692','CBERS-4/WFI L4-DN — STAC','https://data.inpe.br/bdc/stac/v1/collections/CB4-WFI-L4-DN-1','GeoTIFF + XML + PNG thumbnail','Quatro bandas WFI ortorretificadas a 64 m em DN.'),
dist('DD000723','DP000693','CBERS-4/WFI L4-SR — STAC/COG','https://data.inpe.br/bdc/stac/v1/collections/CB4-WFI-L4-SR-1','Cloud Optimized GeoTIFF','Reflectância de superfície WFI a 64 m com CMASK.','cliente STAC | GIS | Python','STAC API / HTTPS range requests','por cena, data, footprint e banda'),
dist('DD000724','DP000694','CBERS-4/WFI 16D LCF — STAC/COG','https://data.inpe.br/bdc/stac/v1/collections/CBERS4-WFI-16D-2','Cloud Optimized GeoTIFF','Inclui reflectância, CMASK, ClearOB, TotalOB, DayOfYear, NDVI e EVI.','cliente STAC | BDC Explorer | GIS/Python','STAC API / HTTPS range requests','por tile, janela de 16 dias e banda'),
dist('DD000725','DP000695','CBERS-4/PAN5M L2-DN — STAC','https://data.inpe.br/bdc/stac/v1/collections/CB4-PAN5M-L2-DN-1','GeoTIFF + XML + PNG thumbnail','Banda pancromática a 5 m em DN Level-2.'),
dist('DD000726','DP000696','CBERS-4/PAN5M L4-DN — STAC','https://data.inpe.br/bdc/stac/v1/collections/CB4-PAN5M-L4-DN-1','GeoTIFF + XML + PNG thumbnail','Banda pancromática ortorretificada a 5 m em DN.'),
dist('DD000727','DP000697','CBERS-4/PAN10M L2-DN — STAC','https://data.inpe.br/bdc/stac/v1/collections/CB4-PAN10M-L2-DN-1','GeoTIFF + XML + PNG thumbnail','Bandas verde, vermelho e NIR a 10 m em DN Level-2.'),
dist('DD000728','DP000698','CBERS-4/PAN10M L4-DN — STAC','https://data.inpe.br/bdc/stac/v1/collections/CB4-PAN10M-L4-DN-1','GeoTIFF + XML + PNG thumbnail','Bandas verde, vermelho e NIR ortorretificadas a 10 m em DN.'),
dist('DD000729','DP000699','CBERS-4/WFI 3M Mosaic — STAC/COG','https://data.inpe.br/bdc/stac/v1/collections/mosaic-cbers4-brazil-3m-1','Cloud Optimized GeoTIFF','Mosaico nacional histórico abril–junho de 2020 em falsa cor.','cliente STAC | GIS | navegador','STAC API / HTTPS range requests','mosaico único por asset'),
dist('DD000730','DP000700','CBERS-4A/MUX L4-SR — STAC/COG','https://data.inpe.br/bdc/stac/v1/collections/CB4A-MUX-L4-SR-1','Cloud Optimized GeoTIFF','Reflectância de superfície CBERS-4A/MUX a 16 m com CMASK.','cliente STAC | GIS | Python','STAC API / HTTPS range requests','por cena, data, footprint e banda'),
])

with P.open(encoding='utf-8-sig',newline='') as f:
    existing=list(csv.DictReader(f))
ids={r['product_id'] for r in existing}; urls={r['product_page_url'] for r in existing}
for r in products:
    assert r[0] not in ids, r[0]
    assert r[19] not in urls, r[19]
with D.open(encoding='utf-8-sig',newline='') as f:
    existing_d=list(csv.DictReader(f))
dids={r['distribution_id'] for r in existing_d}; durls={(r['product_id'],r['access_url']) for r in existing_d}
for r in dists:
    assert r[0] not in dids, r[0]
    assert (r[1],r[3]) not in durls, (r[1],r[3])
with P.open('a',encoding='utf-8',newline='') as f:
    w=csv.writer(f,lineterminator='\n'); w.writerows(products)
with D.open('a',encoding='utf-8',newline='') as f:
    w=csv.writer(f,lineterminator='\n'); w.writerows(dists)
print(f'OK append {len(products)} products {len(dists)} distributions')
