#!/usr/bin/env python3
import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TODAY = "2026-08-14"

products = [
 {"product_id":"DP000025","resource_id":"DR0010","product_name":"Cobertura e Uso da Terra — Coleção 10.1","product_acronym":"MapBiomas LULC 10.1","product_family":"MapBiomas Cobertura e Uso da Terra","product_kind":"dataset_series","product_description":"Série anual revisada de mapas de cobertura e uso da terra do Brasil para 1985–2024, organizada na Coleção 10.1 do MapBiomas.","research_areas":"Land use and land cover | Remote sensing | Ecology | Territorial analysis","keywords":"uso da terra | cobertura da terra | séries anuais | MapBiomas | Brasil","geographic_coverage":"Brasil","covers_brazil":"sim","spatial_support":"célula raster | estatísticas territoriais derivadas","spatial_resolution":"30 m na série principal; produtos complementares podem diferir","temporal_coverage":"1985–2024","temporal_resolution":"anual","update_frequency":"por coleção, com revisão da série histórica","product_status":"ativo","version_or_collection":"Coleção 10.1","enumeration_scope":"complete","product_page_url":"https://brasil.mapbiomas.org/colecoes-mapbiomas/","methodology_url":"https://brasil.mapbiomas.org/metodo_cobertura_e_uso/","primary_or_derived":"derivado","limitations":"Coleções são revisadas e podem alterar classes ou classificação histórica; registrar coleção, legenda e data de acesso. A Coleção 10.1 corrigiu aspectos da série 1985–2003 e pixels NODATA em áreas específicas.","last_verified":TODAY},
 {"product_id":"DP000026","resource_id":"DR0010","product_name":"Desmatamento e Vegetação Secundária — Coleção 10.1","product_acronym":"MapBiomas Desmatamento/VS 10.1","product_family":"MapBiomas Desmatamento e Vegetação Secundária","product_kind":"dataset_series","product_description":"Série derivada da Coleção 10.1 para caracterizar desmatamento e vegetação secundária, com mapas e estatísticas por múltiplos recortes territoriais.","research_areas":"Land use change | Restoration ecology | Remote sensing | Conservation","keywords":"desmatamento | vegetação secundária | regeneração | MapBiomas | Brasil","geographic_coverage":"Brasil","covers_brazil":"sim","spatial_support":"célula raster | estatísticas territoriais derivadas","spatial_resolution":"herdada da coleção de cobertura e uso; consultar produto","temporal_coverage":"1987–2024 nas estatísticas oficiais consultadas","temporal_resolution":"anual","update_frequency":"por coleção","product_status":"ativo","version_or_collection":"Coleção 10.1","enumeration_scope":"complete","product_page_url":"https://brasil.mapbiomas.org/colecoes-mapbiomas/","methodology_url":"https://brasil.mapbiomas.org/colecoes-mapbiomas/","primary_or_derived":"derivado","limitations":"Desmatamento e vegetação secundária são produtos derivados e não devem ser confundidos com alertas operacionais; registrar coleção, definição e recorte territorial.","last_verified":TODAY},
 {"product_id":"DP000027","resource_id":"DR0010","product_name":"MapBiomas Fogo — Coleção 4","product_acronym":"MapBiomas Fogo 4","product_family":"MapBiomas Fogo","product_kind":"dataset_series","product_description":"Coleção de mapas de cicatrizes de fogo, áreas queimadas anuais e acumuladas e cobertura atingida pelo fogo no Brasil.","research_areas":"Fire ecology | Remote sensing | Conservation | Land use","keywords":"fogo | área queimada | cicatriz de fogo | MapBiomas | Brasil","geographic_coverage":"Brasil","covers_brazil":"sim","spatial_support":"célula raster | vetores derivados","spatial_resolution":"consultar coleção e distribuição","temporal_coverage":"1985–2024 nos produtos acumulados oficiais consultados","temporal_resolution":"anual e acumulada; Monitor do Fogo possui outra cadência","update_frequency":"por coleção e produtos operacionais associados","product_status":"ativo","version_or_collection":"Coleção 4","enumeration_scope":"family_level","product_page_url":"https://brasil.mapbiomas.org/colecoes-mapbiomas/","methodology_url":"https://brasil.mapbiomas.org/colecoes-mapbiomas/","primary_or_derived":"derivado","limitations":"Distinguir coleção histórica de cicatrizes do Monitor do Fogo e registrar produto, período e versão; área queimada não é equivalente a contagem de focos ativos.","last_verified":TODAY},
 {"product_id":"DP000028","resource_id":"DR0010","product_name":"MapBiomas Pastagem — Coleção 10","product_acronym":"MapBiomas Pastagem 10","product_family":"MapBiomas Pastagem","product_kind":"dataset_series","product_description":"Família de produtos sobre pastagens brasileiras, incluindo vigor, idade e biomassa de pastagem disponibilizados na Coleção 10.","research_areas":"Grassland ecology | Agriculture | Remote sensing | Land use","keywords":"pastagem | vigor | idade | biomassa | MapBiomas | Brasil","geographic_coverage":"Brasil","covers_brazil":"sim","spatial_support":"célula raster | estatísticas territoriais derivadas","spatial_resolution":"consultar camada da coleção","temporal_coverage":"varia conforme módulo e camada","temporal_resolution":"anual ou variável conforme camada","update_frequency":"por coleção","product_status":"ativo","version_or_collection":"Coleção 10","enumeration_scope":"family_level","product_page_url":"https://brasil.mapbiomas.org/colecoes-mapbiomas/","methodology_url":"https://brasil.mapbiomas.org/colecoes-mapbiomas/","primary_or_derived":"derivado","limitations":"Vigor, idade e biomassa são variáveis distintas e não intercambiáveis; preservar a camada, a versão e a definição metodológica usadas.","last_verified":TODAY},
 {"product_id":"DP000029","resource_id":"DR0010","product_name":"MapBiomas Agricultura — Coleção 10","product_acronym":"MapBiomas Agricultura 10","product_family":"MapBiomas Agricultura","product_kind":"dataset_series","product_description":"Família de produtos agrícolas da Coleção 10, incluindo sistemas de irrigação e frequência média e anual de ciclos de cultivo.","research_areas":"Agriculture | Remote sensing | Land use | Territorial analysis","keywords":"agricultura | irrigação | ciclos de cultivo | MapBiomas | Brasil","geographic_coverage":"Brasil","covers_brazil":"sim","spatial_support":"célula raster","spatial_resolution":"consultar camada da coleção","temporal_coverage":"varia conforme camada","temporal_resolution":"anual ou agregado conforme camada","update_frequency":"por coleção","product_status":"ativo","version_or_collection":"Coleção 10","enumeration_scope":"family_level","product_page_url":"https://brasil.mapbiomas.org/colecoes-mapbiomas/","methodology_url":"https://brasil.mapbiomas.org/colecoes-mapbiomas/","primary_or_derived":"derivado","limitations":"As camadas representam atributos agrícolas distintos; não generalizar período, definição ou acurácia entre irrigação e frequência de cultivos.","last_verified":TODAY},
 {"product_id":"DP000030","resource_id":"DR0012","product_name":"Focos de Queimadas e Incêndios","product_acronym":"Focos INPE","product_family":"Programa Queimadas — focos ativos","product_kind":"dataset_series","product_description":"Série operacional de detecções de focos de fogo por satélite, disponibilizada em intervalos de anuais a tempo quase real, com atualização dos dados mais recentes a cada 10 minutos.","research_areas":"Fire ecology | Remote sensing | Environmental monitoring","keywords":"focos de fogo | queimadas | incêndios | satélite | INPE","geographic_coverage":"Brasil e demais áreas monitoradas pelo programa","covers_brazil":"sim","spatial_support":"ponto de detecção por satélite","spatial_resolution":"depende do sensor e satélite","temporal_coverage":"1998–presente para o acervo destacado pelo portal","temporal_resolution":"quase em tempo real | diária | mensal | anual","update_frequency":"até a cada 10 minutos nos arquivos recentes","product_status":"ativo","version_or_collection":"serviço operacional corrente","enumeration_scope":"complete","product_page_url":"https://terrabrasilis.dpi.inpe.br/queimadas/portal/pages/secao_downloads/dados-abertos/","methodology_url":"https://terrabrasilis.dpi.inpe.br/queimadas/portal/informacoes/perguntas-frequentes/","primary_or_derived":"derivado","limitations":"Foco detectado não equivale automaticamente a incêndio individual nem a área queimada; registrar satélite, sensor, período e satélite de referência quando usado em comparações.","last_verified":TODAY},
 {"product_id":"DP000031","resource_id":"DR0012","product_name":"Eventos de Fogo","product_acronym":"Eventos de Fogo INPE","product_family":"Programa Queimadas — eventos de fogo","product_kind":"dataset_series","product_description":"Integração espaço-temporal de focos de fogo ativo para distinguir eventos de incêndios e queimadas no Brasil, incluindo localização de frentes, estimativa de área, duração e atributos associados.","research_areas":"Fire ecology | Environmental monitoring | Remote sensing | Land use","keywords":"eventos de fogo | incêndios | queimadas | área queimada | INPE","geographic_coverage":"Brasil","covers_brazil":"sim","spatial_support":"evento espaço-temporal | frentes de fogo","spatial_resolution":"derivada das detecções integradas; consultar produto","temporal_coverage":"corrente; consultar disponibilidade","temporal_resolution":"evento; atualização horária dos eventos ativos/em observação","update_frequency":"horária","product_status":"provisório","version_or_collection":"produto em fase de validação — maturidade Provisório","enumeration_scope":"complete","product_page_url":"https://terrabrasilis.dpi.inpe.br/queimadas/portal/pages/secao_downloads/dados-abertos/","methodology_url":"https://terrabrasilis.dpi.inpe.br/queimadas/portal/pages/secao_downloads/dados-abertos/","primary_or_derived":"derivado","limitations":"Produto explicitamente em validação e maturidade provisória; não tratar como série consolidada sem registrar data, estado do evento e versão/metodologia disponível.","last_verified":TODAY},
 {"product_id":"DP000032","resource_id":"DR0012","product_name":"Área Queimada AQ1km","product_acronym":"AQ1km","product_family":"Programa Queimadas — área queimada","product_kind":"dataset_series","product_description":"Produto mensal do Programa Queimadas que delimita a extensão de áreas atingidas pelo fogo na vegetação, disponibilizado em raster TIFF e Shapefile.","research_areas":"Fire ecology | Remote sensing | Environmental monitoring","keywords":"área queimada | AQ1km | fogo | vegetação | INPE","geographic_coverage":"Brasil e cobertura definida pelo produto","covers_brazil":"sim","spatial_support":"célula raster | polígonos vetoriais","spatial_resolution":"1 km conforme denominação AQ1km","temporal_coverage":"série conforme acervo do programa","temporal_resolution":"mensal","update_frequency":"mensal","product_status":"ativo","version_or_collection":"AQ1km corrente","enumeration_scope":"complete","product_page_url":"https://terrabrasilis.dpi.inpe.br/queimadas/portal/pages/secao_downloads/dados-abertos/","methodology_url":"https://terrabrasilis.dpi.inpe.br/queimadas/portal/pages/secao_downloads/dados-abertos/","primary_or_derived":"derivado","limitations":"Área queimada é um estimador espacial distinto de focos ativos; verificar método, período, cobertura e eventuais limitações de detecção antes de comparação com outros produtos de fogo.","last_verified":TODAY},
 {"product_id":"DP000033","resource_id":"DR0012","product_name":"Risco de Fogo e Meteorologia","product_acronym":"Risco de Fogo INPE","product_family":"Programa Queimadas — risco de fogo e meteorologia","product_kind":"indicator_family","product_description":"Família de camadas diárias observadas e previstas de risco de fogo e variáveis meteorológicas associadas, incluindo precipitação, temperatura, umidade relativa e dias sem chuva.","research_areas":"Fire risk | Climate science | Environmental monitoring | Remote sensing","keywords":"risco de fogo | meteorologia | precipitação | temperatura | umidade | INPE","geographic_coverage":"Brasil e cobertura operacional do programa","covers_brazil":"sim","spatial_support":"grade espacial","spatial_resolution":"varia conforme variável/produto; consultar documentação","temporal_coverage":"corrente e histórico conforme arquivo/anuário","temporal_resolution":"diária; previsões para até 3 dias","update_frequency":"diária","product_status":"ativo","version_or_collection":"produto operacional corrente","enumeration_scope":"family_level","product_page_url":"https://terrabrasilis.dpi.inpe.br/queimadas/portal/pages/secao_downloads/dados-abertos/","methodology_url":"https://terrabrasilis.dpi.inpe.br/queimadas/portal/pages/secao_relatorio/anuario-risco-de-fogo/","primary_or_derived":"derivado","limitations":"Distinguir observado de previsto, variável meteorológica de índice de risco e horizonte de previsão; não tratar a família como uma única variável homogênea.","last_verified":TODAY},
 {"product_id":"DP000034","resource_id":"DR0016","product_name":"CNUC — lista de Unidades de Conservação ativas","product_acronym":"CNUC tabular","product_family":"Cadastro Nacional de Unidades de Conservação","product_kind":"dataset_series","product_description":"Snapshots tabulares oficiais das unidades de conservação ativas no CNUC, com categoria de manejo, área, esfera de governo, ano de criação e outros atributos cadastrais.","research_areas":"Conservation | Protected areas | Environmental policy | Territorial planning","keywords":"unidades de conservação | CNUC | SNUC | áreas protegidas | cadastro","geographic_coverage":"Brasil","covers_brazil":"sim","spatial_support":"unidade de conservação | atributos cadastrais","spatial_resolution":"não se aplica","temporal_coverage":"situação cadastral por snapshot; edição corrente consultada março de 2026","temporal_resolution":"snapshot administrativo","update_frequency":"semestral conforme catálogo de dados abertos","product_status":"ativo","version_or_collection":"CNUC_2026_03","enumeration_scope":"complete","product_page_url":"https://dados.gov.br/dados/conjuntos-dados/unidadesdeconservacao","methodology_url":"https://www.gov.br/mma/pt-br/composicao/sbio/dap/cadastro-nacional-de-ucs","primary_or_derived":"primário","limitations":"Situação administrativa e atributos podem mudar; registrar a data do snapshot. O cadastro oficial depende das informações mantidas pelos órgãos gestores nas diferentes esferas.","last_verified":TODAY},
 {"product_id":"DP000035","resource_id":"DR0016","product_name":"CNUC — limites geoespaciais das Unidades de Conservação","product_acronym":"CNUC geoespacial","product_family":"Cadastro Nacional de Unidades de Conservação","product_kind":"dataset_series","product_description":"Snapshots geoespaciais oficiais dos limites das unidades de conservação com registro ativo no CNUC, disponibilizados para uso em SIG.","research_areas":"Conservation | Protected areas | GIS | Territorial planning","keywords":"unidades de conservação | limites | shapefile | CNUC | áreas protegidas","geographic_coverage":"Brasil","covers_brazil":"sim","spatial_support":"polígonos de unidades de conservação","spatial_resolution":"precisão e qualidade variam por UC; o sistema registra qualidade do dado geoespacial","temporal_coverage":"situação cadastral por snapshot; edição corrente consultada março de 2026","temporal_resolution":"snapshot administrativo","update_frequency":"semestral conforme catálogo de dados abertos","product_status":"ativo","version_or_collection":"CNUC_2026_03","enumeration_scope":"complete","product_page_url":"https://dados.gov.br/dados/conjuntos-dados/unidadesdeconservacao","methodology_url":"https://www.gov.br/mma/pt-br/composicao/sbio/dap/cadastro-nacional-de-ucs","primary_or_derived":"primário","limitations":"Limites e qualidade geométrica não possuem precisão uniforme; registrar snapshot, qualidade do dado geoespacial e órgão gestor. Não interpretar polígonos como precisão cadastral homogênea.","last_verified":TODAY},
]

dists = [
 {"distribution_id":"DD000033","product_id":"DP000025","distribution_name":"MapBiomas LULC 10.1 — plataforma/GEE","access_url":"https://brasil.mapbiomas.org/colecoes-mapbiomas/","format":"GeoTIFF | asset Google Earth Engine | estatísticas tabulares","access_protocol":"HTTP download | Google Earth Engine","access_tool":"Plataforma MapBiomas | GEE Toolkit | script","free_download":"sim","authentication_required":"parcial","access_conditions":"dados públicos, abertos e gratuitos; GEE requer conta/projeto conforme serviço","license":"CC BY; atribuição MapBiomas requerida","provider_attribution_required":"sim","subset_support":"estado | bioma | município | território vetorial via ferramentas documentadas","notes":"Asset oficial da Coleção 10.1 e downloads são listados na página de coleções; registrar coleção e legenda.","last_verified":TODAY},
 {"distribution_id":"DD000034","product_id":"DP000026","distribution_name":"MapBiomas Desmatamento/Vegetação Secundária 10.1 — GEE/estatísticas","access_url":"https://brasil.mapbiomas.org/colecoes-mapbiomas/","format":"asset Google Earth Engine | estatísticas tabulares","access_protocol":"Google Earth Engine | HTTP download","access_tool":"GEE Toolkit | Plataforma MapBiomas | navegador","free_download":"sim","authentication_required":"parcial","access_conditions":"dados públicos; acesso GEE sujeito às condições do serviço","license":"CC BY; atribuição MapBiomas requerida","provider_attribution_required":"sim","subset_support":"múltiplos recortes territoriais","notes":"A página oficial lista o asset conjunto de desmatamento e vegetação secundária da Coleção 10.1.","last_verified":TODAY},
 {"distribution_id":"DD000035","product_id":"DP000027","distribution_name":"MapBiomas Fogo 4 — mapas anuais e acumulados","access_url":"https://brasil.mapbiomas.org/colecoes-mapbiomas/","format":"GeoTIFF | ZIP vetorial | asset Google Earth Engine","access_protocol":"HTTP download | Google Earth Engine","access_tool":"navegador | SIG | GEE","free_download":"sim","authentication_required":"parcial","access_conditions":"dados públicos; GEE sujeito às condições do serviço","license":"CC BY; atribuição MapBiomas requerida","provider_attribution_required":"sim","subset_support":"Brasil; recortes via ferramentas MapBiomas/GEE","notes":"A página oficial lista rasters anuais/acumulados e vetores; não tratar cada ano como produto autônomo.","last_verified":TODAY},
 {"distribution_id":"DD000036","product_id":"DP000028","distribution_name":"MapBiomas Pastagem 10 — assets de vigor, idade e biomassa","access_url":"https://brasil.mapbiomas.org/colecoes-mapbiomas/","format":"assets Google Earth Engine | exportações raster","access_protocol":"Google Earth Engine | HTTP","access_tool":"GEE | Plataforma MapBiomas","free_download":"sim","authentication_required":"parcial","access_conditions":"dados públicos; GEE sujeito às condições do serviço","license":"CC BY; atribuição MapBiomas requerida","provider_attribution_required":"sim","subset_support":"espacial e temporal conforme ferramenta/camada","notes":"A página oficial lista assets distintos para vigor, idade e biomassa da pastagem na Coleção 10.","last_verified":TODAY},
 {"distribution_id":"DD000037","product_id":"DP000029","distribution_name":"MapBiomas Agricultura 10 — assets de irrigação e ciclos de cultivo","access_url":"https://brasil.mapbiomas.org/colecoes-mapbiomas/","format":"assets Google Earth Engine | exportações raster","access_protocol":"Google Earth Engine | HTTP","access_tool":"GEE | Plataforma MapBiomas","free_download":"sim","authentication_required":"parcial","access_conditions":"dados públicos; GEE sujeito às condições do serviço","license":"CC BY; atribuição MapBiomas requerida","provider_attribution_required":"sim","subset_support":"espacial e temporal conforme ferramenta/camada","notes":"A página oficial lista sistemas de irrigação e frequência média/anual de ciclos de cultivo na Coleção 10.","last_verified":TODAY},
 {"distribution_id":"DD000038","product_id":"DP000030","distribution_name":"Focos de Queimadas — CSV/KML","access_url":"https://terrabrasilis.dpi.inpe.br/queimadas/portal/pages/secao_downloads/dados-abertos/","format":"CSV | KML","access_protocol":"HTTP download","access_tool":"navegador | SIG | script","free_download":"sim","authentication_required":"não","access_conditions":"dados abertos para uso público","license":"dados abertos; citar Programa Queimadas/INPE conforme orientação da fonte","provider_attribution_required":"sim","subset_support":"intervalos recentes, diários, mensais e anuais conforme arquivos","notes":"Arquivos incluem últimos 10 minutos, diários, mensais e anuais em CSV e opções KML.","last_verified":TODAY},
 {"distribution_id":"DD000039","product_id":"DP000031","distribution_name":"Eventos de Fogo — eventos ativos/em observação","access_url":"https://terrabrasilis.dpi.inpe.br/queimadas/portal/pages/secao_downloads/dados-abertos/","format":"KML","access_protocol":"HTTP download","access_tool":"navegador | Google Earth | SIG","free_download":"sim","authentication_required":"não","access_conditions":"dados abertos; produto provisório em validação","license":"dados abertos; citar Programa Queimadas/INPE","provider_attribution_required":"sim","subset_support":"eventos ativos | eventos em observação","notes":"Atualização horária e maturidade Provisório devem acompanhar qualquer uso.","last_verified":TODAY},
 {"distribution_id":"DD000040","product_id":"DP000032","distribution_name":"AQ1km — raster e vetor mensal","access_url":"https://terrabrasilis.dpi.inpe.br/queimadas/portal/pages/secao_downloads/dados-abertos/","format":"TIFF | Shapefile","access_protocol":"HTTP download","access_tool":"navegador | SIG","free_download":"sim","authentication_required":"não","access_conditions":"dados abertos para uso público","license":"dados abertos; citar Programa Queimadas/INPE","provider_attribution_required":"sim","subset_support":"mensal","notes":"Produto AQ 1 km possui arquivos mensais raster e Shapefile.","last_verified":TODAY},
 {"distribution_id":"DD000041","product_id":"DP000033","distribution_name":"Risco de Fogo e Meteorologia — observado e previsto","access_url":"https://terrabrasilis.dpi.inpe.br/queimadas/portal/pages/secao_downloads/dados-abertos/","format":"arquivos raster/meteorológicos conforme variável | mapas web","access_protocol":"HTTP download | visualização web","access_tool":"navegador | SIG","free_download":"sim","authentication_required":"não","access_conditions":"dados abertos para uso público","license":"dados abertos; citar Programa Queimadas/INPE","provider_attribution_required":"sim","subset_support":"variável | observado | previsão até 3 dias","notes":"A página oficial separa risco observado diário e risco previsto para os próximos três dias, junto a variáveis meteorológicas.","last_verified":TODAY},
 {"distribution_id":"DD000042","product_id":"DP000034","distribution_name":"CNUC_2026_03 — tabela de UCs ativas","access_url":"https://dados.gov.br/dados/conjuntos-dados/unidadesdeconservacao","format":"CSV","access_protocol":"HTTP download | Portal de Dados Abertos","access_tool":"navegador | planilha | script","free_download":"sim","authentication_required":"não","access_conditions":"download público","license":"Creative Commons Attribution","provider_attribution_required":"sim","subset_support":"consulta/filtragem após download; relatório parametrizado disponível no CNUC","notes":"Recurso oficial contém lista de UCs ativas com dados atualizados até março de 2026; catálogo informa atualização semestral.","last_verified":TODAY},
 {"distribution_id":"DD000043","product_id":"DP000035","distribution_name":"CNUC_2026_03 — limites geoespaciais","access_url":"https://dados.gov.br/dados/conjuntos-dados/unidadesdeconservacao","format":"ZIP | Shapefile","access_protocol":"HTTP download | Portal de Dados Abertos","access_tool":"navegador | SIG","free_download":"sim","authentication_required":"não","access_conditions":"download público","license":"Creative Commons Attribution","provider_attribution_required":"sim","subset_support":"snapshot nacional; filtros e downloads também disponíveis no mapa CNUC","notes":"Recurso oficial de março de 2026 contém limites das UCs com registro ativo; qualidade geométrica varia entre registros.","last_verified":TODAY},
]

def append(path, rows, expected_last, key):
    with path.open(encoding="utf-8", newline="") as f:
        r = csv.DictReader(f); fields=list(r.fieldnames or []); old=list(r)
    assert old[-1][key] == expected_last, (path, old[-1][key])
    ids={x[key] for x in old}
    assert not any(x[key] in ids for x in rows)
    for x in rows:
        assert set(x)==set(fields), (path, set(fields)-set(x), set(x)-set(fields))
    with path.open("a", encoding="utf-8", newline="") as f:
        csv.DictWriter(f, fieldnames=fields, lineterminator="\n").writerows(rows)

p=ROOT/"data/data_products.csv"; d=ROOT/"data/product_distributions.csv"
append(p, products, "DP000024", "product_id")
append(d, dists, "DD000032", "distribution_id")

with p.open(encoding="utf-8", newline="") as f: pr=list(csv.DictReader(f))
with d.open(encoding="utf-8", newline="") as f: dr=list(csv.DictReader(f))
with (ROOT/"data/data_resources.csv").open(encoding="utf-8", newline="") as f: sr=list(csv.DictReader(f))
assert len(sr)==55 and len(pr)==35 and len(dr)==43
sids={x['resource_id'] for x in sr}; pids={x['product_id'] for x in pr}
assert len(pids)==len(pr) and len({x['distribution_id'] for x in dr})==len(dr)
assert all(x['resource_id'] in sids for x in pr)
assert all(x['product_id'] in pids for x in dr)
print(f"OK: {len(sr)} fontes, {len(pr)} produtos, {len(dr)} distribuições")
