#!/usr/bin/env python3
import csv, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
TODAY='2026-08-14'

def read(path):
    with path.open(encoding='utf-8-sig',newline='') as f:
        r=csv.DictReader(f); return list(r.fieldnames or []),list(r)
def write(path,fields,rows):
    with path.open('w',encoding='utf-8',newline='') as f:
        w=csv.DictWriter(f,fieldnames=fields,lineterminator='\n'); w.writeheader(); w.writerows(rows)

rf,rr=read(ROOT/'data/data_resources.csv')
pf,pr=read(ROOT/'data/data_products.csv')
df,dr=read(ROOT/'data/product_distributions.csv')
assert len(rr)==58 and len(pr)==39 and len(dr)==47
assert rr[-1]['resource_id']=='DR0058' and pr[-1]['product_id']=='DP000039' and dr[-1]['distribution_id']=='DD000047'

new_source={
'resource_id':'DR0059','resource_name':'Projeções Climáticas no Brasil','acronym':'PClima / PCBr','official_identity':'Portal de Projeções Climáticas no Brasil do INPE/MCTI','description':'Plataforma oficial para visualizar e baixar projeções de mudanças climáticas sobre o Brasil produzidas a partir de modelos climáticos globais e regionais.','homepage_url':'https://pclima.inpe.br/','data_access_url':'https://pclima.inpe.br/analise/','research_areas':'Clima e Ciências Atmosféricas | Ciências Ambientais e Ecologia | Planejamento Territorial e Políticas Públicas','keywords':'projeções climáticas | mudanças climáticas | CMIP5 | CMIP6 | Eta | BESM | Brasil','data_product_types':'projeções climáticas | mapas | séries | API','data_formats':'formatos variáveis conforme consulta e exportação; API permite seleção de formato','visualization_types':'mapa interativo | gráficos | download','geographic_coverage':'Brasil','covers_brazil':'sim','spatial_resolution':'varia conforme modelo e experimento','temporal_coverage':'simulações históricas e projeções para o século XXI; varia conforme conjunto','temporal_resolution':'varia conforme modelo, variável e frequência selecionada','data_sources':'CMIP5 | CMIP6 | HELIX | BESM | Eta/CPTEC/INPE','free_download':'sim','access_conditions':'visualização e download públicos; API possui fluxo de token/cadastro','programmatic_access':'sim','access_protocols':'HTTP download | API','authentication_required':'parcial','access_documentation_url':'https://pclima.inpe.br/?page_id=183','license':'não localizada nesta rodada; citação institucional requerida pela documentação','institutional_status':'público','owner_or_manager':'INPE / MCTI','academic_uses':'Analisar cenários e projeções climáticas para estudos de impactos, vulnerabilidade, adaptação e planejamento territorial.','limitations':'Projeções não são previsões meteorológicas; resultados dependem do modelo, experimento, cenário, resolução e período selecionados e devem preservar essas dimensões e a incerteza entre modelos.','academic_evidence_type':'documentação técnica oficial','academic_evidence_url':'https://pclima.inpe.br/?page_id=15','academic_evidence_note':'A documentação oficial descreve o portal, os conjuntos CMIP5/CMIP6, HELIX, BESM e Eta/CPTEC/INPE e sua finalidade para estudos de impactos, vulnerabilidade e adaptação.','verification_url':'https://pclima.inpe.br/?page_id=15','last_verified':TODAY}
assert set(new_source)==set(rf)
rr.append(new_source)

products=[
{'product_id':'DP000040','resource_id':'DR0004','product_name':'Inventário Nacional de Emissões e Remoções de GEE — série 1990–2022','product_acronym':'Inventário Nacional GEE','product_family':'Inventário Nacional de Gases de Efeito Estufa','product_kind':'dataset_series','product_description':'Série oficial brasileira de emissões antrópicas por fontes e remoções por sumidouros de gases de efeito estufa, organizada nos cinco setores do Inventário Nacional e atualizada no primeiro BTR/NIR para 1990–2022.','research_areas':'Climate mitigation | Greenhouse gas inventories | Public policy','keywords':'GEE | emissões | remoções | inventário nacional | LULUCF | Brasil','geographic_coverage':'Brasil','covers_brazil':'sim','spatial_support':'nacional | setores | categorias e gases conforme inventário','spatial_resolution':'nacional; desagregações dependem do produto complementar','temporal_coverage':'1990–2022 no primeiro BTR/NIR','temporal_resolution':'anual','update_frequency':'por ciclo oficial de inventário/transparência','product_status':'ativo','version_or_collection':'Primeiro BTR / Relatório Nacional de Inventário — 2024','enumeration_scope':'complete','product_page_url':'https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/cgcl/paginas/relatorios-bienais-de-transparencia-btrs','methodology_url':'https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/cgcl/paginas/relatorios-bienais-de-transparencia-btrs','primary_or_derived':'derivado','limitations':'Comparações entre edições devem considerar recálculos, mudanças metodológicas, incertezas e QA/QC documentados no inventário; não misturar estimativas de edições diferentes sem harmonização.','last_verified':TODAY},
{'product_id':'DP000041','resource_id':'DR0004','product_name':'Emissões e Remoções por Unidade Federativa — 1990–2022','product_acronym':'SIRENE UF','product_family':'Desagregação subnacional do Inventário Nacional de GEE','product_kind':'dataset_series','product_description':'Desagregação oficial das emissões e remoções do Inventário Nacional para as unidades federativas, cobrindo cinco setores e série histórica iniciada em 1990.','research_areas':'Climate mitigation | Territorial analysis | Public policy','keywords':'GEE | estados | unidade federativa | emissões | remoções | LULUCF','geographic_coverage':'27 unidades da federação do Brasil','covers_brazil':'sim','spatial_support':'unidade federativa | setor','spatial_resolution':'UF','temporal_coverage':'1990–2022 na nota metodológica vigente consultada','temporal_resolution':'anual','update_frequency':'por atualização oficial','product_status':'ativo','version_or_collection':'desagregação 1990–2022','enumeration_scope':'complete','product_page_url':'https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/sirene/publicacoes/emissoes-por-unidade-federativa','methodology_url':'https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/sirene/publicacoes/emissoes-por-unidade-federativa','primary_or_derived':'derivado','limitations':'A desagregação territorial deriva do Inventário Nacional e deve ser interpretada segundo a nota metodológica, categorias e regras de alocação aplicadas a cada setor.','last_verified':TODAY},
{'product_id':'DP000042','resource_id':'DR0004','product_name':'Fatores de Emissão de CO₂ do Sistema Interligado Nacional','product_acronym':'Fatores SIN','product_family':'SIRENE — fatores de emissão de eletricidade','product_kind':'dataset_series','product_description':'Séries oficiais de fatores de emissão de CO₂ da geração elétrica no Sistema Interligado Nacional, incluindo fator médio para inventários e fatores da margem de operação para aplicações metodológicas específicas.','research_areas':'Carbon accounting | Energy systems | Climate mitigation','keywords':'fator de emissão | CO2 | SIN | eletricidade | inventários corporativos | MDL','geographic_coverage':'Sistema Interligado Nacional — Brasil','covers_brazil':'sim','spatial_support':'sistema elétrico nacional | série temporal','spatial_resolution':'SIN','temporal_coverage':'arquivos históricos e ano-base 2026 disponíveis na página oficial','temporal_resolution':'mensal, diária ou horária conforme série e método','update_frequency':'periódica; arquivos por ano-base','product_status':'ativo','version_or_collection':'séries até 2026 verificadas','enumeration_scope':'family_level','product_page_url':'https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/sirene/dados-e-ferramentas/fatores-de-emissao','methodology_url':'https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/sirene/dados-e-ferramentas/fatores-de-emissao','primary_or_derived':'derivado','limitations':'Fator médio para inventários e margem de operação para MDL têm finalidades distintas e não são intercambiáveis; registrar método, ano-base e eventuais correções do arquivo usado.','last_verified':TODAY},
{'product_id':'DP000043','resource_id':'DR0003','product_name':'Índices e Indicadores de Risco Climático AdaptaBrasil','product_acronym':'AdaptaBrasil Risco','product_family':'Risco climático, ameaça, exposição e vulnerabilidade','product_kind':'indicator_family','product_description':'Sistema hierárquico de índices de risco de impacto climático e seus componentes de vulnerabilidade, exposição, ameaça, sensibilidade e capacidade adaptativa para setores estratégicos.','research_areas':'Climate adaptation | Socioecological systems | Public policy | Risk assessment','keywords':'risco climático | vulnerabilidade | exposição | ameaça | adaptação | indicadores','geographic_coverage':'Brasil; recortes territoriais variam por indicador','covers_brazil':'sim','spatial_support':'município e outros recortes territoriais conforme indicador','spatial_resolution':'varia conforme indicador','temporal_coverage':'presente e cenários futuros conforme indicador','temporal_resolution':'varia conforme indicador e cenário','update_frequency':'por atualização metodológica e de dados','product_status':'ativo','version_or_collection':'catálogo corrente de indicadores','enumeration_scope':'family_level','product_page_url':'https://adaptabrasil.mcti.gov.br/sobre/lista-de-indicadores','methodology_url':'https://adaptabrasil.mcti.gov.br/sobre/glossario','primary_or_derived':'derivado','limitations':'Índices agregam informações não diretamente comparáveis e não quantificam automaticamente perdas; dados brutos primários não estão integralmente disponíveis e cada indicador deve preservar documentação, fonte e cenário.','last_verified':TODAY},
{'product_id':'DP000044','resource_id':'DR0005','product_name':'Rede Observacional do CEMADEN','product_acronym':'Rede CEMADEN','product_family':'Dados observacionais para monitoramento de desastres naturais','product_kind':'dataset_series','product_description':'Dados observacionais das redes do CEMADEN, incluindo pluviômetros, estações hidrológicas, PCDs geotécnicas/Acqua e radares meteorológicos acessíveis pelo Mapa Interativo.','research_areas':'Hydrology | Meteorology | Natural hazards | Environmental monitoring','keywords':'pluviometria | hidrologia | radares | estações | desastres | CEMADEN','geographic_coverage':'Brasil conforme implantação das redes','covers_brazil':'sim','spatial_support':'estações e sensores | radar','spatial_resolution':'pontual ou cobertura de radar conforme equipamento','temporal_coverage':'pluviometria para download desde 2013; demais redes conforme implantação','temporal_resolution':'subdiária; varia por equipamento','update_frequency':'quase em tempo real para visualização; downloads históricos mensais conforme módulo','product_status':'ativo','version_or_collection':'Mapa Interativo / rede observacional corrente','enumeration_scope':'family_level','product_page_url':'https://mapainterativo.cemaden.gov.br/','methodology_url':'https://www.gov.br/cemaden/pt-br/paginas/historico-da-criacao-do-cemaden','primary_or_derived':'primário','limitations':'Dados da rede disponibilizados no Mapa Interativo podem não ter passado por tratamento e podem conter inconsistências; timestamps são registrados em UTC e condições de download variam por tipo de estação.','last_verified':TODAY},
{'product_id':'DP000045','resource_id':'DR0005','product_name':'Monitoramento de Secas e Índice Integrado de Seca','product_acronym':'IIS CEMADEN','product_family':'Monitoramento de secas e impactos','product_kind':'indicator_family','product_description':'Monitoramento periódico de condições de seca e impactos no Brasil, com Índice Integrado de Seca e análises para municípios e territórios vulneráveis.','research_areas':'Drought monitoring | Climate impacts | Hydrology | Socioecological systems','keywords':'seca | IIS | impactos | municípios | terras indígenas | assentamentos','geographic_coverage':'Brasil','covers_brazil':'sim','spatial_support':'município | terras indígenas | assentamentos e outros recortes de monitoramento','spatial_resolution':'territorial; varia conforme indicador','temporal_coverage':'série de monitoramento contínua; consultas recentes e histórico disponível','temporal_resolution':'mensal','update_frequency':'mensal','product_status':'ativo','version_or_collection':'monitoramento mensal corrente','enumeration_scope':'family_level','product_page_url':'https://www.gov.br/cemaden/pt-br/assuntos/monitoramento/impactos-seca/monitoramento-de-seca-para-o-brasil','methodology_url':'https://www.gov.br/cemaden/pt-br/assuntos/monitoramento/impactos-seca/monitoramento-de-seca-para-o-brasil','primary_or_derived':'derivado','limitations':'O IIS e demais classificações são indicadores derivados; interpretar classes segundo metodologia e mês de referência, sem converter diretamente categorias em perdas econômicas ou ecológicas.','last_verified':TODAY},
{'product_id':'DP000046','resource_id':'DR0002','product_name':'Catálogo de Camadas Geoespaciais IDE-SISEMA','product_acronym':'Catálogo IDE-SISEMA','product_family':'Metadados e camadas ambientais de Minas Gerais','product_kind':'federated_catalog','product_description':'Catálogo institucional de metadados e camadas geoespaciais ambientais e territoriais do SISEMA, com histórico de publicação e atualização por camada.','research_areas':'GIS | Environmental management | Territorial planning | Data infrastructure','keywords':'metadados | camadas | Minas Gerais | meio ambiente | geoinformação','geographic_coverage':'Minas Gerais','covers_brazil':'sim','spatial_support':'camadas vetoriais e raster | metadados','spatial_resolution':'herdada de cada camada','temporal_coverage':'varia conforme camada','temporal_resolution':'varia conforme camada','update_frequency':'contínua conforme publicação de camadas','product_status':'ativo','version_or_collection':'IDE-SISEMA 3.0','enumeration_scope':'external_index','product_page_url':'https://geoportal.meioambiente.mg.gov.br/','methodology_url':'https://geoportal.meioambiente.mg.gov.br/','primary_or_derived':'agregador','limitations':'Escala, data, licença, qualidade e método são propriedades da camada e do respectivo metadado; o catálogo não torna produtos heterogêneos metodologicamente equivalentes.','last_verified':TODAY},
{'product_id':'DP000047','resource_id':'DR0002','product_name':'Geoserviços OGC IDE-SISEMA','product_acronym':'IDE-SISEMA OGC','product_family':'Serviços interoperáveis de dados geoespaciais','product_kind':'data_service','product_description':'Serviços interoperáveis WMS, WFS, WCS e CSW para consumo das camadas e metadados publicados na IDE-SISEMA em aplicações SIG e sistemas externos.','research_areas':'Geospatial information science | Environmental data infrastructure | GIS','keywords':'WMS | WFS | WCS | CSW | OGC | geoserviços','geographic_coverage':'Minas Gerais; cobertura depende da camada','covers_brazil':'sim','spatial_support':'serviço geoespacial','spatial_resolution':'herdada da camada consumida','temporal_coverage':'varia conforme camada','temporal_resolution':'varia conforme camada','update_frequency':'contínua conforme atualização das camadas','product_status':'ativo','version_or_collection':'serviços OGC correntes','enumeration_scope':'complete','product_page_url':'https://geoportal.meioambiente.mg.gov.br/webservices','methodology_url':'https://geoportal.meioambiente.mg.gov.br/webservices','primary_or_derived':'serviço','limitations':'WMS fornece representação de mapa; WFS permite acesso vetorial e WCS a coberturas raster. O protocolo não altera precisão, escala, licença ou qualidade científica da camada de origem.','last_verified':TODAY},
{'product_id':'DP000048','resource_id':'DR0059','product_name':'Projeções Climáticas no Brasil — modelos globais e regionais','product_acronym':'PClima Projeções','product_family':'Projeções de mudanças climáticas para o Brasil','product_kind':'dataset_series','product_description':'Conjuntos de simulações e projeções climáticas para o Brasil provenientes de modelos globais e regionais, com seleção por modelo, experimento, cenário, período, variável e frequência.','research_areas':'Climate science | Climate impacts | Adaptation | Environmental modelling','keywords':'projeções climáticas | CMIP5 | CMIP6 | Eta | BESM | RCP | Brasil','geographic_coverage':'Brasil','covers_brazil':'sim','spatial_support':'grade de modelo | área | ponto conforme consulta','spatial_resolution':'varia por modelo e conjunto','temporal_coverage':'histórico e projeções até o final do século XXI conforme conjunto','temporal_resolution':'varia por frequência e variável','update_frequency':'por incorporação de conjuntos/modelos','product_status':'ativo','version_or_collection':'portal corrente — conjuntos CMIP5/CMIP6, HELIX, BESM e Eta/CPTEC/INPE','enumeration_scope':'family_level','product_page_url':'https://pclima.inpe.br/analise/','methodology_url':'https://pclima.inpe.br/?page_id=183','primary_or_derived':'derivado','limitations':'Projeções dependem de cenários e modelos e não são previsões meteorológicas; análises devem considerar ensemble, dispersão entre experimentos, resolução espacial e período de referência.','last_verified':TODAY}
]
for x in products: assert set(x)==set(pf)
pr.extend(products)

dists=[
('DD000048','DP000040','Inventário Nacional GEE — BTR/NIR','https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/cgcl/paginas/relatorios-bienais-de-transparencia-btrs','PDF | tabelas e anexos conforme publicação','HTTP web/download','navegador | planilha conforme anexo','sim','não','publicação oficial','conteúdo gov.br; verificar licença do arquivo específico','sim','nacional | setor | gás | categoria','Série 1990–2022 no primeiro BTR/NIR.'),
('DD000049','DP000041','SIRENE — Emissões por UF','https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/sirene/publicacoes/emissoes-por-unidade-federativa','painel web | publicação | tabelas','HTTP web/download','navegador | planilha','sim','não','acesso público','conteúdo gov.br; verificar arquivo específico','sim','UF | setor | ano','Nota metodológica vigente cobre 1990–2022.'),
('DD000050','DP000042','SIRENE — Fatores de emissão SIN','https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/sirene/dados-e-ferramentas/fatores-de-emissao','XLSX | notas técnicas','HTTP download','planilha | script','sim','não','acesso público','CC BY-ND 3.0 informado no conteúdo gov.br consultado','sim','ano-base | mês/dia/hora conforme método','Há arquivos corrigidos e ano-base 2026; preservar método e versão.'),
('DD000051','DP000043','AdaptaBrasil — consulta e download de indicadores','https://adaptabrasil.mcti.gov.br/sobre/lista-de-indicadores','JSON | download estruturado | visualização web','HTTP web | microserviços JSON','navegador | script Python','sim','não','consulta pública; detalhes de API conforme documentação','CC BY-SA; versão não especificada na página fonte canônica','sim','indicador | território | cenário','FAQ oficial confirma download de todos os dados e microserviços JSON; dados brutos primários não estão integralmente disponíveis.'),
('DD000052','DP000044','CEMADEN — dados pluviométricos','https://mapainterativo.cemaden.gov.br/','arquivo de dados mensal','HTTP download','navegador | planilha | script','sim','parcial','download por UF/município, mês e ano; confirmação de segurança','uso não comercial e atribuição CEMADEN conforme notas institucionais','sim','UF | município | estação | mês','Pluviometria disponível para download desde 2013; registros em UTC.'),
('DD000053','DP000044','CEMADEN — PCDs hidrológicas/geotécnicas/Acqua e radares','https://mapainterativo.cemaden.gov.br/','arquivos mensais e produtos de radar conforme módulo','HTTP download','navegador | SIG','parcial','parcial','alguns downloads solicitam nome/e-mail e envio de link','uso não comercial e atribuição CEMADEN conforme notas institucionais','sim','UF | município | equipamento | período','Condições e disponibilidade variam por rede/equipamento.'),
('DD000054','DP000045','CEMADEN — monitoramento mensal de secas/IIS','https://www.gov.br/cemaden/pt-br/assuntos/monitoramento/impactos-seca/monitoramento-de-seca-para-o-brasil','mapas | tabelas | download IIS | boletim','HTTP web/download','navegador | SIG | planilha','sim','não','acesso público','atribuição CEMADEN requerida; restrições institucionais podem se aplicar a reprodução','sim','município | território vulnerável | mês','Boletins mensais e mapa interativo; preservar mês e método do índice.'),
('DD000055','DP000046','IDE-SISEMA — catálogo de metadados','https://geoportal.meioambiente.mg.gov.br/','metadados web | links de download','HTTP web | CSW','navegador | cliente CSW','sim','não','consulta pública','varia conforme camada','sim','camada | tema | metadado','Metadados registram publicação e atualização mais recente das camadas.'),
('DD000056','DP000047','IDE-SISEMA — WMS/WFS/WCS','https://geoserver.meioambiente.mg.gov.br/ows','PNG/JPEG/GIF via WMS | Shapefile/GML/GeoJSON via WFS | raster via WCS','WMS | WFS | WCS','QGIS | ArcGIS | cliente OGC','sim','não','serviços OGC públicos','varia conforme camada','sim','camada | bbox | filtros suportados pelo serviço','Endpoint oficial documentado pelo Geoportal.'),
('DD000057','DP000047','IDE-SISEMA — CSW de metadados','https://idesisema.meioambiente.mg.gov.br/geonetwork/srv/por/csw?service=CSW&version=2.0.2&request=GetCapabilities','XML/metadados','CSW','cliente OGC | navegador | script','sim','não','serviço público','varia conforme metadado/recurso','sim','catálogo | consulta CSW','Endpoint CSW 2.0.2 documentado pelo Geoportal.'),
('DD000058','DP000048','PClima — visualizador e download','https://pclima.inpe.br/analise/','dados de projeção | mapas | PNG; formato de dados selecionável','HTTP web/download','navegador | análise climática','sim','não','consulta e download públicos pela interface','licença específica não localizada; citação institucional requerida','sim','modelo | cenário | variável | período | área/ponto','Seleção explícita de conjunto, modelo, experimento, cenário, frequência e variável.'),
('DD000059','DP000048','PClima — API','https://pclima.inpe.br/analise/API/','formato selecionável pela API','API | HTTPS','script | cliente HTTP','sim','sim','API usa token/cadastro conforme interface','licença específica não localizada; citação institucional requerida','sim','modelo | cenário | variável | tempo | bbox/ponto','Interface permite gerar URL parametrizada; preservar parâmetros usados.')]
for vals in dists:
    x=dict(zip(df,['distribution_id','product_id','distribution_name','access_url','format','access_protocol','access_tool','free_download','authentication_required','access_conditions','license','provider_attribution_required','subset_support','notes','last_verified'])) if False else None
# build by header order
for vals in dists:
    base={'distribution_id':vals[0],'product_id':vals[1],'distribution_name':vals[2],'access_url':vals[3],'format':vals[4],'access_protocol':vals[5],'access_tool':vals[6],'free_download':vals[7],'authentication_required':vals[8],'access_conditions':vals[9],'license':vals[10],'provider_attribution_required':vals[11],'subset_support':vals[12],'notes':vals[13],'last_verified':TODAY}
    assert set(base)==set(df); dr.append(base)

regp=ROOT/'data/brazil_scope_priorities.json'; reg=json.loads(regp.read_text(encoding='utf-8'))
p0=next(x for x in reg['tiers'] if x['priority_tier']=='P0')['resource_ids']
assert 'DR0059' not in p0; p0.append('DR0059'); reg['reviewed_at']=TODAY

assert len({r['resource_id'] for r in rr})==59
assert len({r['product_id'] for r in pr})==48
assert len({r['distribution_id'] for r in dr})==59
assert all(p['resource_id'] in {r['resource_id'] for r in rr} for p in pr)
assert all(d['product_id'] in {p['product_id'] for p in pr} for d in dr)
write(ROOT/'data/data_resources.csv',rf,rr); write(ROOT/'data/data_products.csv',pf,pr); write(ROOT/'data/product_distributions.csv',df,dr)
regp.write_text(json.dumps(reg,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('OK: 59 fontes, 48 produtos, 59 distribuições')
