#!/usr/bin/env python3
import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERIFIED = "2026-08-15"

RESOURCE = {
"resource_id":"DR0074","resource_name":"Informações Ambientais — Mapas e Produtos Cartográficos — IBGE","acronym":"Mapas Ambientais IBGE","official_identity":"Tema institucional de mapas e produtos cartográficos ambientais do IBGE","description":"Conjunto institucional de mapas e produtos cartográficos sobre recursos naturais e meio ambiente do Brasil, incluindo relevo, vegetação, solos, clima e morfologia continental e oceânica.","homepage_url":"https://www.ibge.gov.br/geociencias/cartas-e-mapas/informacoes-ambientais.html","data_access_url":"https://www.ibge.gov.br/geociencias/cartas-e-mapas/informacoes-ambientais.html","research_areas":"Ciências Ambientais e Ecologia | Geociências, Solos e Geografia Física | Sensoriamento Remoto e Geoinformação","keywords":"mapas ambientais | relevo | vegetação | solos | clima | morfologia | IBGE","data_product_types":"mapas | bases espaciais | vetores | publicações cartográficas","data_formats":"PDF | vetores geoespaciais | ZIP | formatos variáveis conforme produto","visualization_types":"mapas | bases espaciais","geographic_coverage":"Brasil; cobertura marinha em produtos específicos","covers_brazil":"sim","spatial_resolution":"varia por produto; escalas de referência devem ser preservadas","temporal_coverage":"edições históricas e produtos de referência; varia por produto","temporal_resolution":"por edição cartográfica","data_sources":"levantamentos ambientais do IBGE | sensoriamento remoto | cartografia temática | modelos topográficos e batimétricos conforme produto","free_download":"sim","access_conditions":"consulta e downloads públicos nas páginas oficiais dos produtos","programmatic_access":"não","access_protocols":"HTTP download | HTTPS web","authentication_required":"não","access_documentation_url":"https://www.ibge.gov.br/geociencias/cartas-e-mapas/informacoes-ambientais.html","license":"licença específica dos arquivos deve ser verificada por produto; observar termos de uso do IBGE","institutional_status":"público","owner_or_manager":"IBGE","academic_uses":"Cartografia temática, síntese ambiental, ensino, geografia física, ecologia, planejamento territorial e análises históricas de referência.","limitations":"Os produtos têm escalas, anos, métodos e finalidades distintas; mapas históricos de pequena escala não representam condição ambiental atual nem substituem bases de maior detalhe.","academic_evidence_type":"documentação técnica oficial","academic_evidence_url":"https://www.ibge.gov.br/geociencias/cartas-e-mapas/informacoes-ambientais.html","academic_evidence_note":"A página oficial reúne como produtos próprios mapas ambientais de relevo, vegetação, morfologia continental e oceânica, clima e solos, além de outras séries.","verification_url":"https://www.ibge.gov.br/geociencias/cartas-e-mapas/informacoes-ambientais.html","last_verified":VERIFIED}

PRODUCTS = [
{"product_id":"DP000111","resource_id":"DR0057","product_name":"Biomas e Sistema Costeiro-Marinho do Brasil — revisão 2025","product_acronym":"Biomas IBGE 2025","product_family":"Biomas e Sistema Costeiro-Marinho do Brasil","product_kind":"map_layer_collection","product_description":"Edição 2025 dos limites oficiais dos seis biomas brasileiros e do Sistema Costeiro-Marinho, incorporando a primeira revisão de limites compatível com 1:250.000 em trechos da interface Mata Atlântica–Cerrado em Minas Gerais e São Paulo.","research_areas":"Biogeography | Ecology | Environmental mapping | Territorial analysis","keywords":"biomas | sistema costeiro-marinho | limites | revisão 2025 | Mata Atlântica | Cerrado | IBGE","geographic_coverage":"Brasil e Sistema Costeiro-Marinho; revisão 2025 concentrada em trechos MG/SP","covers_brazil":"sim","spatial_support":"polígonos vetoriais | mapa","spatial_resolution":"compatível com escala 1:250.000","temporal_coverage":"edição 2025; revisão divulgada em 2025","temporal_resolution":"edição cartográfica","update_frequency":"por revisão/edição","product_status":"ativo","version_or_collection":"2025 — primeira revisão de limites","enumeration_scope":"complete","product_page_url":"https://www.ibge.gov.br/geociencias/informacoes-ambientais/estudos-ambientais/15842-biomas.html?edicao=45164","methodology_url":"https://www.ibge.gov.br/geociencias/informacoes-ambientais/estudos-ambientais/15842-biomas.html?edicao=45164","primary_or_derived":"derivado","limitations":"Os limites são referenciais cartográficos e podem ser revisados. A revisão 2025 não deve ser interpretada como mudança temporal do bioma inteiro; ela ajusta limites em trechos específicos com base em evidência ambiental e cartográfica.","last_verified":VERIFIED},
{"product_id":"DP000112","resource_id":"DR0070","product_name":"Áreas Protegidas na Amazônia Legal — retrato ambiental e estatístico 2025","product_acronym":"Áreas Protegidas Amazônia Legal 2025","product_family":"Estrutura Territorial — Áreas Protegidas","product_kind":"indicator_family","product_description":"Síntese ambiental e estatística das Unidades de Conservação, Terras Indígenas e Territórios Quilombolas oficialmente delimitados na Amazônia Legal, integrando recortes territoriais de 2025 e características ambientais e sociodemográficas.","research_areas":"Conservation | Socioecological systems | Territorial analysis | Environmental statistics","keywords":"áreas protegidas | Amazônia Legal | unidades de conservação | terras indígenas | territórios quilombolas | 2025","geographic_coverage":"Amazônia Legal brasileira","covers_brazil":"parcial","spatial_support":"áreas protegidas | Amazônia Legal | unidades territoriais e estatísticas","spatial_resolution":"recortes oficiais das instituições competentes; precisão varia por cadastro de origem","temporal_coverage":"recortes territoriais de 2025; estatísticas e referências variam conforme variável","temporal_resolution":"snapshot integrado","update_frequency":"por edição","product_status":"ativo","version_or_collection":"publicação 2025 — divulgada em 12/11/2025","enumeration_scope":"complete","product_page_url":"https://www.ibge.gov.br/geociencias/cartas-e-mapas/mapas-regionais/44874-areas-protegidas-na-amazonia-legal.html?lang=pt-BR","methodology_url":"https://www.ibge.gov.br/geociencias/cartas-e-mapas/mapas-regionais/44874-areas-protegidas-na-amazonia-legal.html?lang=pt-BR","primary_or_derived":"derivado","limitations":"Integra recortes produzidos por CNUC/MMA, Funai e Incra/órgãos estaduais com referências próprias. O percentual de área protegida não mede por si só efetividade de conservação, integridade ecológica ou segurança territorial.","last_verified":VERIFIED},
{"product_id":"DP000113","resource_id":"DR0070","product_name":"Censo Demográfico 2022 — população e domicílios em Unidades de Conservação","product_acronym":"Censo 2022 UCs","product_family":"Estrutura Territorial — Unidades de Conservação","product_kind":"dataset","product_description":"Resultados do universo do Censo Demográfico 2022 para pessoas residentes e domicílios localizados em Unidades de Conservação, com desagregações territoriais, categorias de manejo e grupos populacionais específicos.","research_areas":"Population geography | Conservation | Socioecological systems | Environmental justice","keywords":"Censo 2022 | unidades de conservação | população | domicílios | indígenas | quilombolas | SNUC","geographic_coverage":"Brasil; Unidades de Conservação e recortes nacionais, regionais, estaduais e municipais","covers_brazil":"sim","spatial_support":"Unidade de Conservação | município | Unidade da Federação | Brasil | outros recortes de divulgação","spatial_resolution":"recortes territoriais e UCs; arquivos vetoriais também disponibilizados","temporal_coverage":"Censo Demográfico 2022; publicação temática 2025","temporal_resolution":"censo decenal / edição temática","update_frequency":"decenal ou por divulgação temática","product_status":"ativo","version_or_collection":"Censo Demográfico 2022 — resultados do universo em UCs","enumeration_scope":"complete","product_page_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/estrutura-territorial/43972-unidades-de-conservacao.html","methodology_url":"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/estrutura-territorial/43972-unidades-de-conservacao.html?=&t=sobre","primary_or_derived":"derivado","limitations":"As estatísticas descrevem população e domicílios recenseados nos recortes de UCs usados na divulgação; não medem efetividade de manejo, pressão ambiental ou condição ecológica. A própria publicação recomenda cautela para informações de alfabetização de 5–14 anos dos grupos específicos.","last_verified":VERIFIED},
{"product_id":"DP000114","resource_id":"DR0074","product_name":"Unidades de Relevo do Brasil 1:5.000.000 — 2006","product_acronym":"Relevo Brasil 2006","product_family":"Mapas Ambientais Série Brasil","product_kind":"map_layer_collection","product_description":"Mapa sintético do relevo brasileiro em 1:5.000.000, classificando Domínios Morfoestruturais, Regiões Geomorfológicas, Unidades de Relevo e Modelados; a edição de 2006 identifica 167 unidades de relevo.","research_areas":"Geomorphology | Physical geography | Environmental mapping","keywords":"relevo | geomorfologia | domínios morfoestruturais | modelados | 1:5.000.000 | 2006","geographic_coverage":"Brasil","covers_brazil":"sim","spatial_support":"unidades geomorfológicas | mapa | base espacial","spatial_resolution":"escala 1:5.000.000","temporal_coverage":"edição 2006","temporal_resolution":"edição cartográfica","update_frequency":"por edição; sem periodicidade inferida","product_status":"arquivado","version_or_collection":"2006 — 2ª edição","enumeration_scope":"complete","product_page_url":"https://www.ibge.gov.br/geociencias/informacoes-ambientais/geomorfologia/15827-unidades-de-relevo.html","methodology_url":"https://www.ibge.gov.br/geociencias/informacoes-ambientais/geomorfologia/15827-unidades-de-relevo.html","primary_or_derived":"derivado","limitations":"Produto histórico e de pequena escala, adequado a síntese nacional. Não representa detalhamento geomorfológico local nem substitui mapeamentos 1:250.000 ou levantamentos posteriores.","last_verified":VERIFIED},
{"product_id":"DP000115","resource_id":"DR0074","product_name":"Vegetação Brasileira 1:5.000.000 — 2004","product_acronym":"Vegetação Brasil 2004","product_family":"Mapas Ambientais Série Brasil","product_kind":"map_layer_collection","product_description":"Terceira versão do Mapa de Vegetação do Brasil, em 1:5.000.000, reconstruindo a vegetação original e representando formações florestais e campestres, formações pioneiras, áreas de tensão ecológica, refúgios, remanescentes e antropismos.","research_areas":"Vegetation science | Biogeography | Ecology | Environmental mapping","keywords":"vegetação | fitofisionomia | vegetação original | remanescentes | antropismos | 1:5.000.000 | 2004","geographic_coverage":"Brasil","covers_brazil":"sim","spatial_support":"unidades de vegetação | mapa | base espacial","spatial_resolution":"escala 1:5.000.000","temporal_coverage":"edição 2004; reconstrução da vegetação original com informação de remanescentes e antropismos da edição","temporal_resolution":"edição cartográfica","update_frequency":"por edição; série histórica 1988, 1993 e 2004","product_status":"arquivado","version_or_collection":"2004 — terceira versão","enumeration_scope":"complete","product_page_url":"https://www.ibge.gov.br/geociencias/informacoes-ambientais/vegetacao/10872-vegetacao.html?lang=pt-BR","methodology_url":"https://www.ibge.gov.br/geociencias/informacoes-ambientais/vegetacao/10872-vegetacao.html?lang=pt-BR","primary_or_derived":"derivado","limitations":"Mapa histórico de síntese; a representação de vegetação original, remanescentes e antropismos não equivale a um produto contemporâneo de cobertura e uso da terra. Preservar edição e legenda.","last_verified":VERIFIED},
{"product_id":"DP000116","resource_id":"DR0074","product_name":"Solos do Brasil 1:5.000.000 — mapa 2001 e base espacial 2006","product_acronym":"Solos Brasil 1:5M","product_family":"Mapas Ambientais Série Brasil","product_kind":"map_layer_collection","product_description":"Produto cartográfico nacional de solos em 1:5.000.000, adotando nomenclatura e especificações do Sistema Brasileiro de Classificação de Solos; a página oficial disponibiliza mapa de 2001 e base de dados espacial de 2006.","research_areas":"Soil science | Physical geography | Environmental mapping","keywords":"solos | pedologia | SiBCS | 1:5.000.000 | mapa 2001 | base 2006","geographic_coverage":"Brasil","covers_brazil":"sim","spatial_support":"unidades de solos | mapa | base espacial","spatial_resolution":"escala 1:5.000.000","temporal_coverage":"mapa 2001; base de dados espacial 2006","temporal_resolution":"edição cartográfica","update_frequency":"por edição; sem periodicidade inferida","product_status":"arquivado","version_or_collection":"mapa 2001 | base espacial 2006","enumeration_scope":"complete","product_page_url":"https://www.ibge.gov.br/geociencias/informacoes-ambientais/pedologia/15829-solos.html?lang=pt-BR","methodology_url":"https://www.ibge.gov.br/geociencias/informacoes-ambientais/pedologia/15829-solos.html?lang=pt-BR","primary_or_derived":"derivado","limitations":"Produto de síntese nacional e histórico. A classificação deve ser interpretada segundo a edição do SiBCS usada à época e não substitui levantamentos pedológicos de maior escala/detalhe.","last_verified":VERIFIED},
{"product_id":"DP000117","resource_id":"DR0074","product_name":"Clima do Brasil 1:5.000.000 — 2002","product_acronym":"Clima Brasil 2002","product_family":"Mapas Ambientais Série Brasil","product_kind":"map_layer_collection","product_description":"Mapa nacional de clima em 1:5.000.000 que representa zonas climáticas agrupadas por temperatura e umidade e tipos climáticos como quente, subquente e classes mesotérmicas.","research_areas":"Climatology | Physical geography | Environmental mapping","keywords":"clima | zonas climáticas | temperatura | umidade | 1:5.000.000 | 2002","geographic_coverage":"Brasil","covers_brazil":"sim","spatial_support":"zonas e tipos climáticos | mapa | vetores","spatial_resolution":"escala 1:5.000.000","temporal_coverage":"edição 2002","temporal_resolution":"regionalização climática; não série observacional","update_frequency":"por edição; sem periodicidade inferida","product_status":"arquivado","version_or_collection":"2002","enumeration_scope":"complete","product_page_url":"https://www.ibge.gov.br/geociencias/informacoes-ambientais/climatologia/15817-clima.html","methodology_url":"https://www.ibge.gov.br/geociencias/informacoes-ambientais/climatologia/15817-clima.html","primary_or_derived":"derivado","limitations":"É regionalização climática histórica de pequena escala, não série meteorológica nem climatologia atualizada. Não usar como substituto de normais climatológicas recentes ou dados de estação/modelo.","last_verified":VERIFIED},
{"product_id":"DP000118","resource_id":"DR0074","product_name":"Morfologia Continental e do Fundo dos Oceanos — 1:6.500.000 — 2004","product_acronym":"Morfologia Brasil 2004","product_family":"Mapas Ambientais Série Brasil","product_kind":"map_layer_collection","product_description":"Mapa de síntese dos padrões morfológicos continentais e marinhos do Brasil, elaborado pela combinação de imagens de satélite e modelos da topografia continental e do fundo oceânico.","research_areas":"Geomorphology | Marine geoscience | Physical geography | Environmental mapping","keywords":"morfologia | topografia | fundo oceânico | relevo | satélite | 1:6.500.000 | 2004","geographic_coverage":"Brasil e áreas oceânicas representadas no produto","covers_brazil":"sim","spatial_support":"superfície continental e marinha | mapa","spatial_resolution":"escala 1:6.500.000","temporal_coverage":"edição 2004","temporal_resolution":"edição cartográfica","update_frequency":"por edição; sem periodicidade inferida","product_status":"arquivado","version_or_collection":"2004","enumeration_scope":"complete","product_page_url":"https://www.ibge.gov.br/geociencias/cartas-e-mapas/informacoes-ambientais/15953-morfologia-continental-e-do-fundo-dos-oceanos.html","methodology_url":"https://www.ibge.gov.br/geociencias/cartas-e-mapas/informacoes-ambientais/15953-morfologia-continental-e-do-fundo-dos-oceanos.html","primary_or_derived":"derivado","limitations":"Produto histórico de síntese e pequena escala; padrões morfológicos derivados não equivalem a batimetria/topografia de alta resolução nem a levantamento geofísico local.","last_verified":VERIFIED}
]

DISTS = [
("DD000127","DP000111","Biomas 2025 — vetores, mapa e notas metodológicas","https://www.ibge.gov.br/geociencias/informacoes-ambientais/estudos-ambientais/15842-biomas.html?edicao=45164","SHP | XLSX | PDF","HTTP download | web","navegador web","sim","não","consulta e downloads públicos pela edição 2025","licença específica não localizada nesta auditoria; observar termos do IBGE","desconhecido","por arquivo/edição","A edição 2025 disponibiliza vetores, mapa e documentação; registrar a edição e não misturar limites de anos diferentes."),
("DD000128","DP000112","Áreas Protegidas na Amazônia Legal — publicação e materiais 2025","https://www.ibge.gov.br/geociencias/cartas-e-mapas/mapas-regionais/44874-areas-protegidas-na-amazonia-legal.html?lang=pt-BR","publicação | tabelas | mapas | materiais associados","HTTP download | web","navegador web","sim","não","consulta pública pela página oficial","licença específica dos arquivos não localizada; observar termos do IBGE e fontes dos recortes","desconhecido","por componente da publicação","Recortes de UC, TI e territórios quilombolas são produzidos por instituições distintas e devem manter sua proveniência."),
("DD000129","DP000113","Unidades de Conservação — SIDRA, tabelas, vetores e publicação Censo 2022","https://www.ibge.gov.br/geociencias/organizacao-do-territorio/estrutura-territorial/43972-unidades-de-conservacao.html","XLSX | ODS | SHP | PDF | JPG | SIDRA","HTTP download | SIDRA | web","navegador web | SIDRA","sim","não","consulta pública; múltiplos pontos de acesso oficiais","licença específica dos arquivos não localizada nesta auditoria; observar termos do IBGE","desconhecido","por tabela, UC, UF e outros recortes","Produto combina estatísticas censitárias com recortes de UCs; não interpretar atributos populacionais como indicadores diretos de condição ecológica."),
("DD000130","DP000114","Unidades de Relevo 2006 — base espacial e mapa","https://www.ibge.gov.br/geociencias/informacoes-ambientais/geomorfologia/15827-unidades-de-relevo.html","base espacial | mapa | downloads","HTTP download | web","navegador web","sim","não","downloads públicos pela página oficial","licença específica dos arquivos não localizada nesta auditoria; observar termos do IBGE","desconhecido","por arquivo","Escala 1:5.000.000 e edição 2006; uso adequado a síntese nacional, não detalhamento local."),
("DD000131","DP000115","Vegetação Brasileira 2004 — mapa e base espacial","https://www.ibge.gov.br/geociencias/informacoes-ambientais/vegetacao/10872-vegetacao.html?lang=pt-BR","mapa | base espacial | downloads","HTTP download | web","navegador web","sim","não","downloads públicos pela página oficial","licença específica dos arquivos não localizada nesta auditoria; observar termos do IBGE","desconhecido","por arquivo","Produto histórico em 1:5.000.000; preservar legenda e edição e não confundir com cobertura/uso contemporâneo."),
("DD000132","DP000116","Solos 1:5.000.000 — mapa 2001 e base espacial 2006","https://www.ibge.gov.br/geociencias/informacoes-ambientais/pedologia/15829-solos.html?lang=pt-BR","mapa | base espacial | downloads","HTTP download | web","navegador web","sim","não","downloads públicos pela página oficial","licença específica dos arquivos não localizada nesta auditoria; observar termos do IBGE","desconhecido","por arquivo/edição","A página distingue mapa 2001 e base espacial 2006; não colapsar as duas referências temporais em uma única data."),
("DD000133","DP000117","Clima do Brasil 2002 — PDF e vetores","https://www.ibge.gov.br/geociencias/informacoes-ambientais/climatologia/15817-clima.html?=&t=acesso-ao-produto","PDF | vetores ZIP","HTTP download | web","navegador web","sim","não","downloads públicos pela página oficial","licença específica dos arquivos não localizada nesta auditoria; observar termos do IBGE","desconhecido","por arquivo","Regionalização climática de 2002; não equivale a séries de estação, reanálise ou normais climatológicas atuais."),
("DD000134","DP000118","Morfologia Continental e do Fundo dos Oceanos 2004 — downloads","https://www.ibge.gov.br/geociencias/cartas-e-mapas/informacoes-ambientais/15953-morfologia-continental-e-do-fundo-dos-oceanos.html","mapa e downloads; formatos específicos devem ser verificados no arquivo","HTTP download | web","navegador web","sim","não","downloads públicos pela página oficial","licença específica dos arquivos não localizada nesta auditoria; observar termos do IBGE","desconhecido","por arquivo","Produto histórico em 1:6.500.000; não inferir resolução topográfica ou batimétrica a partir da escala de representação.")
]


def read_ids(path, field):
    with path.open(encoding="utf-8", newline="") as f:
        return {r[field] for r in csv.DictReader(f)}

def append_dicts(path, rows):
    with path.open(encoding="utf-8", newline="") as f:
        header = next(csv.reader(f))
    with path.open("a", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=header, lineterminator="\n")
        for row in rows:
            missing = set(header)-set(row)
            extra = set(row)-set(header)
            if missing or extra:
                raise SystemExit(f"schema mismatch {path}: missing={missing} extra={extra}")
            w.writerow(row)

def main():
    resources = ROOT/"data/data_resources.csv"
    products = ROOT/"data/data_products.csv"
    dists = ROOT/"data/product_distributions.csv"
    rids = read_ids(resources,"resource_id")
    pids = read_ids(products,"product_id")
    dids = read_ids(dists,"distribution_id")
    if RESOURCE["resource_id"] in rids:
        raise SystemExit("DR0074 already exists")
    for p in PRODUCTS:
        if p["product_id"] in pids:
            raise SystemExit(f"duplicate product id {p['product_id']}")
        if p["resource_id"] not in rids and p["resource_id"] != RESOURCE["resource_id"]:
            raise SystemExit(f"missing resource {p['resource_id']}")
    append_dicts(resources,[RESOURCE])
    append_dicts(products,PRODUCTS)
    dist_header = ["distribution_id","product_id","distribution_name","access_url","format","access_protocol","access_tool","free_download","authentication_required","access_conditions","license","provider_attribution_required","subset_support","notes","last_verified"]
    dist_rows=[]
    for x in DISTS:
        if x[0] in dids: raise SystemExit(f"duplicate distribution id {x[0]}")
        dist_rows.append(dict(zip(dist_header, list(x)+[VERIFIED])))
    append_dicts(dists,dist_rows)
    print(f"appended 1 resource, {len(PRODUCTS)} products, {len(dist_rows)} distributions")

if __name__ == "__main__": main()
