import csv, json
from pathlib import Path
from datetime import datetime, timezone

today = datetime.now(timezone.utc).date().isoformat()
R=Path('data/data_resources.csv'); P=Path('data/data_products.csv'); D=Path('data/product_distributions.csv'); B=Path('data/brazil_scope_priorities.json')

def read(path):
    with path.open(encoding='utf-8', newline='') as f:
        r=csv.DictReader(f); return r.fieldnames, list(r)
def append(path, rows):
    fields,_=read(path)
    with path.open('a',encoding='utf-8',newline='') as f:
        w=csv.DictWriter(f,fieldnames=fields,lineterminator='\n')
        for row in rows: w.writerow({k:row.get(k,'') for k in fields})

_,rs=read(R); _,ps=read(P); _,ds=read(D)
rids={x['resource_id'] for x in rs}; pids={x['product_id'] for x in ps}; dids={x['distribution_id'] for x in ds}; urls={x['product_page_url'] for x in ps if x.get('product_page_url')}

source={'resource_id':'DR0118','resource_name':'Instituto Nacional de Meteorologia — dados, estações e climatologia','acronym':'INMET','official_identity':'Instituto Nacional de Meteorologia — INMET / Ministério da Agricultura e Pecuária','description':'Fonte meteorológica oficial brasileira para observações de estações, séries históricas, catálogos de estações, normais climatológicas e avisos meteorológicos.','homepage_url':'https://portal.inmet.gov.br/','data_access_url':'https://portal.inmet.gov.br/dadoshistoricos','research_areas':'Clima e Ciências Atmosféricas | Ciências Ambientais e Ecologia | Infraestruturas e Ciência de Dados','keywords':'INMET | meteorologia | clima | estações meteorológicas | séries históricas | normais climatológicas | avisos meteorológicos','data_product_types':'observações meteorológicas | séries históricas | climatologia | catálogos de estações | alertas','data_formats':'CSV | ZIP | tabelas web | mapas; varia por produto','visualization_types':'tabelas | mapas | gráficos | portal web','geographic_coverage':'Brasil; rede de estações e produtos nacionais conforme o serviço','covers_brazil':'sim','spatial_resolution':'pontual por estação ou agregada/cartográfica conforme produto','temporal_coverage':'séries históricas e produtos correntes; varia por produto','temporal_resolution':'horária a climatológica conforme produto','data_sources':'estações meteorológicas automáticas e convencionais | processamento climatológico do INMET | previsão e análise meteorológica institucional','free_download':'parcial','access_conditions':'acesso público em produtos selecionados; BDMEP pode exigir fluxo próprio de consulta; observar metadados e período de cada produto','programmatic_access':'desconhecido','access_protocols':'HTTPS download | consulta web','authentication_required':'parcial','access_documentation_url':'https://portal.inmet.gov.br/paginas/estacoes','license':'não localizada de forma inequívoca no nível geral; verificar termos do produto/arquivo','institutional_status':'público','owner_or_manager':'Instituto Nacional de Meteorologia — INMET / Ministério da Agricultura e Pecuária','academic_uses':'Climatologia, meteorologia, extremos climáticos, agrometeorologia, ecologia, hidrologia, risco de desastres e validação de produtos de sensoriamento remoto.','limitations':'Cobertura espacial e continuidade variam por estação e período. Observações de estação, normais climatológicas, previsões e avisos são objetos distintos e não devem ser tratados como equivalentes; registrar estação, período, unidade e versão do produto.','academic_evidence_type':'documentação técnica oficial','academic_evidence_url':'https://portal.inmet.gov.br/normais','academic_evidence_note':'O portal oficial documenta séries históricas, estações automáticas e convencionais, normais climatológicas e demais produtos meteorológicos do INMET.','verification_url':'https://portal.inmet.gov.br/paginas/estacoes','last_verified':today}

products=[
{'product_id':'DP000522','resource_id':'DR0118','product_name':'INMET — Dados Históricos Anuais de Estações Automáticas','product_acronym':'INMET Históricos Automáticas','product_family':'observações meteorológicas históricas','product_kind':'dataset_series','product_description':'Arquivos anuais de observações das estações meteorológicas automáticas do INMET, organizados por ano e estação.','research_areas':'Clima e Ciências Atmosféricas | Ciências Ambientais e Ecologia | Infraestruturas e Ciência de Dados','keywords':'INMET | estações automáticas | dados históricos | temperatura | precipitação | umidade | vento | radiação','geographic_coverage':'Brasil — estações automáticas do INMET','covers_brazil':'sim','spatial_support':'ponto de estação meteorológica','spatial_resolution':'pontual; representatividade espacial depende da estação e variável','temporal_coverage':'2000–2026 no portal auditado; 2026 parcial e sujeito a atualização','temporal_resolution':'horária nas séries automáticas','update_frequency':'anual/contínua conforme consolidação do portal','product_status':'ativo','version_or_collection':'portal de Dados Históricos Anuais, consultado em 2026','enumeration_scope':'complete','product_page_url':'https://portal.inmet.gov.br/dadoshistoricos','methodology_url':'https://portal.inmet.gov.br/paginas/estacoes','primary_or_derived':'primário','limitations':'Cobertura, falhas, manutenção e disponibilidade variam por estação e ano. O arquivo anual não implica série completa ou homogênea em todas as estações; 2026 é parcial no estado auditado.','last_verified':today},
{'product_id':'DP000523','resource_id':'DR0118','product_name':'INMET — Estações Automáticas — observações correntes','product_acronym':'INMET Automáticas','product_family':'observações meteorológicas operacionais','product_kind':'data_service','product_description':'Serviço de observações meteorológicas das estações automáticas do INMET, com atualização de hora em hora e janela operacional recente.','research_areas':'Clima e Ciências Atmosféricas | Ciências Ambientais e Ecologia | Infraestruturas e Ciência de Dados','keywords':'INMET | estação automática | observação horária | tempo | temperatura | umidade | chuva | vento','geographic_coverage':'Brasil — rede de estações automáticas do INMET','covers_brazil':'sim','spatial_support':'ponto de estação meteorológica','spatial_resolution':'pontual','temporal_coverage':'janela operacional dos últimos 90 dias segundo a documentação do serviço','temporal_resolution':'horária','update_frequency':'horária','product_status':'ativo','version_or_collection':'serviço corrente 2026','enumeration_scope':'complete','product_page_url':'https://portal.inmet.gov.br/servicos/esta%C3%A7%C3%B5es-autom%C3%A1ticas','methodology_url':'https://portal.inmet.gov.br/paginas/estacoes','primary_or_derived':'primário','limitations':'Observação pontual não representa automaticamente a condição de todo o município ou célula espacial. Disponibilidade depende do funcionamento e transmissão de cada estação; usar horário UTC e metadados da estação.','last_verified':today},
{'product_id':'DP000524','resource_id':'DR0118','product_name':'INMET — Normais Climatológicas do Brasil 1991–2020','product_acronym':'Normais 1991–2020','product_family':'normais climatológicas','product_kind':'indicator_family','product_description':'Valores climatológicos normais de variáveis meteorológicas calculados para 1991–2020 segundo critérios recomendados pela Organização Meteorológica Mundial, com tabelas e mapas por variável.','research_areas':'Clima e Ciências Atmosféricas | Ciências Ambientais e Ecologia','keywords':'normais climatológicas | 1991-2020 | temperatura | precipitação | umidade | vento | pressão | insolação | evaporação','geographic_coverage':'Brasil — estações e produtos climatológicos do INMET','covers_brazil':'sim','spatial_support':'estação e sínteses/mapas climatológicos conforme variável','spatial_resolution':'varia por tabela/mapa e conjunto de estações','temporal_coverage':'1991-01-01 a 2020-12-31','temporal_resolution':'mensal | anual | decendial e estatísticas específicas conforme variável','update_frequency':'por período climatológico/atualização metodológica','product_status':'ativo','version_or_collection':'Normais Climatológicas 1991–2020, lançadas em 2022','enumeration_scope':'complete','product_page_url':'https://portal.inmet.gov.br/normais','methodology_url':'https://portal.inmet.gov.br/servicos/normais-climatol%C3%B3gicas','primary_or_derived':'derivado','limitations':'Normal climatológica é estatística de referência de longo período, não observação do tempo presente nem projeção climática futura. Cobertura e disponibilidade de variáveis dependem das estações e critérios de cálculo.','last_verified':today},
{'product_id':'DP000525','resource_id':'DR0118','product_name':'INMET — Catálogo de Estações Automáticas','product_acronym':'Catálogo Automáticas','product_family':'metadados de estações meteorológicas','product_kind':'catalog','product_description':'Catálogo oficial das estações meteorológicas automáticas do INMET, disponibilizado para download em CSV.','research_areas':'Clima e Ciências Atmosféricas | Infraestruturas e Ciência de Dados','keywords':'estações automáticas | catálogo | metadados | coordenadas | INMET','geographic_coverage':'Brasil','covers_brazil':'sim','spatial_support':'ponto de estação e metadados cadastrais','spatial_resolution':'pontual','temporal_coverage':'cadastro corrente; histórico operacional depende da estação','temporal_resolution':'não aplicável; metadado cadastral','update_frequency':'conforme manutenção da rede','product_status':'ativo','version_or_collection':'catálogo corrente 2026','enumeration_scope':'complete','product_page_url':'https://portal.inmet.gov.br/paginas/catalogoaut','methodology_url':'https://portal.inmet.gov.br/paginas/estacoes','primary_or_derived':'primário','limitations':'Catálogo descreve estações e não contém, por si só, a série observacional completa. Status e disponibilidade podem mudar; coordenadas/metadados devem ser associados à estação correta no período analisado.','last_verified':today},
{'product_id':'DP000526','resource_id':'DR0118','product_name':'INMET — Catálogo de Estações Convencionais','product_acronym':'Catálogo Convencionais','product_family':'metadados de estações meteorológicas','product_kind':'catalog','product_description':'Catálogo oficial das estações meteorológicas convencionais do INMET, disponibilizado para download em CSV.','research_areas':'Clima e Ciências Atmosféricas | Infraestruturas e Ciência de Dados','keywords':'estações convencionais | catálogo | metadados | coordenadas | INMET','geographic_coverage':'Brasil','covers_brazil':'sim','spatial_support':'ponto de estação e metadados cadastrais','spatial_resolution':'pontual','temporal_coverage':'cadastro corrente; histórico operacional depende da estação','temporal_resolution':'não aplicável; metadado cadastral','update_frequency':'conforme manutenção da rede','product_status':'ativo','version_or_collection':'catálogo corrente 2026','enumeration_scope':'complete','product_page_url':'https://portal.inmet.gov.br/paginas/catalogoman','methodology_url':'https://portal.inmet.gov.br/paginas/estacoes','primary_or_derived':'primário','limitations':'Catálogo de estações não equivale aos dados observados. Estações convencionais possuem práticas, horários e continuidade próprios; verificar metadados e disponibilidade da série antes de comparar com estações automáticas.','last_verified':today},
{'product_id':'DP000527','resource_id':'DR0118','product_name':'INMET — Avisos Meteorológicos','product_acronym':'Avisos INMET','product_family':'avisos de tempo severo','product_kind':'data_service','product_description':'Serviço oficial de avisos meteorológicos emitidos pelo INMET, com fenômeno, área de abrangência, severidade e período de validade; em 2026 a interface passou a organizar avisos por dia com horizonte de até cinco dias.','research_areas':'Clima e Ciências Atmosféricas | Ciências Ambientais e Ecologia | Planejamento Territorial e Políticas Públicas','keywords':'avisos meteorológicos | tempo severo | tempestade | chuva intensa | onda de calor | baixa umidade | risco','geographic_coverage':'Brasil','covers_brazil':'sim','spatial_support':'área de abrangência do aviso','spatial_resolution':'conforme polígono/área do aviso','temporal_coverage':'serviço corrente; histórico depende da interface e arquivo disponível','temporal_resolution':'evento/aviso','update_frequency':'diária e conforme emissão/atualização do aviso','product_status':'ativo','version_or_collection':'interface atualizada em 2026-06-09; horizonte de até 5 dias','enumeration_scope':'complete','product_page_url':'https://alertas2.inmet.gov.br/','methodology_url':'https://portal.inmet.gov.br/noticias/inmet-aprimora-interface-de-avisos-meteorol%C3%B3gicos','primary_or_derived':'derivado','limitations':'Aviso é produto de análise/previsão de risco meteorológico e não observação de impacto ocorrido. Severidade, área e validade podem ser atualizadas; não interpretar ausência de aviso como ausência garantida de fenômeno local.','last_verified':today}
]

dists=[
{'distribution_id':'DD000543','product_id':'DP000522','distribution_name':'INMET — Dados Históricos Anuais — downloads por ano','access_url':'https://portal.inmet.gov.br/dadoshistoricos','format':'ZIP/CSV conforme ano e pacote','access_protocol':'HTTPS download','access_tool':'navegador web','free_download':'sim','authentication_required':'não','access_conditions':'seleção por ano; preservar estação, unidades e cabeçalhos dos arquivos','license':'não localizada de forma inequívoca no nível do arquivo','provider_attribution_required':'sim','subset_support':'por ano e estação dentro dos pacotes','notes':'O portal lista anos 2000–2026 no estado auditado; 2026 aparece como parcial e deve ser tratado como tal.','last_verified':today},
{'distribution_id':'DD000544','product_id':'DP000523','distribution_name':'INMET — Estações Automáticas — tabela operacional','access_url':'https://tempo.inmet.gov.br/','format':'tabela/consulta web','access_protocol':'HTTPS','access_tool':'navegador web','free_download':'parcial','authentication_required':'não','access_conditions':'consulta operacional; documentação informa atualização horária e janela recente','license':'não localizada de forma inequívoca','provider_attribution_required':'sim','subset_support':'por estação/local e período oferecido pela interface','notes':'Produto operacional; para séries longas utilizar a distribuição histórica e registrar UTC.','last_verified':today},
{'distribution_id':'DD000545','product_id':'DP000524','distribution_name':'INMET — Normais Climatológicas 1991–2020 — tabelas e mapas','access_url':'https://portal.inmet.gov.br/normais','format':'tabelas/arquivos e mapas conforme variável','access_protocol':'HTTPS','access_tool':'navegador web','free_download':'sim','authentication_required':'não','access_conditions':'seleção por período climatológico e variável','license':'não localizada de forma inequívoca no nível do arquivo','provider_attribution_required':'sim','subset_support':'por variável, estação/período e produto climatológico','notes':'Inclui temperatura, precipitação, umidade, vento, pressão, insolação, evaporação e outras estatísticas conforme disponibilidade.','last_verified':today},
{'distribution_id':'DD000546','product_id':'DP000525','distribution_name':'INMET — Catálogo de Estações Automáticas — CSV','access_url':'https://portal.inmet.gov.br/paginas/catalogoaut','format':'CSV','access_protocol':'HTTPS download','access_tool':'navegador web','free_download':'sim','authentication_required':'não','access_conditions':'download público','license':'não localizada de forma inequívoca no nível do arquivo','provider_attribution_required':'sim','subset_support':'catálogo completo; filtrar localmente','notes':'Metadados cadastrais das estações automáticas; não contém a série meteorológica histórica.','last_verified':today},
{'distribution_id':'DD000547','product_id':'DP000526','distribution_name':'INMET — Catálogo de Estações Convencionais — CSV','access_url':'https://portal.inmet.gov.br/paginas/catalogoman','format':'CSV','access_protocol':'HTTPS download','access_tool':'navegador web','free_download':'sim','authentication_required':'não','access_conditions':'download público','license':'não localizada de forma inequívoca no nível do arquivo','provider_attribution_required':'sim','subset_support':'catálogo completo; filtrar localmente','notes':'Metadados cadastrais das estações convencionais; não contém a série meteorológica histórica.','last_verified':today},
{'distribution_id':'DD000548','product_id':'DP000527','distribution_name':'INMET — Avisos Meteorológicos — portal operacional','access_url':'https://alertas2.inmet.gov.br/','format':'visualização web e dados do aviso conforme interface','access_protocol':'HTTPS','access_tool':'navegador web','free_download':'parcial','authentication_required':'não','access_conditions':'consulta pública; avisos são dinâmicos e podem ser atualizados','license':'não localizada de forma inequívoca no nível do recurso','provider_attribution_required':'sim','subset_support':'por dia, fenômeno e área conforme interface','notes':'Desde 2026-06-09 a interface organiza avisos por dia e pode apresentar horizonte de até cinco dias.','last_verified':today}
]

if source['resource_id'] not in rids:
    if any(x.get('homepage_url')==source['homepage_url'] for x in rs): raise SystemExit('INMET already cataloged under another resource')
    append(R,[source])
add=[]
for p in products:
    if p['product_id'] in pids: continue
    if p['product_page_url'] in urls: raise SystemExit('duplicate product URL: '+p['product_page_url'])
    add.append(p)
if add: append(P,add)
addd=[d for d in dists if d['distribution_id'] not in dids]
if addd: append(D,addd)

reg=json.loads(B.read_text(encoding='utf-8')); reg['reviewed_at']=today
p0=next(t for t in reg['tiers'] if t['priority_tier']=='P0')
if 'DR0118' not in p0['resource_ids']: p0['resource_ids'].append('DR0118')
B.write_text(json.dumps(reg,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

_,rs2=read(R); _,ps2=read(P); _,ds2=read(D)
assert len({x['resource_id'] for x in rs2})==len(rs2)
assert len({x['product_id'] for x in ps2})==len(ps2)
assert len({x['distribution_id'] for x in ds2})==len(ds2)
RIDS={x['resource_id'] for x in rs2}; PIDS={x['product_id'] for x in ps2}
assert all(x['resource_id'] in RIDS for x in ps2)
assert all(x['product_id'] in PIDS for x in ds2)
assert all(f'DP{i:06d}' in PIDS for i in range(522,528))
DIDS={x['distribution_id'] for x in ds2}; assert all(f'DD{i:06d}' in DIDS for i in range(543,549))
print(f'Read-back counts: {len(rs2)} resources | {len(ps2)} products | {len(ds2)} distributions')
