import csv, json
from pathlib import Path
TODAY='2026-08-19'
rp=Path('data/data_resources.csv'); pp=Path('data/data_products.csv'); dp=Path('data/product_distributions.csv')

def read(path):
    with path.open(encoding='utf-8', newline='') as f: return list(csv.DictReader(f))

def next_id(rows,key,prefix):
    m=max(int(r[key].replace(prefix,'')) for r in rows)+1
    return f'{prefix}{m:04d}'

resources=read(rp); products=read(pp); dists=read(dp)
existing_names={r['resource_name'] for r in resources}
existing_purls={r['product_page_url'] for r in products}
if 'Atlas da Violência — Ipea/FBSP' in existing_names or 'Mapa das Organizações da Sociedade Civil — Ipea' in existing_names:
    raise SystemExit('Target source already materialized; aborting to avoid duplication')
rid1=next_id(resources,'resource_id','DR'); rid2=f'DR{int(rid1[2:])+1:04d}'
new_resources=[
{'resource_id':rid1,'resource_name':'Atlas da Violência — Ipea/FBSP','acronym':'Atlas da Violência','official_identity':'Plataforma e série de estudos e indicadores sobre violência no Brasil','description':'Plataforma do Ipea em parceria com o Fórum Brasileiro de Segurança Pública para consulta de séries, indicadores e estudos sobre violência, homicídios e segurança pública no Brasil.','homepage_url':'https://www.ipea.gov.br/atlasviolencia/','data_access_url':'https://www.ipea.gov.br/atlasviolencia/dados-series/158','research_areas':'Planejamento Territorial e Políticas Públicas | Infraestruturas e Ciência de Dados','keywords':'violência | homicídios | segurança pública | mortalidade | municípios | indicadores','data_product_types':'séries | indicadores | mapas | relatórios','data_formats':'visualização web | tabelas | PDF; varia conforme produto','visualization_types':'mapa interativo | gráficos | tabelas','geographic_coverage':'nacional — Brasil; estados e municípios conforme produto','covers_brazil':'sim','spatial_resolution':'município | UF | Brasil; varia conforme indicador','temporal_coverage':'séries históricas e edições anuais; varia conforme indicador','temporal_resolution':'anual; varia conforme indicador','data_sources':'SIM/MS | bases de segurança pública | estimativas e métodos do Atlas','free_download':'parcial','access_conditions':'consulta pública; downloads e publicações variam por produto','programmatic_access':'desconhecido','access_protocols':'HTTPS','authentication_required':'não','access_documentation_url':'https://www.ipea.gov.br/atlasviolencia/','license':'verificar por produto/publicação','institutional_status':'público / parceria institucional','owner_or_manager':'Ipea / Fórum Brasileiro de Segurança Pública','academic_uses':'Analisar padrões territoriais e temporais de violência letal, homicídios e indicadores de segurança pública.','limitations':'Indicadores combinam registros administrativos e, em alguns produtos, estimativas modeladas; subnotificação, classificação da causa e diferenças territoriais exigem leitura metodológica. Homicídios estimados não equivalem aos registros brutos do SIM.','academic_evidence_type':'documentação técnica oficial','academic_evidence_url':'https://repositorio.ipea.gov.br/collections/6f2ea994-fdfe-496b-8b21-4a0175c4bd8e','academic_evidence_note':'O Ipea documenta o Atlas da Violência e a edição 2025, inclusive o método de homicídios estimados.','verification_url':'https://www.ipea.gov.br/atlasviolencia/','last_verified':TODAY},
{'resource_id':rid2,'resource_name':'Mapa das Organizações da Sociedade Civil — Ipea','acronym':'Mapa das OSC','official_identity':'Plataforma pública de dados sobre organizações da sociedade civil no Brasil','description':'Plataforma mantida pelo Ipea que integra e disponibiliza informações cadastrais, territoriais, de atuação, vínculos e projetos de organizações da sociedade civil brasileiras.','homepage_url':'https://mapaosc.ipea.gov.br/','data_access_url':'https://mapaosc.ipea.gov.br/listar-oscs/244','research_areas':'Planejamento Territorial e Políticas Públicas | Infraestruturas e Ciência de Dados','keywords':'organizações da sociedade civil | OSC | associações | fundações | participação social | território','data_product_types':'cadastro integrado | mapa | consulta | indicadores','data_formats':'visualização web | registros estruturados; formatos de exportação variam','visualization_types':'mapa interativo | busca tabular | fichas de organizações','geographic_coverage':'nacional — Brasil','covers_brazil':'sim','spatial_resolution':'organização | município | UF; conforme campo','temporal_coverage':'cadastro corrente com históricos variáveis conforme fonte integrada','temporal_resolution':'cadastral/administrativa; varia','data_sources':'CNPJ e outros registros administrativos | informações autodeclaradas/integradas pela plataforma','free_download':'parcial','access_conditions':'consulta pública; disponibilidade de exportação varia por módulo','programmatic_access':'desconhecido','access_protocols':'HTTPS','authentication_required':'não','access_documentation_url':'https://mapaosc.ipea.gov.br/','license':'verificar no módulo/recurso','institutional_status':'público','owner_or_manager':'Instituto de Pesquisa Econômica Aplicada — Ipea','academic_uses':'Mapear distribuição, perfil institucional, atuação, projetos e vínculos de organizações da sociedade civil e apoiar estudos de participação social e políticas públicas.','limitations':'Integra registros administrativos e informações com completude desigual; cadastro não certifica atividade efetiva, qualidade institucional, impacto social ou atualização uniforme de todos os campos.','academic_evidence_type':'documentação oficial','academic_evidence_url':'https://mapaosc.ipea.gov.br/','academic_evidence_note':'A plataforma pública permite localizar e detalhar OSCs no território brasileiro e expõe atributos institucionais e de atuação provenientes de diferentes bases.','verification_url':'https://mapaosc.ipea.gov.br/','last_verified':TODAY}
]
with rp.open('a',encoding='utf-8',newline='') as f:
    w=csv.DictWriter(f,fieldnames=list(resources[0].keys()),lineterminator='\n')
    for r in new_resources: w.writerow(r)

prows=read(pp)
pids=[]; tmp=prows[:]
for _ in range(4):
    p=next_id(tmp,'product_id','DP'); pids.append(p); tmp.append({'product_id':p})
new_products=[
{'product_id':pids[0],'resource_id':rid1,'product_name':'Atlas da Violência — dados e séries históricas','product_acronym':'Atlas — Dados e Séries','product_family':'indicadores de violência e homicídios','product_kind':'indicator_family','product_description':'Conjunto de séries e indicadores disponibilizados pelo Atlas da Violência para consulta territorial e temporal de violência e homicídios no Brasil.','research_areas':'Planejamento Territorial e Políticas Públicas | Infraestruturas e Ciência de Dados','keywords':'violência | homicídios | séries históricas | segurança pública | indicadores','geographic_coverage':'Brasil — recortes nacional, estadual e municipal conforme indicador','covers_brazil':'sim','spatial_support':'agregado territorial conforme série','spatial_resolution':'Brasil | UF | município; varia conforme indicador','temporal_coverage':'histórico variável conforme série','temporal_resolution':'anual; varia conforme série','update_frequency':'conforme atualização do Atlas','product_status':'ativo','version_or_collection':'portal corrente consultado em 2026','enumeration_scope':'external_index','product_page_url':'https://www.ipea.gov.br/atlasviolencia/dados-series/158','methodology_url':'https://www.ipea.gov.br/atlasviolencia/','primary_or_derived':'derivado','limitations':'Séries podem combinar registros administrativos e estimativas; cada indicador deve ser usado com sua definição, fonte e período.','last_verified':TODAY},
{'product_id':pids[1],'resource_id':rid1,'product_name':'Atlas da Violência 2025 — retrato dos municípios e homicídios estimados','product_acronym':'Atlas da Violência 2025','product_family':'edição municipal do Atlas da Violência','product_kind':'indicator_family','product_description':'Edição 2025, com ano-base 2023, dedicada à distribuição municipal da violência letal e aos homicídios estimados, incluindo análise regional do crime organizado.','research_areas':'Planejamento Territorial e Políticas Públicas | Infraestruturas e Ciência de Dados','keywords':'Atlas da Violência 2025 | municípios | homicídios estimados | crime organizado | violência letal','geographic_coverage':'Brasil — municípios e regiões','covers_brazil':'sim','spatial_support':'município | região','spatial_resolution':'municipal e regional','temporal_coverage':'ano-base 2023; análises históricas complementares variam','temporal_resolution':'anual/edição','update_frequency':'por edição do Atlas','product_status':'ativo','version_or_collection':'Atlas da Violência 2025 — ano-base 2023','enumeration_scope':'complete','product_page_url':'https://repositorio.ipea.gov.br/collections/6f2ea994-fdfe-496b-8b21-4a0175c4bd8e','methodology_url':'https://www.ipea.gov.br/atlasviolencia/','primary_or_derived':'derivado','limitations':'Homicídios estimados incorporam mortes violentas com causa indeterminada classificadas por técnica de machine learning; não são contagem administrativa bruta. O relatório é uma edição analítica.','last_verified':TODAY},
{'product_id':pids[2],'resource_id':rid2,'product_name':'Mapa das OSC — cadastro e consulta nacional de organizações','product_acronym':'Cadastro Mapa OSC','product_family':'cadastro integrado de organizações da sociedade civil','product_kind':'dataset_series','product_description':'Base integrada e consulta pública de organizações da sociedade civil, com identificação, localização, natureza jurídica, áreas de atuação e outros atributos disponíveis por organização.','research_areas':'Planejamento Territorial e Políticas Públicas | Infraestruturas e Ciência de Dados','keywords':'OSC | organizações da sociedade civil | cadastro | CNPJ | participação social','geographic_coverage':'Brasil','covers_brazil':'sim','spatial_support':'organização | endereço | município | UF','spatial_resolution':'registro de organização e agregações territoriais','temporal_coverage':'cadastro corrente; históricos dependem dos campos/fontes','temporal_resolution':'cadastral','update_frequency':'conforme atualização das bases integradas','product_status':'ativo','version_or_collection':'consulta corrente em 2026','enumeration_scope':'complete','product_page_url':'https://mapaosc.ipea.gov.br/listar-oscs/244','methodology_url':'https://mapaosc.ipea.gov.br/','primary_or_derived':'derivado','limitations':'Integra bases administrativas e informações com completude variável; presença no cadastro não comprova atividade atual, impacto, regularidade ou preenchimento completo.','last_verified':TODAY},
{'product_id':pids[3],'resource_id':rid2,'product_name':'Mapa das OSC — visualização territorial e fichas institucionais','product_acronym':'Mapa OSC — Mapa','product_family':'exploração territorial de OSCs','product_kind':'data_service','product_description':'Serviço web para explorar a distribuição territorial das OSCs e abrir fichas institucionais com atributos cadastrais, atuação, vínculos, projetos e recursos quando disponíveis.','research_areas':'Planejamento Territorial e Políticas Públicas | Infraestruturas e Ciência de Dados','keywords':'OSC | mapa | território | fichas institucionais | projetos | participação social','geographic_coverage':'Brasil','covers_brazil':'sim','spatial_support':'organização e agregação territorial','spatial_resolution':'endereço/município conforme registro','temporal_coverage':'corrente com históricos variáveis','temporal_resolution':'consulta corrente','update_frequency':'conforme plataforma','product_status':'ativo','version_or_collection':'plataforma corrente em 2026','enumeration_scope':'external_index','product_page_url':'https://mapaosc.ipea.gov.br/mapa/3526902','methodology_url':'https://mapaosc.ipea.gov.br/','primary_or_derived':'derivado','limitations':'A visualização depende da geocodificação e completude dos cadastros; mapa e ficha não constituem verificação independente de atuação, recursos ou resultados da organização.','last_verified':TODAY}
]
for r in new_products:
    if r['product_page_url'] in existing_purls: raise SystemExit('product URL already exists: '+r['product_page_url'])
with pp.open('a',encoding='utf-8',newline='') as f:
    w=csv.DictWriter(f,fieldnames=list(prows[0].keys()),lineterminator='\n')
    for r in new_products: w.writerow(r)

drows=read(dp); dids=[]; tmp=drows[:]
for _ in range(4):
    d=next_id(tmp,'distribution_id','DD'); dids.append(d); tmp.append({'distribution_id':d})
urls=['https://www.ipea.gov.br/atlasviolencia/dados-series/158','https://repositorio.ipea.gov.br/collections/6f2ea994-fdfe-496b-8b21-4a0175c4bd8e','https://mapaosc.ipea.gov.br/listar-oscs/244','https://mapaosc.ipea.gov.br/mapa/3526902']
names=['Atlas da Violência — consulta de dados e séries','Atlas da Violência 2025 — publicação e materiais','Mapa das OSC — consulta nacional','Mapa das OSC — mapa e fichas']
fmts=['web/tabelas; varia por série','HTML/PDF; materiais associados conforme publicação','aplicação web / registros estruturados','aplicação web / mapa interativo']
new_d=[]
for i in range(4):
    new_d.append({'distribution_id':dids[i],'product_id':pids[i],'distribution_name':names[i],'access_url':urls[i],'format':fmts[i],'access_protocol':'HTTPS','access_tool':'navegador web','free_download':'parcial' if i!=1 else 'sim','authentication_required':'não','access_conditions':'consulta pública; disponibilidade de download varia por recurso','license':'verificar no recurso/publicação','provider_attribution_required':'sim','subset_support':'por indicador/território' if i==0 else ('por publicação/material' if i==1 else 'por organização/território'),'notes':'Usar a definição, fonte, período e limitações documentadas no produto; não generalizar completude ou licença entre módulos.','last_verified':TODAY})
with dp.open('a',encoding='utf-8',newline='') as f:
    w=csv.DictWriter(f,fieldnames=list(drows[0].keys()),lineterminator='\n')
    for r in new_d: w.writerow(r)

bp=Path('data/brazil_scope_priorities.json'); obj=json.loads(bp.read_text(encoding='utf-8')); obj['reviewed_at']=TODAY
p0=next(t for t in obj['tiers'] if t['priority_tier']=='P0')['resource_ids']
for rid in (rid1,rid2):
    if rid not in p0: p0.append(rid)
bp.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('APPENDED',rid1,rid2,*pids,*dids)
